
<div class="ionix">

    	<div class="bloq1">
        	<div class="tabAll">
            	<div class="tabIn taC bBlue colorfff t30 ff2 tU">
                	Título del Informe
                </div>
            </div>
        </div>

		<div class="bloqCont allion row m0">
        	<div class="col-sm-3 col-xs-12 allion p0">
				<div class="tab nodoa"><div class="tabIn bccc t18 ff2 p20">Empresario de mi red</div></div>
                <div class="tab nodoa"><a class="tabIn beee t20 cP ff0 p1020 color666 bBS1">Nivel 1</a></div>
                <div class="tab nodoa"><a class="tabIn beee t20 cP ff0 p1020 color666 bBS1">Nivel 2</a></div>
                <div class="tab nodoa"><a class="tabIn beee t20 cP ff0 p1020 color666 bBS1">Nivel 3</a></div>
                <div class="tab nodoa"><a class="tabIn beee t20 cP ff0 p1020 color666 bBS1">Nivel 4</a></div>
                <div class="tab nodoa"><a class="tabIn beee t20 cP ff0 p1020 color666 bBS1">Nivel 5</a></div>
                <div class="tab nodoa"><a class="tabIn beee t20 cP ff0 p1020 color666 bBS1">Nivel 6</a></div>
                <div class="tab nodoa"><div class="tabIn bccc t18 ff2 p20">Clientes de mi red</div></div>
                <div class="tab nodoa"><a class="tabIn beee t20 cP ff0 p1020 color666 bBS1">Mis Clientes</a></div>
                <div class="tab nodoa"><a class="tabIn beee t20 cP ff0 p1020 color666 bBS1">Clientes de mis empresarios</a></div>
            </div>

            <div class="col-sm-9 col-xs-12 allion p0" style=" border-left:solid 1px #333;">
            	<div class="bloqIn allionIn">


                    <div class=" well p30 table-responsive">

                        <table class="table">
                          <thead>
                            <tr>
                              <th>Nombre</th>
                              <th>Grupo</th>
                              <th>IVA</th>
                              <th>$ Comisionable</th>
                              <th>% Comisión</th>
                              <th>Vlr Comisión</th>
                            </tr>
                          </thead>
                          <tbody>

                          <?php for($h=0; $h<2; $h++){ ?>
                                <tr>
                                  <td>William Aragón</td>
                                  <td>Singular</td>
                                  <td>0.6 %</td>
                                  <td>80 %</td>
                                  <td>75 %</td>
                                  <td>$2'550.000</td>
                                </tr>
                                <tr>
                                  <td>Jhon James Montaño</td>
                                  <td>Escalas</td>
                                  <td>0.6 %</td>
                                  <td>80 %</td>
                                  <td>75 %</td>
                                  <td>$2'550.000</td>
                                </tr>
                            <?php } ?>

                          </tbody>
                        </table>

                    </div>


                </div>

                <div class="bloqEnd">
                    <div class="tabAll">
                        <div class="tabIn taR colorfff t30 ff0 tU pLR40">
                            TOTAL: <strong>$752'954.000</strong>
                        </div>
                    </div>
                </div>

            </div>
        </div>


</div>






<!--
<?php if ( empty($this->Productos ) ) :?>

    <div class='text-center'>
        <br>
        <h4>No has agregado productos a tu sección favoritos</h4>
    </div>

<?php else :?>
<table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Img</th>
                <th>Producto</th>
                <th>Opciones</th>
            </tr>
        </thead>


        <tbody>
            <?php foreach ( $this->Productos as $Producto ) : ?>
                <?php
                    $idorden_nv_0          = $Producto['idorden_nv_0'];
                    $idproducto            = $Producto['idproducto'];
                    $nom_producto          = trim($Producto['nom_producto']) ;
                    $nombre_imagen         = BASE_IMG_PRODUCTOS_50x50. $Producto['nombre_imagen'] ;
                    $idtercero             = Session::Get('idtercero');
                ?>

                <tr>
                	<td width="120"><img  src="<?= $nombre_imagen ;?>"  /></td>
                    <td style="vertical-align:middle">  <?= $nom_producto  ; ?> </td>
                    <td style="vertical-align:middle" class="taC">
                    	<a href="<?= BASE_URL ;?>productos/vista_ampliada/<?= $idproducto ?>/<?=  $idorden_nv_0 ;?>" class="btn btn-info">Ver Producto</a>
                     <a href="#" class="btn btn-danger" id='borrar_producto_favoritos'
                        idtercero = <?= $idtercero ;?>
                        idproducto = <?= $idproducto ;?>
                        nomproducto ='<?= $nom_producto  ;?>'
                     >
                     Borrar</a>
                    </td>
                </tr>
            <?php endforeach ;?>

        </tbody>

    </table>

 <?php endif ;?>

-->
