
<?php
	//Debug::Mostrar( $this->Productos );
?>

<br><br>
<table class="table table-bordered table-hover">
        <thead>

            <tr>
                <th>Img</th>
                <th>Producto</th>
                <th>Opciones</th>
            </tr>
        </thead>

        <tbody>
            <tr>
            	<td width="120"><img  src="../public/images/categorias_index/9.jpg" width="100" /></td>
                <td style="vertical-align:middle">
                	Gas pimienta super dummer<br>
                    <small>
                    	<a href="#" class="aS"><img src="../public/images/tienda/arr3.png"> Catgoría</a> &nbsp;&nbsp;
                        <a href="#" class="aS"><img src="../public/images/tienda/arr3.png"> Subcategoría</a>&nbsp;&nbsp;
                        <a href="#" class="aS"><img src="../public/images/tienda/arr3.png"> Marca</a>&nbsp;&nbsp;
                     </small>
                </td>
                <td style="vertical-align:middle" class="taC">
                	<a href="#" class="btn btn-info">Ver Producto</a>
                </td>
            </tr>
        </tbody>
    </table>