
<?php if ( empty($this->Productos ) ) :?>

    <div class='text-center'>
        <br>
        <h4>No has agregado productos a tu sección favoritos</h4>
    </div>

<?php else :?>
<table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Img</th>
                <th>Producto</th>
                <th>Opciones</th>
            </tr>
        </thead>


        <tbody>
            <?php foreach ( $this->Productos as $Producto ) : ?>
                <?php
                    $idorden_nv_0          = $Producto['idorden_nv_0'];
                    $idproducto            = $Producto['idproducto'];
                    $nom_producto          = trim($Producto['nom_producto']) ;
                    $nombre_imagen         = BASE_IMG_PRODUCTOS_50x50. $Producto['nombre_imagen'] ;
                    $idtercero             = Session::Get('idtercero');
                ?>

                <tr>
                	<td width="120"><img  src="<?= $nombre_imagen ;?>"  /></td>
                    <td style="vertical-align:middle">  <?= $nom_producto  ; ?> </td>
                    <td style="vertical-align:middle" class="taC">
                    	<a href="<?= BASE_URL ;?>productos/vista_ampliada/<?= $idproducto ?>/<?=  $idorden_nv_0 ;?>" class="btn btn-info">Ver Producto</a>
                     <a href="#" class="btn btn-danger" id='borrar_producto_favoritos'
                        idtercero = <?= $idtercero ;?>
                        idproducto = <?= $idproducto ;?>
                        nomproducto ='<?= $nom_producto  ;?>'
                     >
                     Borrar</a>
                    </td>
                </tr>
            <?php endforeach ;?>

        </tbody>

    </table>

 <?php endif ;?>


