

<div class="ionix">
    <div class="general">
    	<div class="contenido-index mb30 pAA30">

			<div class="row">

 				<!-- CATEGORIAS MARCAS -->
                <div id="menu-izq-otros-productos" class="col-sm-3 col-xs-12 colCatMar">
                    <div class="panel-group" id="accordion">
						<?php include (APPLICATION_SECTIONS .'otros_productos_categorias.php');?><!--Llamado Al Menu-Industrial -->
                        <?php include (APPLICATION_SECTIONS .'otros_productos_marcas.php');?><!--Llamado Al Menu-Industrial -->
                        <?php include (APPLICATION_SECTIONS .'otros_productos_empresas.php');?><!--Llamado Al Menu-Industrial -->
                    </div>
                </div>


        		<!-- INICIA PRESENTACIÓN DE PRODUCTOS -->

                <div id="contenido-productos" class="col-sm-9 col-xs-12 "   >
                
                	
                    
                    <?php
					
					
						if( Session::Get('CEO_CATEGORIA_INDUSTRIAL' ) == 1) {
							
							echo '<img src="../../../../public/images/banners/1.png" />';
							
						} else if( Session::Get('CEO_CATEGORIA_INDUSTRIAL' ) == 2) {
							
							echo '<img src="../../../../public/images/banners/2.png" />';
							
						} else if( Session::Get('CEO_CATEGORIA_INDUSTRIAL' ) == 3) {
							
							echo '<img src="../../../../public/images/banners/3.png" />';
							
						} else if( Session::Get('CEO_CATEGORIA_INDUSTRIAL' ) == 4) {
							
							echo '<img src="../../../../public/images/banners/4.png" />';
							
						} else if( Session::Get('CEO_CATEGORIA_INDUSTRIAL' ) == 5) {
							
							echo '<img src="../../../../public/images/banners/5.png" />';
							
						} else if( Session::Get('CEO_CATEGORIA_INDUSTRIAL' ) == 6) {
							
							echo '<img src="../../../../public/images/banners/6.png" />';
							
						} else if( Session::Get('CEO_CATEGORIA_INDUSTRIAL' ) == 7) {
							
							echo '<img src="../../../../public/images/banners/7.png" />';
							
						} else if( Session::Get('CEO_CATEGORIA_INDUSTRIAL' ) == 8) {
							
							echo '<img src="../../../../public/images/banners/8.png" />';
							
						}
					
					
					
                    	include (APPLICATION_SECTIONS .'paginador_prod_x_pagina.php');

                        foreach ($this->Productos_Pagina as $Productos){
                            $mostrar_imagen_varias_referencias=true;
                            include (APPLICATION_CODS . 'campos_productos.php');
                    ?>
                         <?php if ( $en_oferta == 1 ) : ?> <div class="artOpt artPor4 oferta">
                            <?php else :?>                 <div class="artOpt artPor4">
                         <?php endif ;?>
                         <?php include (APPLICATION_SECTIONS . 'productos_listado.php');?>
                          </div>

                    <?php } ?>
                    <br style="clear:both;" /><br /><br />
                    <?php if(isset($this->Paginacion)) echo $this->Paginacion; ?>
                </div>

			</div>


        </div>
    </div>
</div>







