<div class="ionix">
    <div class="general">    
    	<div class="contenido-index mb30">
        	<br /><br />
    
            <!--PORDUCTOS CATEGORIAS MARCAS -->
            <!--CONTENIDO GENERAL = TODA LA PAGINA -->

			<div class="row">
 
                <div id="menu-izq-otros-productos" class="col-sm-3 col-xs-3 colCatMar">
                    <div class="panel-group" id="accordion">
						<?php include (APPLICATION_SECTIONS .'otros_productos_categorias.php');?><!--Llamado Al Menu-Industrial -->
                        <?php include (APPLICATION_SECTIONS .'otros_productos_marcas.php');?><!--Llamado Al Menu-Industrial -->
                        <?php include (APPLICATION_SECTIONS .'otros_productos_empresas.php');?><!--Llamado Al Menu-Industrial -->
                    </div><!-- class="panel-group" id="accordion" -->
                </div> <!-- col-lg-3  col-md-3 col-sm-3 columna_categorias-marcas-->


        		<!-- INICIA PRESENTACIÓN DE PRODUCTOS -->				
                <div id="contenido-productos" class="col-sm-9 col-sm-9">
                    <?php
                    	include (APPLICATION_SECTIONS .'paginador_prod_x_pagina.php');
											
                        foreach ($this->Productos_Pagina as $Productos){
                            $mostrar_imagen_varias_referencias=true;
                            include (APPLICATION_CODS . 'campos_productos.php');
                    ?>
                            <div class="artOpt artPor4">
                                <?php include (APPLICATION_SECTIONS . 'productos_listado.php');?>
                            </div><!--Articulos col-lg-3 col-md-3 col-sm-3 col-xs-3" id="articulos -->
                    
                    <?php } ?>
                    
                    <?php if(isset($this->Paginacion)) echo $this->Paginacion; ?>
                </div><!--Division De la Pagina = Producto -->

			</div> <!-- Fin Row -->


        </div>
    </div>
</div>







