



<div id="contenido-productos">
	<div>

		<?php
			include (APPLICATION_SECTIONS .'paginador_prod_x_pagina.php');

			foreach ($this->Productos_Pagina as $Productos) {
				$mostrar_imagen_varias_referencias=true;
				include (APPLICATION_CODS . 'campos_productos.php');
        ?>

         <?php if ( $en_oferta == 1 ) : ?> <div class="artOpt artPor4 oferta">
            <?php else :?>                 <div class="artOpt artPor4">
         <?php endif ;?>
         <?php include (APPLICATION_SECTIONS . 'productos_listado.php');?>
          </div>

        <?php
			} if( isset($this->Paginacion)) echo $this->Paginacion;
		?>

	</div>
</div>
</div>

