
<!--PORDUCTOS CATEGORIAS MARCAS -->
<div class="contenido"><!--CONTENIDO GENERAL = TODA LA PAGINA -->

  <div class="row">

    <div id="menu-izq-otros-productos">
              <div class=" col-lg-3  col-md-3 col-sm-3 columna_categorias-marcas">
                  <div class="panel-group" id="accordion"><!--Contenido de los paneles -->

                 <div class="panel"><!--Panel -->
                    <div class="panel-heading cabezera-panel">
                        <h4 class="panel-title">
                             <a href="#categorias" data-toggle="collapse"   data-parent="#accordion">CATEGORIAS</a>
                        </h4>
                    </div>

                    <div id="categorias" class="panel-collapse collapse in">
                        <div class="panel-body"><!--Contenedor de CATEGORIAS -->

                         <ul class="list-unstyled accordion" id="accordion"><!-- Menu accordion-->
                           <li><!--ASEO DEL HOGAR -->
                              <div class="link"><p>ASEO DEL HOGAR  </p></div><!-- Titulo = ASEO DEL HOGAR -->

                               <ul class="list-unstyled submenu"><!--Contenido -->
                                     <li><a href="#" class="sub-lista">Implementos para el aseo ( 3 )</a></li><!-- Sublistas -->
                               </ul><!--Contenido -->

                           </li><!-- ASEO DEL HOGAR-->

                         </ul><!--Menu accordion -->
                        </div><!--Contenedor de  CATEGORIAS-->
                    </div>
                 </div><!--Panel -->

<!-- //////////////////////////////////////////////////////-Panel- Marcas-////////////////////////////////////////////////////////////// -->


                 <div class="panel"><!--Panel -->
                    <div class="panel-heading  cabezera-panel">
                        <h4 class="panel-title">
                             <a href="#marcas" data-toggle="collapse"   data-parent="#accordion">MARCAS</a>
                        </h4>
                    </div>

                    <div id="marcas" class="panel-collapse collapse ">
                        <div class="panel-body"><!--Contenedor de MARCAS -->

                             <ul class="list-unstyled">
                                 <li><a class="lista-marcas" href="#">ACER ( 2 )</a></li><!-- Sub-lista-->

                                        <!-- Contenido lista -->


                             </ul>
                        </div><!--Contenedor de MARCAS -->
                    </div>
                 </div><!--Panel -->


<!-- //////////////////////////////////////////////////////-Panel- Empresas-////////////////////////////////////////////////////////////// -->


                 <div class="panel"><!--Panel -->
                    <div class="panel-heading  cabezera-panel">
                        <h4 class="panel-title">
                             <a href="#empresas-asociadas" data-toggle="collapse"   data-parent="#accordion">EMPRESAS ASOCIADAS</a>
                        </h4>
                    </div>

                    <div id="empresas-asociadas" class="panel-collapse collapse ">
                        <div class="panel-body"><!--Contenedor de  -->

                            <ul class="list-unstyled">
                                <li><a class="sub-lista-empresas" href="#">EMPRESA 1</a></li>
                            </ul>

                        </div><!--Contenedor de  -->
                    </div>
                 </div><!--Panel -->



                  </div><!--Contenido de los paneles -->
              </div> <!-- col-lg-3  col-md-3 col-sm-3 columna_categorias-marcas-->
    </div> <!-- Fin Menu-izq-otrosproductos-->

        <!-- INICIA PRESENTACIÓN DE PRODUCTOS -->

    <div id="contenido-productos"> <!--Section = Innicio-Presentacion del Producto  CONTENEDOR DE PRDUCTOS -->
      <div  class="esta es..! col-lg-9 col-md-9 col-sm-9">

      </div><!--Division De la Pagina = Producto -->
  </div>


 </div> <!-- Fin Row -->

</div><!-- FIN class="contenido" -->









