<!--
       Estilos Css => Carpeta Css => tron_estilos_productos_tron.css
       Js          => Carpeta Js  =>
 -->



<div class="container">
  <div class="row">
    <!--////////////////////////////////////////////////-Section = Productos//////////////////////////////////////////////////-->
    <!--Contenedor = Presentacion Del Producto //
    Se divide En Presentacion-Producto ,  Fragancias , Accesorios-->
    <div class="col-lg-9 col-md-9 col-sm-9">
      <div class="contenedor_del_producto_presentado"><!--Contenido-Presentacion-Producto-->
       <?php include (APPLICATION_SECTIONS .'productos_tron_ropa.php'); ?>
        <!--Division2-Fragancia , Accesorios-->
          <div id="contenido-productos">
             <div class=" col-lg-9 col-md-9 col-sm-9 section-fragancias-accesorios"><!--Section = Fragancias , Accesorios-->
                <div class=" row"><!--Fragancias-->
                  <p class="titulo_fragancia"> <strong> FRAGANCIAS </strong> </p>
                    <?php include (APPLICATION_SECTIONS .'productos_tron_ropa_fragancias.php'); ?>
                </div><!--Fragancias-->
              <div class=" row">
                  <?php include (APPLICATION_SECTIONS .'productos_tron_ropa_accesorios.php'); ?>
              </div>
            </div><!--Section = Fragancias , Accesorios-->
      </div>
      <!--Precio_varia_segun_la_cantidad -->
      </div>

        <div><!-- Ventana Modal -->
            <?php include (APPLICATION_SECTIONS .'productos_tron_ventana_modal.php'); ?>
        </div>

    </div><!--Fin-Contenedor = Presentacion Del Producto // Se divide En Presentacion-Producto ,  Fragancias , Accesorios-->

<!--Resumen Pedido TRON-->
<div class="col-lg-3 col-md-3 col-sm-3" id="resumen-pedido-tron">
     <?php include (APPLICATION_SECTIONS .'productos_tron_resumen.php'); ?>
</div>



</div>



<!--////////////////////////////////////////////-Anadir-Productos////////////////////////////////////////////////////////-->


<!--Para Incluir mas Productos = Debes llenar los DIV con las clase row -->
<div class="well row"></div>
<div class="well row"></div>
<div class="well row"></div>
<!--Para Incluir mas Productos = Debes llenar los DIV con las clase row -->

</div>
<br>
<br>
<br>


