

<script>
	$(document).ready(function() {

      if (!!$('.ionIIid').offset()) { // make sure ".ionIIid" element exists
         var ionIIidTop = $('.ionIIid').offset().top; // returns number
         $(window).scroll(function(){ // scroll event
          var windowTop = $(window).scrollTop(); // returns number

      if (ionIIidTop < windowTop){
         $('.ionIIid').css({ position: 'fixed', top: 0 });
         $('.carrito-resumen-pedido').css({ position: 'fixed', top: 0 });
          } else {
             $('.ionIIid').css('position','static');
             $('.carrito-resumen-pedido').css('position','static');
          }
       });
      }
	});

</script>





<?php
    include (APPLICATION_SECTIONS .'productos/tron/asignar_precios_individuales.php');
 ?>


<div class="ionix">
	<div class="general mb30 pAA30">

<!--        <div class="titleM1 colorBlue t24 mb30">PRODUCTOS TRON  |  <a href="#carrosmotos" class="colorBlue t12"> CARROS Y MOTOS</a></div> -->

		<div class="reemplllazo"></div>
        <div class="row mb20 beee ionIIid" style="z-index: 100;">

        	<div class="col-sm-3 col-xs-6">
            	<div id="bIONPrd1" class="tab h100 bS1 bIONPrd1">
                	<div class="tabIn">
                        <div class="col-sm-4 col-xs-4 vcenter">
                            <img src="<?= BASE_IMG_PRODUCTOS_TRON ;?>ropa_producto.jpg">
                        </div><!--
                        --><div class="col-sm-8 col-xs-8 vcenter bOrange">
                            <div class="t14 ff2 mb3 colorBlue">Detergente de Ropa</div>
                            <div class="t20 ff1 color000 precio_publico-ocacional">      <?= $text_pv_comprador_ocasional_ropa ;?></div>
                            <div class="t35R ff2 mb3 colorOrange" id="precio-tron-ropa"> <?= $text_pv_tron_ropa ;?></div>
                            <div class="t12 ff0 color666">Precio especial para ti</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-xs-6">
                <div id="bIONPrd3" class="tab h100 bS1">
                    <div class="tabIn">
                        <div class="col-sm-4 col-xs-4 vcenter">
                            <img src="<?= BASE_IMG_PRODUCTOS_TRON ;?>pisos_producto.jpg">
                        </div><!--
                        --><div class="col-sm-8 col-xs-8 vcenter">
                            <div class="t14 ff2 mb3 colorBlue">Limpiador multiusos</div>
                            <div class="t20 ff1 color000"> <?= $text_pv_comprador_ocasional_pisos  ;?> </div>
                            <div class="t35R ff2 mb3 colorOrange" id="precio-tron-pisos"><?= $text_pv_tron_pisos  ;?> </div>
                            <div class="t12 ff0 color666">Precio especial para ti</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-3 col-xs-6">
            	<div id="bIONPrd2" class="tab h100 bS1">
                	<div class="tabIn">
                        <div class="col-sm-4 col-xs-4 vcenter">
                            <img src="<?= BASE_IMG_PRODUCTOS_TRON ;?>banios_producto.jpg">
                        </div><!--
                        --><div class="col-sm-8 col-xs-8 vcenter">
                            <div class="t14 ff2 mb3 colorBlue">Desinfectante de baños</div>
                            <div class="t20 ff1 color000">  <?= $text_pv_comprador_ocasional_banios  ;?> </div>
                            <div class="t35R ff2 mb3 colorOrange" id="precio-tron-banios">  <?= $text_pv_tron_banios  ;?> </div>
                            <div class="t12 ff0 color666">Precio especial para ti</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-3 col-xs-6">
            	<div id="bIONPrd4" class="tab h100 bS1">
                	<div class="tabIn">
                        <div class="col-sm-4 col-xs-4 vcenter">
                            <img src="<?= BASE_IMG_PRODUCTOS_TRON ;?>loza_producto.jpg">
                        </div><!--
                        --><div class="col-sm-8 col-xs-8 vcenter">
                            <div class="t14 ff2 mb3 colorBlue">Lavaloza</div>
                            <div class="t20 ff1 color000"><?= $text_pv_comprador_ocasional_loza ;?> </div>
                            <div class="t35R ff2 mb3 colorOrange" id="precio-tron-loza"><?= $text_pv_tron_loza ;?></div>
                            <div class="t12 ff0 color666">Precio especial para ti</div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="row">

            <?php
            	include (APPLICATION_SECTIONS .'productos_tron_ventana_modal.php');
				$arrIon = array (
					"Todos los Productos",
					"productos/tron/ropa.php",
					"productos/tron/ropa_fragancias.php",
					"productos/tron/ropa_accesorios.php",
                    "productos/tron/pisos.php",
                    "productos/tron/pisos_fragancias.php",
                    "productos/tron/pisos_accesorios.php",
					"productos/tron/banios.php",
					"productos/tron/banios_fragancias.php",
					"productos/tron/banios_accesorios.php",
					"productos/tron/loza.php",
					"productos/tron/loza_fragancias.php",
					"productos/tron/loza_accesorios.php"
				);
			?>

            <div class="col-sm-9 col-xs-12 lationT1" >


					<?php $t=0; for($tt=0; $tt<4; $tt++){ ?>
                        <div class="contenedor_del_producto_presentado"><!--Contenido-Presentacion-Producto-->
                            <div class="col-sm-3 col-xs-12">
                                <?php include (APPLICATION_SECTIONS.$arrIon[1+$t]); ?>
                            </div>

                            <div class="col-sm-9 col-xs-12">
                                <div class="row mb20"><!--Fragancias-->
                                    <p class="titulo_fragancia"> <strong> FRAGANCIAS </strong> </p>
                                    <?php include (APPLICATION_SECTIONS.$arrIon[2+$t]); ?>
                                </div>

                                <div class="row">
                                    <?php include (APPLICATION_SECTIONS.$arrIon[3+$t]); ?>
                                </div>
                            </div>

                            <br style="clear:both" />
                        </div>
                    <?php $t = $t+3; } ?>

               	<div id="carrosmotos" style="height:50px;"></div>

                <div class="felipeCalcula">

                  <!--  <div class="titleM1 colorBlue t24 mb30">CARROS Y MOTOS</div> -->

                    <?php include (APPLICATION_SECTIONS .'productos/tron/carros_y_motos.php'); ?>

                </div>

			</div>

            <div class="col-sm-3 col-xs-12" id="resumen-pedido-tron">
                <div class="theiaStickySidebar ionWin">

                	<?php include (APPLICATION_SECTIONS .'productos/tron/resumen_marco_derecho.php'); ?>

                </div>
            </div>

 		</div>
	</div>
</div>



