<div class="ionix">
    <div class="general">
    	<div class="contenido-index mb30 pAA30">
        	<div class="titleM1 colorBlue t24 mb30">

            	<?php if( count($this->Productos) > 0 ) :?>
                	PRODUCTOS ENCONTRADOS
                <?php else :?>
                	NO SE ENCONTRARON PRODUCTOS
                <?php endif;?>

            </div>
        <div id="contenido-productos">
            <div class="row">
                <?php
                    foreach ($this->Productos as $Productos) {
                    $mostrar_imagen_varias_referencias=true;
                    include (APPLICATION_CODS . 'campos_productos.php');
                ?>
                        <?php if ( $en_oferta == 1 ) : ?> <div class="artOpt artPor4 oferta">
                            <?php else :?>                 <div class="artOpt artPor4">
                         <?php endif ;?>

                            <?php include (APPLICATION_SECTIONS . 'productos_listado.php');?>
                        </div>

                <?php } ?>
            </div>
        </div>
		</div>
    </div>
</div>
