<div  id="contenido-productos" style="padding-top : 150px; width: 95%; margin: 0px auto;">
    <section >
      <div class="row">
         <div class="col-lg-12">
            <?php if( count($this->Productos) > 0 ) :?>
              <h3   id="destacados"><strong>PRODUCTOS ENCONTRADOS</strong></h3>

            <?php else :?>
                <br /><br />
                <h3 class="text-center"  id="destacados"><strong>NO SE ENCONTRARON PRODUCTOS</strong></h3>
                <br /> <br /><br /><br />
          <?php endif;?>
         </div>
      </div>
   </section>
 <!-- INICIO SECCION DESTACADOS -/////////////////////////////////////////////////////////////////////////////////////////////////  -->
 <section>
    <div class="container productos-center"><!--Class=Productos-Center => Se Encuentra En Los //Estilos-Titulos De Destacados , Ofertas y Novedades //-->
       <div class="row">
       <!-- INFORMACION DEL PRODUCTO -->
          <?php
             foreach ($this->Productos as $Productos)
             {
                $mostrar_imagen_varias_referencias=true;
                include (APPLICATION_CODS . 'campos_productos.php');

              ?>
          <div class="col-lg-2  col-md-2 col-sm-2  col-xs-2"  id="articulos">
               <?php include (APPLICATION_SECTIONS . 'productos_listado.php');?>
            </div><!-- FINAL COLUMNAS -->

           <?php }?>
          </div><!-- FINAL ROW -->
     </div><!-- FINAL CONTAINER-->

   </section><!-- FINAL SECCION DESTACADOS -->
</div>

<script>
            // Msotrar Carrito
           var $control = 0; 
           $('#menu_mostrar_carrito').on('click',function(){
               if($control == 0){
                  $('.navBar_mostrar_carrito').show();
                  $(this).css('background','#0469ED');
                 $control++;
              }else{
                  $('.navBar_mostrar_carrito').hide();
                  $(this).css('background','#003E90');
                 $control--;
              }
           });
</script>