<div class="ionix">
    <div class="general">    
    	<div class="contenido-index mb30 pAA30">
        	<div class="titleM1 colorBlue t24 mb30"><?= $this->Nombre_Agrupacion  ;?></div>
        
            <div class="row">
                <?php
                    foreach ($this->Productos_Varias_Referencias as $Productos) {
                    $mostrar_imagen_varias_referencias=false;
                    include (APPLICATION_CODS . 'campos_productos.php');
                ?>
                        <div class="artOpt artPor5">
                            <?php include (APPLICATION_SECTIONS . 'productos_listado.php');?>
                        </div>
                
                <?php } ?>
            </div>

		</div>
    </div>
</div>