<?php

  if (isset($this->Error)){
    exit;
  }
      $Producto                 = $this->Producto;
      $Cantidad_Imagenes        = $this->Cantidad_Registros;
      $codigo_grupo             = $Producto[0]['codigo_grupo'];
      $en_oferta                = $Producto[0]['en_oferta'];
      $fabricado_x_ta           = $Producto[0]['fabricado_x_ta'];
      $fragancia                = String_Functions::Formato_Texto($Producto [0]["fragancia"]);
      $id_controles             = 'cantidad'.$Producto[0]['idproducto'];
      $id_controles_escalas     = 'escalas'.$Producto[0]['idproducto'];
      $id_precio_final_tron     = 'precio_final_tron'.$Producto[0]['idproducto'];
      $id_pv_tron               = 'pv_tron'.$Producto[0]['idproducto'];
      $id_pv_tron_escala_a      = 'pv_tron_escala_a'.$Producto[0]['idproducto'];
      $id_pv_tron_escala_b      = 'pv_tron_escala_b'.$Producto[0]['idproducto'];
      $id_pv_tron_escala_c      = 'pv_tron_escala_c'.$Producto[0]['idproducto'];
      $id_categoria_producto    = $Producto[0]['id_categoria_producto'];
      $idescala                 = $Producto[0]['idescala'];
      $idgrupo                  = $Producto[0]['idgrupo'];
      $idproducto               = $Producto[0]["idproducto"];
      $nom_producto_descripcion =String_Functions::Formato_Texto($Producto [0]["nom_producto_descripcion"]);
      $nom_producto_largo       = $Producto[0]["nom_producto_largo"];
      $nombre_imagen            = $Producto [0]["nombre_imagen"];
      $nompresentacion          = String_Functions::Formato_Texto($Producto[0]["nompresentacion"]);
      $pv_ocasional             = Numeric_Functions::Formato_Numero($Producto[0]['pv_ocasional']);
      $pv_tron                  = Numeric_Functions::Formato_Numero($Producto[0]['pv_tron']);
      $pv_tron_escala_a         = $Producto[0]['pv_tron_escala_a'];
      $pv_tron_escala_b         = $Producto[0]['pv_tron_escala_b'];
      $pv_tron_escala_c         = $Producto[0]['pv_tron_escala_c'];
      $pv_tron_previo           = $Producto[0]['pv_tron'];   // COPIA, SIN, FORMATO, DEL $ PARA QUE AL REGRESAR LA CANTIDAD A CERO, RETORNO EL VALOR
      $Escala_1                 = '';
      $idnomproducto            = 'nomproducto'.$Producto[0]['idproducto'];
      $idnompresentacion        = 'nompresentacion'.$Producto[0]['idproducto'];
      $id_agrupacion            = $Producto[0]['id_agrupacion'];
      $logueado                 = $_SESSION['logueado'];
      $idtipo_plan_compras      = Session::Get('idtipo_plan_compras');
      $tags_busqueda            = $Producto[0]['tags_busqueda'];

      if ( $logueado  == TRUE ){
           $Pagina_Actual = "http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'].'/1/';
           $Pagina_Actual = $Pagina_Actual . Session::Get('idtercero').'/'.Session::Get('codigousuario').'/';
      }else{
        $Pagina_Actual          = "http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
      }

      $URL_COMPARTIR_FACEBOOK = "http://www.facebook.com/sharer.php?u=".$Pagina_Actual;
      $URL_COMPARTIR_GOOGLE   = "https://plus.google.com/share?url=".$Pagina_Actual;
      $URL_COMPARTIR_TWITER   = "https://twitter.com/?status=Me gusta esta página: ".$Pagina_Actual;

      Session::Set('FACEBOOK',TRUE);
      Session::Set('Pagina_Facebook_URL'          , trim($Pagina_Actual) );
      Session::Set('Pagina_Facebook_TITULO'       , trim($nom_producto_largo) );
      Session::Set('Pagina_Facebook_DESCRIPCION'  , trim(  $nom_producto_descripcion ) );
      Session::Set('Pagina_Facebook_IMAGEN'       , BASE_IMG_PRODUCTOS_472x472.$nombre_imagen );
      Session::Set('Pagina_Facebook_KEYS'         , trim($tags_busqueda) ) ;

?>

<?php include (APPLICATION_SECTIONS . 'productos/valida_oferta_cumpleanios.php');?>

<!-- MIGAS DE PAN QUE QUEDAN PENDIENTES LINK: HOGAR Y PERSONAL-->

<!-- INICA LA PRESENTACION DEL ARTICULO:IMG, PRECIO , TABLA-->

<div class="ionix">
    <div class="general pAA30">
        <div class="row"><!--IMAGEN PRODUCTO-->
            <div class="col-sm-6 col-xs-12 mb20_onlySmart taC">

                <img id="zoom_03" src="<?= BASE_IMG_PRODUCTOS_472x472.$nombre_imagen; ?>" data-zoom-image="<?= BASE_IMG_PRODUCTOS_944x944.$nombre_imagen  ;?>"  />

                <?php if ($Cantidad_Imagenes  >1) { ?>
                    <div id="gallery_01">
                        <?php
                            foreach ($this->Producto_Imagenes as $Imagenes_Productos){
                                $nombre_imagen  = $Imagenes_Productos["nombre_imagen"];
                                if ($Imagenes_Productos["zoom"]==1) { $Imagen_Zoom = BASE_IMG_PRODUCTOS_944x944; }
                                else                                { $Imagen_Zoom = BASE_IMG_PRODUCTOS_472x472; }
                        ?>
                                <a href="#" data-image="<?= BASE_IMG_PRODUCTOS_472x472.$nombre_imagen  ;?>" data-zoom-image="<?= $Imagen_Zoom.$nombre_imagen  ;?>">
                                    <img id="img_01" src="<?= BASE_IMG_PRODUCTOS_50x50.$nombre_imagen  ;?>" />
                                </a>
                        <?php } ?>
                    </div>
                <?php } ?>

            </div>



            <!-- incluciones de docuementos -->

            <?php include (APPLICATION_SECTIONS . 'productos_recomendar.php');?>
            <!-- incluciones de docuementos -->

            <div class="col-sm-6 col-xs-12 mb20_onlySmart" id="contenido-productos">

                <div class="t30 colorBlue ff2 mb20" id="<?= $idnomproducto  ;?>">
                    <?= $nom_producto_largo ;?>
                </div>

                <div class="t16 mb20"><?= $nom_producto_descripcion;?></div>

                <?php if (!empty( $fragancia )): ?>
                    <div class="t16 mb20 colorBlue"><?= $fragancia; ?></div>
                <?php endif ;?>



                <div id ="<?= $idnompresentacion; ?>">
                    <div class="mb20"><strong>Presentación: </strong><?= $nompresentacion ;?></div>
                    <?php if($id_agrupacion > 0): ?>
                        <!-- ver referencias -->
                        <div class="mb30">
                            <a href="#" class="nuvv" title="Productos semejantes con el mismo precio cuyas compras suman para alcanzar una misma escala"
                                style="text-decoration:none;">
                                <strong class="aS colurAd" style="color: #333;">Ver otras referencias:</strong>
                            </a>
                            <a href="<?=BASE_URL ;?>productos/varias_referencias/<?= $id_agrupacion; ?>" class="aS colorBlue">
                                <?= $nom_producto_largo; ?>
                            </a>
                        </div>
                    <?php endif; ?>
                </div>

                <?php if ( $en_oferta == TRUE) :?>
                <div class="colorfff ff3 t16 mb5" style="color:#f63d27; background-color:#;">
                	<strong>- OFERTA -</strong>
                	<span class="dIB  color666 mb3">Exclusivo para</span>
                    <span class="dIB"><img src="<?=BASE_IMG_TIENDA;?>17.png"   title="Precio Plan Cliente" ></span>
                    <span class="dIB"><img src="<?=BASE_IMG_TIENDA;?>16.png"   title="Precio Plan Empresario TRON" ></span>
                    <a href="<?=BASE_URL ;?>redtron/planes_de_registro" class="t10"> - <em class="aS cP" style="text-decoration:underline;">Más info</em></a>
                </div>
                <div class=" bb333 taC color666 ff0 p10 mb20" style="color:#fff; background-color:#f63d27;">

                    <div class="row p0 m0">
                        <div class="col-sm-5 col-xs-12 vcenter taL">

									<div class="t50 ff2"><?= $pv_tron; ?></div>

                        </div><!--
                        --><div class="col-sm-7 col-xs-12 vcenter taC t30">

                        	 <em>Por tiempo limitado</em>
                            <div class="row p0 m0 t20" style="display:none;">
                            	<div class="col-sm-3 col-xs-3 vcenter taC">
                                    <div class="t12 taR">el tiempo<br>se agota</div>
                                </div><!--
                                --><div class="col-sm-3 col-xs-3 vcenter taC">
                                    <div class="t24">12</div>
                                    <div class="t10">horas</div>
                                </div><!--
                                --><div class="col-sm-3 col-xs-3 vcenter taC">
                                    <div class="t24">48</div>
                                    <div class="t10">minutos</div>
                                </div><!--
                                --><div class="col-sm-3 col-xs-3 vcenter taC">
                                    <div class="t24">26</div>
                                    <div class="t10">segundos</div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
              <?php endif ;?>

                <div class="row">
                    <div class="col-sm-4 col-xs-12 mb20_onlySmart"><!--SUBINICIO DE HIJA-COLUMNA-->
                        <?php if ( $id_categoria_producto <> 6 ) :?>
                            <div class="taC mb10">
                                <strong><?= $pv_ocasional ?> <img src="<?= BASE_IMG_PRODUCTOS ;?>18.png"  title="Precio Público / Comprador Ocasional "></strong>
                            </div>
                        <?php endif;?>

                        <div class="taC mb20 priceTRONProd t18" id="<?= $id_precio_final_tron ;?>">
                            <?= $pv_tron; ?>
                            <img src="<?=BASE_IMG_TIENDA;?>17.png"  title="Plan Cliente">
                            <img src="<?=BASE_IMG_TIENDA;?>16.png"  title="Plan Empresario TRON">
                        </div>

                        <!--SECTION = INPUT , BOTONES , IMG => DONDE SE SELECCIONA LA CANTIDAD DE PRODUCTOS -->
                        <div class="costos-cantidad">
                            <form class="form-horizontal" role="form">
                                <div class="col-xs-4" id="cont-menos">
                                    <div class="form-group">
                                        <!--Inicio  Boton Menos-->
                                        <button id="<?=$idproducto ;?>"
                                        type="button"
                                        class="btn btn-default btn-menos btns-carrito"
                                        onclick="javascript: Carrito_Restar('<?=$id_controles ;?>')"  >-
                                        </button>
                                        <!-- Fin Boton Menos-->
                                    </div>
                                </div>
                                <div class="col-xs-4" id="cont-digitos">
                                    <div class="form-group">
                                        <!--Inicio Input-->
                                        <input id="<?=$id_controles ;?>" class=" digitos btn-carrito-input CantProductosComprados"  type="text"  value="1"
                                        id-idescala = "<?= $idescala ;?>"
                                        precio-amigo-tron = "<?= $pv_tron_previo; ?>"
                                        pv-tron-escala-a = "<?= $pv_tron_escala_a; ?>"
                                        pv-tron-escala-b = "<?= $pv_tron_escala_b; ?>"
                                        pv-tron-escala-c = "<?= $pv_tron_escala_c; ?>" >
                                        <!--Fin Input-->
                                    </div>
                                </div>
                                <div class=" col-xs-4" id="cont-mas">
                                    <div class="form-group">
                                        <!-- Inicio Boton Mas-->
                                        <button id="<?=$idproducto ;?>"
                                        type="button"
                                        class="btn btn-default btn-menos btns-carrito"
                                        onclick="javascript: Carrito_Sumar('<?=$id_controles ;?>')"  >+
                                        </button>
                                        <!-- Fin Boton Mas-->
                                    </div>
                                </div>

                                <input id="<?= $id_controles_escalas ;?>"  type="hidden" value="<?= $idescala ; ?>" />
                                <input id="<?= $id_pv_tron_escala_a ;?>"   type="hidden" value="<?= $pv_tron_escala_a; ?>" />
                                <input id="<?= $id_pv_tron_escala_b ;?>"   type="hidden" value="<?= $pv_tron_escala_b; ?>" />
                                <input id="<?= $id_pv_tron_escala_c ;?>"   type="hidden" value="<?= $pv_tron_escala_c; ?>" />
                                <input id="<?= $id_pv_tron ;?>"            type="hidden" value="<?= $pv_tron_previo; ?>" />
                            </form>

                            <!--INICIO BOTON DE AGREEGAR AL CARRITO DE COMPRAS -->
                            <div class="div-btn-">
                                <button type="button" class="agregar  boton-agregar-carrito"
                                    id                    ="<?=$id_controles ;?>"
                                    id-categoria-producto ="<?= $id_categoria_producto ;?>"
                                    en-oferta               = "<?= $en_oferta ;?>" >
                                    <div class="btn-agregar-carrito">
                                        Agregar <img src="<?=BASE_IMG_TIENDA;?>carrito-transparente.png" id="agr-car">
                                    </div>
                                </button>
                            </div><!--FIN BOTON DE AGREEGAR AL CARRITO DE COMPRAS -->
                        </div>  <!--SECTION = INPUT , BOTONES , IMG => DONDE SE SELECCIONA LA CANTIDAD DE PRODUCTOS-->
                    </div>

                    <!-- contienedor ( row ) = compartir , recomendar amigo , grupo porducto , agregar a favorito -->
                    <div class="col-sm-8 col-xs-12">

                        <!-- recomendar producto a un amigo -->
                        <div class="mb10">
                            <a class="cP" title="Si tu recomendación es efectiva y eres Empresario TRON... ganarás comisiones." id="notificaciones" data-toggle="modal" data-target="#recomendar"
                              >
                                <span class="recomendar"><img src="<?= BASE_IMG_PRODUCTOS ;?>25.png" alt=""></span> &nbsp;
                                ¡Recomendar este Producto a un Amig@!
                            </a>
                        </div>

                        <!-- compartir en redes sociales -->
                        <div class="mb10">
                            <span class="">Compartir: </span> &nbsp;
                            <a target="_blank" href="<?= $URL_COMPARTIR_FACEBOOK ;?>">
                                <img src="<?= BASE_IMG_PRODUCTOS ;?>compartir_en_facebook.png" width="28" />
                            </a> &nbsp;
                            <a target="_blank" href="<?= $URL_COMPARTIR_TWITER ;?>">
                                <img src="<?= BASE_IMG_PRODUCTOS ;?>compartir_twitter.png" width="28" />
                            </a> &nbsp;
                            <a target="_blank" href="<?= $URL_COMPARTIR_GOOGLE ;?>">
                                <img src="<?= BASE_IMG_PRODUCTOS ;?>compartir_googleMas.png" width="28" />
                            </a>
                        </div>

                        <!-- agregar favorito -->
                        <div class="">
                            <?php if (   $this->Favorito == FALSE )  :?>

                                <a class="cP" id="agregar-producto-favoritos" idproducto ="<?= $idproducto ;?>" idtercero = "<?= Session::Get('idtercero_pedido') ;?>"
                                    herf="#" title="Los productos que compras con frecuencia agrégalos a Favoritos para acceder a ellos fácilmente desde Mi Cuenta.">
                                    <span><img src="<?= BASE_IMG_PRODUCTOS ;?>26.png" alt=""></span>
                                    Agregar a Favoritos
                                </a>
                             <?php else : ?>
                                  <span><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" alt=""></span>
                                    Este producto ya hace parte de tus Favoritos!
                            <?php endif ;?>
                        </div>

                        <hr />

                        <!-- grupo del prodcuto -->
                        <div class="mb10">

                            <?php if ($idgrupo>0) :?>
                                <div class="imagen_tecnoaplicadas_producto t16 colorBlue dIB"
                                title="Este producto genera a los empresarios de la red comisiones tipo <?= $codigo_grupo  ;?>.  ¿ Deseas mas información ?, ¡Contáctanos a: contactos@entreamigosalcanzamos.com!">
                                    <div class="tabAll">
                                        <div class="tabIn taL">
                                            Producto grupo:
                                        </div>
                                    </div>
                                </div>

                                <div class="imagen_grupo_producto dIB"
                                title="Este producto genera a los empresarios de la red comisiones tipo <?= $codigo_grupo  ;?>.  ¿ Deseas mas información ?, ¡Contáctanos a: contactos@entreamigosalcanzamos.com!">
                                    <div class="tabAll">
                                        <div class="tabIn">
                                            <strong><?= $codigo_grupo  ;?></strong>
                                        </div>
                                    </div>
                                </div>
                            <?php endif ;?>


                            <?php if ($fabricado_x_ta==1) :?>
                                <div class="imagen_tecnoaplicadas_producto dIB" title="Producto fabricado por: Balquimia S.A.S.">
                                    <div class="tabAll">
                                        <div class="tabIn">
                                            <img src="<?= BASE_IMG_PRODUCTOS ;?>balquimia.png" width="50" alt="">
                                        </div>
                                    </div>
                                </div>
                            <?php endif ;?>

                            <?php if($en_oferta  == 1): ?>
                                <div class="imagen_en_oferta dIB" title="Producto en Oferta !!!">
                                    <div class="tabAll">
                                        <div class="tabIn">
                                            <img src="<?= BASE_IMG_EMPRESA ;?>en_oferta.png" width="50" alt="">
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>

                        </div>

                    </div>
                </div>

            </div>
        </div>
	</div>
</div>

<div class="ionix">
    <div class="general pAA30">
		<!--INICIO- TABS DEL PRODUCTO-->
		<?php if ( $this->Cantidad_Tabs > 0 ) : ?>

            <div class="gene-tabs">
                <ul class="nav nav-tabs">
                	<?php
						$Primer_Tab = true; // BANDERA PARA QUE EN EL PRIMER TAB COLOQUE INFORMACIÓN ADICIONAL
						foreach ($this->Productos_Tabs as $Tabs){
							$Titulo_Tab       = $Tabs["nombre_tab"];
							$IdTab            = 'Tab'.$Tabs["idtab"];
							if ($Primer_Tab==true){
								$Primer_Tab=false;
					?>

                            <li class="active"><a href="#<?= $IdTab ;?>"  data-toggle="tab"> <?= $Titulo_Tab ;?> </a></li><!--TITULO DEL TABS -->

							<?php } else { ?>

                      		<li><a href="#<?= $IdTab ;?>"  data-toggle="tab"> <?= $Titulo_Tab ;?> </a></li><!--TITULO DEL TABS -->

					<?php
							}
						}
					?>
                </ul>

                <div class="tab-content depuraContForz taJ">
					<?php
                    	$Primer_Tab = true; // BANDERA PARA QUE EN EL PRIMER TAB COLOQUE INFORMACIÓN ADICIONAL
                    	foreach ($this->Productos_Tabs as $Tabs) {
							$Información_Tab  = $Tabs["informacion_tab"];
							$IdTab            = 'Tab'.$Tabs["idtab"];
                    		if ($Primer_Tab==true) {
								$Primer_Tab=false;
					?>

                            <div class="tab-pane fade in active contenido-tab" id="<?= $IdTab ;?>"> <br> <?= $Información_Tab ; ?>
          <br style="clear:both;">
                            </div>

                    <?php  } else { ?>

                    		<div class="tab-pane fade contenido-tab" id="<?= $IdTab ;?>"> <br> <?= $Información_Tab ; ?>
 <br style="clear:both;">
                        </div>

                    <?php
                    		}
						}
					?>
				</div><!--FIN-CONTENIDO TABS -->
            </div>
		<?php endif ;?><!-- FIN IF Cantidad_Tabs>-->

	</div>
</div>


<script>

	$(document).ready(function() {

		$("#zoom_03").elevateZoom({
			constrainType	   : "height",
			zoomType		   : "inner",
			containLensZoom	   : true,
			gallery            : 'gallery_01',
			cursor             : 'pointer',
			galleryActiveClass : "active",
			imageCrossfade 	   : false
		});

		$("#zoom_03").on("click", function(e) {
			var ez = $('#zoom_03').data('elevateZoom');
			$.fancybox(ez.getGalleryList());
			return false;
		}); // FIN FUNCIONES ZOOM EN LA VISTA AMPLIADA.

	});

</script>

