   <?php

            if(isset($_GET["lapTransactionState"])){
                Session::Set('pagado_online',0);

                if($_GET["lapTransactionState"]  == "DECLINED") $texto = "Lo sentimos la transacción ha sido declinada o abandonada.";
				if($_GET["lapTransactionState"]  == "APPROVED") $texto = "Su transacción se ha realizado con éxito, muchas gracias por su compra.";
				if($_GET["lapTransactionState"]  == "ERROR") 	$texto = "Se ha presentado un error con el medio de pago externo.";
				if($_GET["lapTransactionState"]  == "PENDING")  $texto = "La transacción se encuentra pendiente.";
				if($_GET["lapTransactionState"]  == "EXPIRED")  $texto = "La transacción ha expirado.";
				if($_GET["lapTransactionState"]  == "EXPIRED")  $texto = "La transacción expiró, por superar el tiempo límite de respuesta.";

                if($_GET["lapTransactionState"]  == "APPROVED")
                {
                 Session::Set('pagado_online',1);
                }

            }

    ?>
<br />
<br />
 <?php if (isset($texto))  :; ?>
    <h1>    <?= $texto ;?> </h1>
<?php endif ;?>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

