
<?php
     $numero_pedido         = Session::Get('numero_pedido');
     $vr_total_pedido       = round(Session::Get('vr_total_pedido'),2);
     $compra_con_iva        = round(Session::Get('compra_con_iva'));
     $baseIva               = round(Session::Get('Vr_Base_Iva'),2);
     $pnombre               = utf8_encode(Session::Get('nombre_cliente'));
     $email                 = utf8_encode(Session::Get('email'));
     $identificacion        = Session::Get('identificacion');
     $signature             = md5 ("4uiapnu24digpg1gb05pntuge3~511623~".$numero_pedido ."~".$vr_total_pedido."~COP");

     $vr_devolucion         = $baseIva;
     $iva                   = $compra_con_iva - $baseIva ;


     if ( $baseIva  == 0 ){
        $iva           = 0;
        $vr_devolucion = 0;
     }

//Debug::Mostrar( $numero_pedido  );
 /*$file = fopen("c:/archivo.txt", "w");
    fwrite($file, $numero_pedido. ' NUMERO PEDIDO'. PHP_EOL);
    //men

fclose($file);

Debug::Mostrar( ' vr_total_pedido ' .  $vr_total_pedido );
Debug::Mostrar( ' baseIva ' . $baseIva  );
Debug::Mostrar( 'iva  ' . $iva  );
*/


?>
<br />

<h2 class="text-center" style="padding-top: 100px;">Estamos ingresando al sistema de pagos en línea, espere unos segundos por favor....</h2>


 <div id="img_cargando" style="display: block; width: 100%; text-align:center;">
     <br>
         Procesando información..
      <br>
         <img src="<?=BASE_IMG_EMPRESA;?>cargando.gif" style="display: block;  width: 30%; margin : 0px auto ;">
      <br>
         &nbsp;&nbsp;Espere unos segundos......
</div>


<br /> <br /> <br /> <br /> <br />
<form name="formPaypal" action="https://gateway.payulatam.com/ppp-web-gateway" method="post" id="">

    <input type="hidden" name="description"         id="description"            value = "<?= "Pedido No. ".$numero_pedido ; ?>" />
    <input type="hidden" name="amount"              id="amount"                 value = "<?= $vr_total_pedido; ?>" />
    <input type="hidden" name="tax"                 id="tax"                    value = "<?= $iva;?>" />
    <input type="hidden" name="taxReturnBase"       id="taxReturnBase"          value = "<?= $baseIva ; ?>" />

    <input type="hidden" name="accountId"           id="accountId"              value="512832">

    <input type="hidden" name="currency"            id="currency"               value = "COP">
    <input type="hidden" name="payerFullName"       id="payerFullName"             value = "<?= $pnombre ;?>">
    <input type="hidden" name="buyerEmail"          id="buyerEmail"             value = "<?=  $email ; ?>">
    <input type="hidden" name="payerDocument"       id="payerDocument"          value = "<?= $identificacion ; ?>">
<!--
    <input type="hidden" name="baseDevolucionIva"   id="baseDevolucionIva"      value = "<?= $vr_devolucion ; ?>" />
     <input name="confirmationUrl"                   type="hidden"         value = " <?= BASE_URL ;?>pedidos/ConfirmacionPayuLatam/" >
	 <input name="responseUrl"                   	type="hidden"           value = "" >
     responseUrl <?= BASE_URL ;?>pedidos/ConfirmacionPayuLatam/
 -->

   <input type="hidden" name="merchantId"           id="merchantId"         value="511623" />
   <input type="hidden" name="referenceCode"        id="referenceCode"       value = "<?= $numero_pedido ; ?>" />
   <input type="hidden" name="signature"            id="signature"          value="<?= $signature?>">

</form>



