<h4>Número de Pedido : <?= $this->numero_pedido ;?> </h4>


<table class=" table table-bordered ">
	<thead> <!-- Cabezera -->
		<tr>
			<th class="text-center">Producto</th>
			<th class="text-center">Fragan./Present.</th>
			<th class="text-center">Cantidad</th>
			<th class="text-center">Vr. Unitario</th>
			<th class="text-center">Vr. Total</th>

		</tr>
	</thead><!-- Cabezera -->


	<tbody><!-- Cuerpo -->

		<?php foreach ($this->Detalle_Pedido as $Pedido) :?>
				<?php
								$nom_producto          = $Pedido['nom_producto'];
								$nompresentacion       = $Pedido['nompresentacion'];
								$cantidad              = $Pedido['cantidad'];
								$vrunitario            = Numeric_Functions::Formato_Numero( $Pedido['vrunitario']);
								$vr_total              = Numeric_Functions::Formato_Numero( $Pedido['vr_total']);
								///
								$suma_total_pedido     = Numeric_Functions::Formato_Numero( $Pedido['suma_total_pedido']);

								$vr_total_pedido       = Numeric_Functions::Formato_Numero( $Pedido['vr_total_pedido']);
								$vr_fletes_totales     = Numeric_Functions::Formato_Numero( $Pedido['vr_fletes_totales']);
								$vr_puntos_redimidos   = Numeric_Functions::Formato_Numero( $Pedido['vr_puntos_redimidos']);
								$vr_comis_pago_pedidos = Numeric_Functions::Formato_Numero( $Pedido['vr_comis_pago_pedidos']);
								?>

								<tr>
											<td class="text-center">  <?= $nom_producto ;?> </td>
												<td class="text-center"> <?= $nompresentacion ;?> </td>
												<td class="text-center"> <?= $cantidad  ;?> </td>
												<td class="text-center"> <?= $vrunitario  ;?> </td>
												<td class="text-center"> <?= $vr_total ;?> </td>
								</tr>
				<?php endforeach ;?>
</tbody><!-- Cuerpo -->
				<tr><td colspan="3" ></td>
								<td> Subtotal Pedido : </td> <td> <?= $suma_total_pedido ;?> </td>
				</tr>
					<tr><td colspan="3" ></td>
								<td> Transporte : </td> <td> <?= 	$vr_fletes_totales ;?> </td>
				</tr>
				<?php if ( $Pedido['vr_puntos_redimidos']> 0 ) :?>
					<tr><td colspan="3" ></td>
									<td> Puntos Utilizados : </td>
									<td> <?= $vr_puntos_redimidos  ;?> </td>
					</tr>
				<?php endif ;?>

				<?php if ( $Pedido['vr_comis_pago_pedidos']> 0 ) :?>
					<tr><td colspan="3" ></td>
									<td> Comisiones Utilizadas : </td>
									<td> <?= $vr_comis_pago_pedidos  ;?> </td>
					</tr>
				<?php endif ;?>

					<tr><td colspan="3" ></td>
								<td> Total Pedido : </td> <td> <?= $vr_total_pedido ;?> </td>
				</tr>
</table>
