	<footer>
   <div class="container">
      <div class="col-lg-3 col-md-3 col-sm-3">
         <p>
            <h5 id="tl"><strong>HOGAR Y PERSONAL</strong></h5>
              <ul class="list-unstyled">
              	<li><a href="<?=BASE_URL;?>productos/productos_tron">Productos Tron</a></li>
              	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/17/Aseo Del Hogar/2">Aseo Del Hogar</a></li>
              	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/27/Cuidado Personal/2">Cuidado Personal</a></li>
              	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/28/Droguería/2">Droguería</a></li>
              	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/30/Fajas/2">Fajas</a></li>
              	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/20/Maquillaje/2">Maquillaje</a></li>
              	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/26/Mascotas/2">Mascotas</a></li>
              	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/25/Otros/2">Otros</a></li>
              	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/18/Productos Naturales/2">Productos Naturales</a></li>
              	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/29/Ropa/2">Ropa</a></li>
              	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/19/Tecnología/2">Tecnología</a></li>
              	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/24/Especiales Tron/2">Especiales Tron</a></li>
              </ul>
         </p>
      </div>

      <div class="col-lg-3 col-md-3 col-sm-3">
         <p>
             <h5 id="tl"><strong>INDUSTRIAL</strong></h5>
               <ul class="list-unstyled">
               	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/4/Línea Alimentaria/1">Línea Alimentaria</a></li>
               	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/1/Línea Artes Gráficas/1">Línea Artes Gráficas</a></li>
               	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/2/Línea Automotriz/1">Línea Automotriz</a></li>
               	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/5/Línea Hotelera/1">Línea Hotelera</a></li>
               	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/3/Línea Mantenimiento Industrial/1">Línea Mantenimiento Industrial</a></li>
               	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/8/Línea Materias Primas/1">Línea Materias Primas</a></li>
               	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/7/Línea Sanidad Portátil/1">Línea Sanidad Portátil</a></li>
               	<li><a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/6/Línea Textil/1">Línea Textil</a></li>
               </ul>
         </p>
      </div>

      <div class="col-lg-3 col-md-3 col-sm-3">
         <p>
             <h5 id="tl"><strong>RED DE AMIGOS</strong></h5>
               <ul class="list-unstyled">
             	  <li><a href="<?= BASE_URL ;?>redtron/red_de_amigos_tron">La Red de Amigos Tron</a></li>
             	  <li><a href="<?= BASE_URL ;?>redtron/tron_productos">Productos Tron</a></li>
             	  <li><a href="<?= BASE_URL ;?>redtron/kint_de_inicio">Kit De Inicio</a></li>
             	  <li><a href="<?= BASE_URL ;?>redtron/pases_de_cortesia">Pases De Cortesia</a></li>
             	  <li><a href="<?= BASE_URL ;?>redtron/comisiones">Comisiones</a></li>
             	  <li><a href="<?= BASE_URL ;?>redtron/Bonificaciones">Bonificaciones</a></li>
               </ul>

             <h5 id="tl"><strong>TIENDA TRON</strong></h5>
                <ul class="list-unstyled">
                	<li><a href="<?= BASE_URL ;?>redtron/planes_de_registro">Planes de Registro</a></li>
                	<li><a href="<?= BASE_URL ;?>redtron/tron_medios_pago">Métodos de Pagos</a></li>
                	<li><a href="<?= BASE_URL ;?>redtron/funcionalidades_interesantes">Funciones Interesantes</a></li>
                	<li><a href="<?= BASE_URL ;?>redtron/tron_transporte">Transporte</a></li>
                </ul>
         </p>
      </div>

      <div class="col-lg-3 col-md-3 col-sm-3">
         <p>
            <h5 id="tl"><strong>SOBRE TRON</strong></h5>
            	  <ul class="list-unstyled">
            		  <li><a href="<?= BASE_URL ;?>redtron/preguntas_frecuentes">Preguntas Frecuentes</a></li>
            		  <li><a href="<?= BASE_URL ;?>redtron/contactanos">Contáctanos</a></li>
            	  	<li><a href="http://www.balquimia.com">BALQUIMIA S.A.S.</a></li>
            		  <li><a href="<?= BASE_URL ;?>redtron/terminos_condiciones">Términos y Condiciones</a></li>
            	  </ul>


            <h5 id="tl"><strong>MI CUENTA</strong></h5>
            	<ul class="list-unstyled">
            		<li>
                   <a href="#myModal" class="footer-ing" data-toggle="modal" data-target="#myModal">
                      <span class="glyphicon glyphicon-user"></span>  Iniciar Sesión
                   </a>
                </li>

            		<li><a href="<?= BASE_URL ;?>terceros/registro" class="footer-rgs"><span class="glyphicon glyphicon-list-alt"> </span> Registrarme  </a></li>
            		<li><a href="#recuperar_contrasena"  data-toggle="modal" data-target="#recuperar_contrasena">Recuperar Contraseña</a></li>
                <!-- Incluir ventana modal => recuperar contraseña -->
                <?php include (APPLICATION_SECTIONS .'ventana_modal_recuperar_contrasena.php');?>
            	</ul>
         </p>
      </div>

   </div>
  </footer>



