
<div class="ionix bGray2">
    <div class="general pAA50">

    	<div class="row">

    		<div class="col-sm-6 col-xs-12">
                <div class="col-sm-6 col-xs-6">
                    <div class="titleM2 colorfff mb10"><strong>HOGAR Y PERSONAL</strong></div>
                    <ul class="listEnd">
                        <li><a href="<?=BASE_URL;?>productos/productos_tron">Productos TRON</a></li>
        <?php $Categorias_Hogar = Session::Get('Categorias_Hogar') ;?>
        <?php  foreach ($Categorias_Hogar  as $Categoria ) :?>
                <?php
                    $idorden_nv_1  = $Categoria['idorden_nv_1'];                 // Id
                    $orden_nivel_1 = trim(ucwords( strtolower($Categoria['orden_nivel_1'])));       // Nombre
                    $texto_url     = BASE_URL . 'productos/productos_por_categoria_individual/'.$idorden_nv_1.'/'.$orden_nivel_1 .'/'.'2';
                ?>
                <li><a href="<?= $texto_url ;?>"> <?= $orden_nivel_1 ;?> </a></li>
        <?php endforeach;?>

                    </ul>
                </div>

                <div class="col-sm-6 col-xs-6">
                    <div class="titleM2 colorfff mb10"><strong>INDUSTRIAL</strong></div>
                    <ul class="listEnd">
        <?php $Categorias_Industrial = Session::Get('Categorias_Industrial') ;?>
        <?php  foreach ($Categorias_Industrial  as $Categoria ) :?>
                <?php
                    $idorden_nv_1  = $Categoria['idorden_nv_1'];                 // Id
                    $orden_nivel_1 = trim(ucwords( strtolower($Categoria['orden_nivel_1'])));       // Nombre
                    $texto_url     = BASE_URL . 'productos/productos_por_categoria_individual/'.$idorden_nv_1.'/'.$orden_nivel_1 .'/'.'1';
                ?>
                 <li><a href="<?= $texto_url ;?>"> <?= $orden_nivel_1 ;?> </a></li>
        <?php endforeach;?>



                    </ul>
                </div>
            </div>
			<div class="col-sm-6 col-xs-12">
                <div class="col-sm-6 col-xs-6">
                    <div class="titleM2 colorfff mb10"><strong>RED DE AMIGOS</strong></div>
                    <ul class="listEnd">
                        <li><a href="<?= BASE_URL ;?>redtron/red_de_amigos_tron">La Red de Amigos Tron</a></li>
                        <li><a href="<?= BASE_URL ;?>redtron/tron_productos">Productos TRON</a></li>
                        <li><a href="<?= BASE_URL ;?>redtron/kint_de_inicio">Kit de Inicio</a></li>

                        <li><a href="<?= BASE_URL ;?>redtron/comisiones">Comisiones</a></li>

                    </ul>

                    <div class="titleM2 colorfff mb10"><strong>TIENDA TRON</strong></div>
                    <ul class="listEnd">
                        <li><a href="<?= BASE_URL ;?>redtron/planes_de_registro">Planes de Registro</a></li>
                        <li><a href="<?= BASE_URL ;?>redtron/tron_medios_pago">Métodos de Pagos</a></li>
                        <li><a href="<?= BASE_URL ;?>redtron/funcionalidades_interesantes">Funciones Interesantes</a></li>
                        <li><a href="<?= BASE_URL ;?>redtron/tron_transporte">Transporte</a></li>
                    </ul>
                </div>

                <div class="col-sm-6 col-xs-6">
                    <div class="titleM2 colorfff mb10"><strong>SOBRE TRON</strong></div>
                    <ul class="listEnd">
                        <li><a href="<?= BASE_URL ;?>redtron/preguntas_frecuentes">Preguntas Frecuentes</a></li>
                        <li><a href="<?= BASE_URL ;?>redtron/contactanos">Contáctanos</a></li>
                        <li><a href="http://www.balquimia.com">BALQUIMIA S.A.S.</a></li>
                        <li><a href="<?= BASE_URL ;?>redtron/terminos_condiciones">Términos y Condiciones</a></li>
                    </ul>

                    <div class="titleM2 colorfff mb10"><strong>MI CUENTA</strong></div>
                    <ul class="listEnd">
                        <li>
                            <a href="#myModal" class="footer-ing" data-toggle="modal" data-target="#myModal">
                                <span class="glyphicon glyphicon-user"></span> Iniciar Sesión
                            </a>
                        </li>
                        <li>
                            <a href="<?= BASE_URL ;?>terceros/registro" class="footer-rgs"><span class="glyphicon glyphicon-list-alt"> </span> Registrarme</a>
                        </li>

                        <?php include (APPLICATION_SECTIONS .'ventana_modal_recuperar_contrasena.php');?>
                    </ul>
                </div>
			</div>
		</div>

	</div>
</div>


<div class="ionix">
    <div class="general p30 t10 taR color666" style="background:url(<?= BASE_IMG_EMPRESA ; ?>logo.png) right center no-repeat; background-size:140px auto; padding-right:180px;">
    	<br />
    	<strong>TRON® marca registrada de Balquimia S.A.S.</strong>
       	<br /><br />

        Tienda virtual y modelo de negocio exclusivo para Colombia
        <br />

        Todos los derechos reservados
        <br />
        <strong>2016</strong>
        <br />
    </div>
</div>


