<!DOCTYPE html>
<html lang="es">
<head>
<?php include (APPLICATION_SECTIONS .'metas'. DS .'metas.php');?>
<!--
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge;chrome=1" />
  <meta http-equiv="Content-Type"    content="text/html; charset=utf-8"/>
  <meta http-equiv="cache-control"   content="max-age=0" />
  <meta http-equiv="cache-control"   content="no-cache" />
  <meta http-equiv="expires"         content="0" />
  <meta http-equiv="expires"         content="Tue, 01 Jan 1980 1:00:00 GMT" />
  <meta http-equiv="pragma"          content="no-cache" />
  <meta name="viewport"              content="width=device-width, initial-scale=1">

  <?php if ( Session::Get('FACEBOOK') == TRUE ):?>
      <meta property='og:locale'        content='es_ES'/>
      <meta property="og:type"          content="website" />
      <meta property="og:url"           content="<?= Session::Get('Pagina_Facebook_URL') ;?>" />
      <meta property="og:title"         content="<?= Session::Get('Pagina_Facebook_TITULO') ;?>" />
      <meta property="og:image"         content="<?= Session::Get('Pagina_Facebook_IMAGEN') ;?>" />
      <meta property='og:site_name'     content='Red Multinivel Entre Amigos Alcanzamos'/>
      <meta property="og:description"   content="<?= Session::Get('Pagina_Facebook_DESCRIPCION') ;?>" />

      <?php Session::Set('FACEBOOK', FALSE); ?>
  <?php endif;?>
  -->


    <title> <?= APP_NAME ;?> </title>

      <!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS CSS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO
      ******************************************************************************************************************-->
      <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,400italic,300italic' rel='stylesheet' type='text/css'>
      <!-- CSS de Bootstrap -->
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>bootstrap.min.css" media="screen" />

      <!--
        <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>custom.css" media="screen" />
      -->

      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>tron_menu_footer.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>tron_login.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>tron_registro.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>font_styles.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>validacion_contraseñas.css"/><!-- Validacion contraseñas -->
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>messi.min.css"/><!-- Validacion contraseñas -->
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>tron_notificaciones.css"/><!-- Validacion contraseñas -->


      <?php  if(isset($this->Css) && !empty($this->Css)) {
          foreach ($this->Css as $Archivo_Css) { ?>
       <link type="text/css"  rel="stylesheet" href="<?= $Archivo_Css ;?>"   />
       <?php }} ?>
      <!-- FIN INLCUSIÓN DE ARCHIVOS CSS
      *******************************************************************************************************************
			INICIA INLCUSIÓN DE ARCHIVOS SUPER CSS -->

            <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>super_css.css"  />
            <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>super_css_responsive.css"  />


  <script src="<?=  BASE_JS ; ?>jquery-1.11.3.min.js"                 type="text/javascript"></script>
  <script src ="<?= BASE_JS ; ?>jquery-migrate-1.2.1.min.js"          type="text/javascript" ></script>

      <!-- librerías opcionales que activan el soporte de HTML5 para IE8 Old IE gets 1.10 new IE gets 2.0 -->
      <!--[if lt IE 9]>
          <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
      <![endif]-->

      <!--[if gte IE 9]>
        <script src="http://code.jquery.com/jquery-2.0.3.js"></script>
      <![endif]-->

     </head>
         <body >

            <!--Llamado del Header tanto el de hogar como el industrial-->
            <?php if (Session::Get('Id_Area_Consulta')==1) :?>
               <?php include (APPLICATION_SECTIONS .'header-industrial.php');?><!--Llamado Al Menu-Industrial -->
            <?php else :?>
               <?php include (APPLICATION_SECTIONS .'header-hogar.php');?>
            <?php endif ;?>


            <?php   $Cumple_Anios       = Session::Get('cumple_anios'); ?>
            <?php   $Mostrar_Msj_Cumple = Session::Get('mostrar_modal_cumple_anios'); ?>
            <?php if ( $Cumple_Anios == TRUE && $Mostrar_Msj_Cumple == TRUE)  :?>
               <?php include (VENTANAS_MODALES . 'mensaje_cumpleanios.php');?>
            <?php endif ;?>


      <?= $ContenidoBody;?>

      <div class="alert alert-success mensaje-agregar_producto text-center"></div>
      <div id="scrollToHere"> </div> <!--  scrollToHere = ES UN ANCLA PARA MOVER EL PUNTO DESDE EL PAGINADOR     -->


      <?php require_once ($RutaFooter);?>

      <script src="<?=  BASE_JS ; ?>prefixfree.min.js"                 type="text/javascript"></script>
      <script src ="<?= BASE_JS ; ?>bootstrap.js"                      type="text/javascript" ></script>
      <script src ="<?= BASE_JS ; ?>tron_login.js"                     type="text/javascript" ></script>
      <script src ="<?= BASE_JS ; ?>tron_menu_fijo.js"                 type="text/javascript" ></script>
      <script src ="<?= BASE_JS ; ?>messi.min.js"                 	   type="text/javascript" ></script>
      <script src ="<?= BASE_JS ; ?>super_jquerion.js" 				         type="text/javascript" ></script>
      <script src ="<?= BASE_JS ; ?>tron_notificaciones.js"            type="text/javascript" ></script>
<!--
<script type="text/javascript">
  //alert(navigator.userAgent);
</script>

<script type="text/javascript">
      t    =new Date;
      m    =t.getMonth();
      d    =t.getDay();
      dt   =t.getDate();
      y    =t.getFullYear();
      h    =t.getHours();

    alert(t);
</script>

  -->


    <!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS JS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->
    <?php
		    if(isset($this->Js) && !empty($this->Js)){
    		    foreach ($this->Js as $Archivo_Js){
	       ?>
            <script src="<?= $Archivo_Js ;?>" type="text/javascript"></script>
	       <?php
    		}
		}
	?>
    <!-- FIN INLCUSIÓN DE ARCHIVOS JS
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->



</body>
</html>


