<!DOCTYPE html>
<html lang="es">
<head>

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge;chrome=1" />
<meta name="viewport"              content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type"    content="text/html; charset=utf-8"/>

<?php include (APPLICATION_SECTIONS."metas/metas.php"); ?>

    <title> <?= APP_NAME ;?> </title>

      <!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS CSS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO
      ******************************************************************************************************************-->
      <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,400italic,300italic' rel='stylesheet' type='text/css'>
      <!-- CSS de Bootstrap -->
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>bootstrap.min.css" media="screen" />
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>custom.css" media="screen" />

      <!--
      <link type="text/css" rel="stylesheet" href="<?=BASE_JQUERY_UI ;?>jquery-ui.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_JQUERY_UI ;?>jquery-ui.structure.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_JQUERY_UI ;?>jquery-ui.theme.css"  />
      -->

      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>tron_menu_footer.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>tron_login.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>tron_registro.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>font_styles.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>validacion_contraseñas.css"/><!-- Validacion contraseñas -->
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>messi.min.css"/><!-- Validacion contraseñas -->
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>tron_notificaciones.css"/><!-- Validacion contraseñas -->


      <?php  if(isset($this->Css) && !empty($this->Css)) {
          foreach ($this->Css as $Archivo_Css) { ?>
       <link type="text/css"  rel="stylesheet" href="<?= $Archivo_Css ;?>"   />
       <?php }} ?>
      <!-- FIN INLCUSIÓN DE ARCHIVOS CSS
      *******************************************************************************************************************
			INICIA INLCUSIÓN DE ARCHIVOS SUPER CSS -->

            <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>super_css.css"  />
            <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>super_css_responsive.css"  />

      <!--INLCUSIÓN DE ARCHIVOS SUPER CSS
      *******************************************************************************************************************-->
<!--
      	<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
		 <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
 -->
  <script src="<?=  BASE_JS ; ?>jquery-1.11.3.min.js"                 type="text/javascript"></script>
  <script src ="<?= BASE_JS ; ?>jquery-migrate-1.2.1.min.js"          type="text/javascript" ></script>

      <!-- librerías opcionales que activan el soporte de HTML5 para IE8 Old IE gets 1.10 new IE gets 2.0 -->
      <!--[if lt IE 9]>
          <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
      <![endif]-->

      <!--[if gte IE 9]>
        <script src="http://code.jquery.com/jquery-2.0.3.js"></script>
      <![endif]-->

         </head>
         <body >

<!--///////////////////////////////-Los documentos llamados se Encuentrar en (application_sections)-/////////////////////////////////////-->
            <!--Llamado del Header tanto el de hogar como el industrial-->
            <?php if (Session::Get('Id_Area_Consulta')==1) :?>
               <?php include (APPLICATION_SECTIONS .'header-industrial.php');?><!--Llamado Al Menu-Industrial -->
            <?php else :?>
               <?php include (APPLICATION_SECTIONS .'header-hogar.php');?>
            <?php endif ;?>
            <!--Llamado del Header tanto el de hogar como el industrial-->
            <!--///////////////////////////////-Los documentos llamados se Encuentrar en (application_sections)-/////////////////////////////////////-->

<?= $ContenidoBody;?>

<div class="alert alert-success mensaje-agregar_producto text-center"></div>



<?php require_once ($RutaFooter);?>

<script src="<?=  BASE_JS ; ?>prefixfree.min.js"                 type="text/javascript"></script>
<script src ="<?= BASE_JS ; ?>bootstrap.js"                      type="text/javascript" ></script>
<script src ="<?= BASE_JS ; ?>tron_login.js"                     type="text/javascript" ></script>
<script src ="<?= BASE_JS ; ?>tron_menu_fijo.js"                 type="text/javascript" ></script>
<script src ="<?= BASE_JS ; ?>messi.min.js"                 	type="text/javascript" ></script>
<script src ="<?= BASE_JS ; ?>super_jquerion.js" 				type="text/javascript" ></script>
<script src ="<?= BASE_JS ; ?>tron_notificaciones.js"        type="text/javascript" ></script>
<!--
<script type="text/javascript">
  //alert(navigator.userAgent);
</script>

<script type="text/javascript">
      t    =new Date;
      m    =t.getMonth();
      d    =t.getDay();
      dt   =t.getDate();
      y    =t.getFullYear();
      h    =t.getHours();

    alert(t);
</script>

  -->


    <!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS JS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->
    <?php
		    if(isset($this->Js) && !empty($this->Js)){
    		    foreach ($this->Js as $Archivo_Js){
	       ?>
            <script src="<?= $Archivo_Js ;?>" type="text/javascript"></script>
	       <?php
    		}
		}
	?>
    <!-- FIN INLCUSIÓN DE ARCHIVOS JS
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->



</body>
</html>


