<div class="contenedor"><!--Contenedor-De-La-Pagina-->
<div class="row"><!--Fila-->

<!--Boton de Ir Arriba -->

  <?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?>

<!--Boton de Ir Arriba -->

<!--Campo de la pagina redtron -->

   <?php include (APPLICATION_SECTIONS . 'redtron_btn_superior.php');?>

<!--Campo de la pagina redtron -->


    <div class="col-lg-9  col-md-9  col-sm-9"><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->
       <div class="row"><!--Titulo-->
       	   <div class="col-lg-12 col-md-12 col-sm-12">
       	   	  <h1 class="titulo-principal">Bonificaciones</h1> <br>
       	   </div>
       </div><!--Titulo-->

<!--////////////////////////////////////////////////-Bonificaciones-/////////////////////////////////////////////////////////////-->

  <div class="col-lg-12 col-md-12 col-sm-12 "><!--Bonificaciones -->
  <p class="text-justificado">Las Bonificaciones son otras de las recompensas para todos los usuarios registrados en el Plan Empresario TRON. Cuando un amigo se registre con tu Código de Usuario en el Plan Empresario TRON, tienes derecho a recibir una Bonificación. Esta Bonificación es un porcentaje de lo pagado por quien ingrese a tu Red por concepto de Derechos de Inscripción. Este porcentaje varía dependiendo del número de cuota (1era, 2da. ó 3ra.) y el nivel que ocupe con respecto a ti quien llega a tu Red de Amigos. La bonificación por la primera cuota que es la que se paga al ingresar es así: Recibirás el 32% por las 4 personas que ingresen en tu primer nivel, el 16% por las 16 personas que ingresen en tu segundo nivel, el 8% por las 64 personas que ingresen en tu tercer nivel, el 4% por las 256 personas que ingresen en tu cuarto nivel, el 2% por las 1.024 personas que ingresen en tu quinto nivel y el 1% por las 4.096 personas que ingresen en tu sexto nivel.- <br><br>
  En las cuotas 2 y 3 se invertirá el porcentaje de bonificación y recibirás las bonificaciones así: el 1% por las 4 personas en tu primer nivel, el 2% por las 16 personas en tu segundo nivel, el 4% por las 64 personas en tu tercer nivel, el 8% por las 256 personas en tu cuarto nivel, el 16% por las 1.024 personas en tu quinto nivel y el 32% por las 4096 personas en tu sexto nivel. Estos porcentajes se aplican a lo que tus amigos cancelaron por concepto de Derechos de Inscripción. Cuando tus amigos presenten a la red con su Código de Usuario a otras personas, por cada una de ellas, volverás a recibir la Bonificación mencionada anteriormente. Y a su vez, cuando los nuevos presenten a sus amigos, sobre el valor cancelado por ellos por concepto de Derechos de Inscripción, tú vuelves a recibir la Bonificación. <br><br>
  En otras palabras, cuando alguien ingrese a tu Red, recibes Bonificación, por él y por todos los que él invite y por todos los que los invitados inviten y así sucesivamente hasta por seis (6) niveles de profundidad a partir de tí. Esto quiere decir que si tu ingresas cuatro (4) amigos y estos a su vez hacen lo mismo y así sigue hasta completar tus seis (6) niveles, tendrás en tu red cinco mil cuatrocientos sesenta (5.460) amigos y por cada uno de ellos recibirás la Bonificación antes mencionada de lo que ellos pagaron por Derechos de Inscripción, o sea, en términos de hoy, $ 121´449.600 ¡¡¡Más de 120 millones de pesos en Bonificaciones!!! <br><br>
  Así bonificamos tu interés en hacer crecer esta red de solidaridad. Te invitamos a transformar esta promesa en algo real, simplemente Pasando la Voz y observando cómo cada que crece tu red, crecen tus ingresos por concepto de Bonificaciones. <br><br>
  Los resultados de tu gestión podrás confirmarlos a principios de cada mes cuando se liquiden Bonificaciones y Comisiones, a través de los distintos Informes que hemos puesto a tu disposición. El 100% de lo ganado será depositado en tu Cuenta Dinero. <br><br>
  		Recuerda, TRON Entre amigos alcanzamos ha sido diseñado pensando en beneficiar a muchísimas personas, a todos los que se vinculen. Te invitamos a ser parte de esta visión.</p>
  </div><!--Bonificaciones -->

<!--////////////////////////////////////////////////-Medios de Cobro-/////////////////////////////////////////////////////////////-->

  <div class="col-lg-12 col-md-12 col-sm-12 "><!--Medios de Cobro -->
      <div> <p class="contenido-titulos">Medios de Cobro</p></div>

      <p class="text-justificado">El pago de las Bonificaciones se hará los primeros tres (3) días hábiles de cada mes, directamente a la cuenta bancaria que has registrado en el momento de la inscripción o posteriormente, en cualquier momento, en Mi Cuenta / Perfil / Datos de Cuenta.
Recuerda que el costo de la transferencia bancaria es de <?= Session::Get('valor_transferencia_bancaria') ;?> por lo que debes ajustar la cifra Valor Mínimo a Transferir a la cuantía que te convenga. Esta cifra viene por defecto en <?= Session::Get('valor_minimo_transferencias') ;?> y puedes incrementarla a tu conveniencia (no disminuirla).</p>
  </div><!--Medios de Cobro -->
 </div><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

   <?php include (APPLICATION_SECTIONS . 'col_izquierdad_redtron.php');?>

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

</div><!--Fin-Fila-->
</div><!--Contenedor-De-La-Pagina-->
<br><br> <br>

