<!--Los estilos se ecuentran en la carpeta CSS => tron_red_amigo_general.css -->

<div class="contenedor"><!--Contenedor-De-La-Pagina-->
<div class="row"><!--Fila-->

<!--Boton de Ir Arriba -->

  <?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?>

<!--Boton de Ir Arriba -->

<!--Campo de la pagina redtron -->

   <?php include (APPLICATION_SECTIONS . 'redtron_btn_superior.php');?>

<!--Campo de la pagina redtron -->

    <div class="col-lg-9  col-md-9  col-sm-9"><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->
       <div class="row"><!--Titulo-->
       	   <div class="col-lg-12 col-md-12 col-sm-12">
       	   	  <h1 class="titulo-principal">Comisiones<a name="info_general"></a></h1> <br>
       	   </div>
       </div><!--Titulo-->


    <div class="col-lg-3 col-md-3 col-sm-3 contenido-indice"><!--Idice-->
       <h5><strong>INDICE</strong></h5><!--Titulo-->

        <nav class="indice">
           <ul class="list-unstyled">
              <li><a href="#introduccion">Introducción</a></li>
              <li><a href="#info_general">Informacion general</a></li>
              <li><a href="#porcentajes">Porcentajes de Comisiones</a></li>
              <li><a href="#puntos">Puntos</a></li>
              <li><a href="#medios">Medios de Cobro</a></li>
           </ul>
        </nav>
    </div><!--Idice-->

    <div class="col-lg-9 col-md-9 col-sm-9"><!--Informacion-Contendo-Introduccion -->
    	 <div><p class="contenido-titulo-Introduccion">Introducción</p> </div> <br><!--Titulo -->
       <p class="text-introduccion">Las comisiones son uno de los pilares del plan de compensación para los usuarios registrados en el Plan Empresario TRON.
       </p>
    </div><!--Informacion-Contendo-Introduccion -->

<!--///////////////////////////////////////////////////-Información General-/////////////////////////////////////////////////////-->

    <div class="col-lg-12 col-md-12 col-sm-12"><!--Información General-->
       <div><p class="contenido-titulos titulo-info-general">Información General</p></div><!--Titulo -->

       <p class="text-justificado">Para recibir comisiones el Empresario TRON debe encontrarse activo en la red y que al último día del mes a liquidar cumplan con alguna de las siguientes condiciones: <br><br>

        <ul class="list-unstyled lista-Info-General">
           <li>1. Que tengan amigos en su red vinculados al Plan Empresario TRON y estos hayan hecho compras.
           </li>

           <li>2. Que tengan amigos vinculados por ellos en el Plan Cliente TRON y estos hayan hecho compras.
           </li>

           <li>3. Que amigos vinculados por ellos al Plan Empresario TRON, tengan amigos vinculados por ellos en el Plan Cliente   TRON y estos hayan hecho compras.
           </li>
        </ul><br><br>

        <p class="text-justificado">Las Comisiones se liquidan los primeros 3 días hábiles del mes siguiente al mes que se liquida. <br><br>
          Las comisiones se pierden cuando un Empresario TRON se inactiva un mes, o sea, no realiza su compra mínima mensual reglamentaria. ($ 25.000 en productos TRON para el hogar ó $ 40.000 en productos industriales fabricados por Balquimia S.A.S.). <br><br>
          Al registrarse en el Plan Empresario TRON, se crearán dos (2) cuentas virtuales a nombre del usuario. La cuenta Dinero y la cuenta Puntos. El 70% del valor total de comisiones serán consignadas en la cuenta Dinero y el 30% restante serán consignados en la cuenta Puntos y estos sólo se utilizaran para compras en la Tienda Virtual. Cada punto tendrá el valor <a name="porcentajes"></a>de $1 M/cte. (un peso moneda colombiana corriente). <br><br>
          Las liquidaciones se basan en todas las compras de productos hechas en el mes por las personas que conforman tu red (“Mis amigos” y “los Amigos de mis Amigos”) registrados en el Plan Empresarios TRON hasta el nivel sexto (6º.) en tu Red y todas las compras de productos hechas en el mes por las personas registradas con tu Código de Usuario en el Plan Cliente TRON. <br><br>
          Hay algunas cuantías sobre las que no se pagan comisiones, estas son: el IVA, el valor del transporte, la compra de accesorios o de productos promocionales los cuales se encuentran identificados con el ícono</p>
          </p><span><img src="<?= BASE_IMG_PRODUCTOS ;?>star2.png"/></span>
          <a name="puntos"></a>
    </div><!--Información General-->

<!--////////////////////////////////////////////////-Porcentajes de Comisiones-//////////////////////////////////////////////////-->

   <div class="col-lg-12 col-md-12 col-sm-12"><!-- Porcentajes de Comisiones-->
       <div><p class="contenido-titulos">Porcentajes de Comisiones</p></div><br><!--Titulo -->

      <div>
         <table class="table table-condensed table-hover contenido-tablas">

              <thead><!--Emcabezado -->
                  <tr>
                     <th>Tipo Plan</th>
                     <th  class="text-center">Productos Comprados</th>
                     <th  class="text-center">Comisiones</th>
                  </tr>
              </thead><!--Emcabezado -->

              <tbody><!--Cuerpo-->
                  <tr>
                     <td>Empresario TRON:</td>
                     <td class="text-center">Productos TRON (cojines)</td>
                     <td class="text-center">5%</td>
                  </tr>
                  <tr>
                     <td></td>
                     <td class="text-center">Otros productos</td>
                     <td class="text-center">Variable<small>(ver tabla en menú Mi Cuenta)</small></td>
                  </tr>
                  <tr>
                     <td>Cliente TRON</td>
                     <td class="text-center">Productos TRON (cojines)</td>
                     <td class="text-center">20%</td>
                  </tr>
                  <tr>
                     <td></td>
                     <td class="text-center">Otros productos</td>
                     <td class="text-center">Variable x 4  <small>(ver tabla en menú Mi Cuenta)</small></td>
                  </tr>
              </tbody><!--Cuerpo-->
         </table>
      </div>
 </div><!-- Porcentajes de Comisiones-->


<!--////////////////////////////////////////////////-Puntos-//////////////////////////////////////////////////-->

  <div class="col-lg-12 col-md-12 col-sm-12"><!--Puntos-->
      <div><p class="contenido-titulos"><a name="medios"></a>Puntos</p></div><!--Titulo-->

      <p class="text-justificado">Los puntos son lo correspondiente al 30% de las Comisiones del Empresario TRON. <br><br>
        Los puntos son una estrategia importante para el funcionamiento de la Red, porque así como tú te ves obligado a comprar en la Tienda Virtual para redimirlos, así lo tendrán que hacer tus muchos amigos registrados en tu red y al hacerlo, tú ganas más porque ganas comisiones por esas compras.
        <br><br>
        Los puntos tendrán una vigencia de 60 días. Por ejemplo: En la liquidación de comisiones del mes de Marzo, un usuario obtiene 15000 puntos. Estos puntos aparecen en su cuenta Puntos los primeros días de Abril cuando se realiza la liquidación de comisiones. El usuario tiene todo el mes de Abril y todo el mes de Mayo para utilizarlos comprando en la Tienda Virtual. El proceso para redimirlos es muy sencillo. Basta comprar cualquier producto TRON u otro producto. Al momento de la liquidación del pedido el sistema verificará en primera instancia si existen puntos a favor y los aplicará al valor a pagar a razón de $ 1 por cada punto. De esta forma los puntos se convierten en dinero.
        </p>
  </div><!--Puntos-->

<!--////////////////////////////////////////////////-Medios de Cobro-//////////////////////////////////////////////////-->

    <div class="col-lg-12 col-md-12 col-sm-12"><!--Puntos-->
      <div><p class="contenido-titulos">Medios de Cobro</p></div><!--Titulo-->

      <p class="text-justificado">Por defecto, el pago de las comisiones se hará en efectivo a través de Efecty., pero pueden los usuarios de la Red, a través del menú <em>Mi Cuenta / Información Adicional</em>, solicitar que sean pagadas mediante transferencia electrónica a alguna cuenta corriente o de ahorros que se encuentre a su nombre. <br><br>

        Al escogerse esta opción, se está autorizando que el costo que tenga esta transferencia (hoy $ 4.500), es asumido por el usuario. En este caso, también hay que autorizar cuál es el valor mínimo que puede ser transferido a su cuenta (por defecto y mínimo $ 10.000) puesto que un valor muy cercano al costo de la transferencia, no se justificaría transferirlo. <br><br>

        Si has escogido recibir sus pagos en efectivo a través de Efecty (opción por defecto), las cuantías inferiores a $ 30.000, no se te pagarán por ser consideradas de menor valor. Estos valores se abonan a la cuenta personal (cuenta Dinero) y contarán para ser restados en el próximo pedido del valor a pagar. En otras palabras, no se te entregan de forma directa pero sirven para que abones al valor de tu próximo pedido. <br><br>

        Si por el contrario, has escogido mediante el menú <em>Mi Cuenta / Información Adicional</em>, modificar tus preferencias a transferencia bancaria como medio de pago de tus comisiones y bonificaciones, se pagará cualquier valor que supere un mínimo determinado (hoy $ 10.000).</p>
  </div><!--Puntos-->
</div><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

   <?php include (APPLICATION_SECTIONS . 'col_izquierdad_redtron.php');?>

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

</div><!--Fin-Fila-->
</div><!--Contenedor-De-La-Pagina-->
<br><br> <br>
