
<div class="ionix">
    <div class="general">
    	<div class="contenido-index mb30 pAA30">

        	<?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?><!--Boton de Ir Arriba -->

            <div class="row">

				<div class="col-sm-9 col-xs-12">

                	<!-- ZONA INFORMATIVA -->
                    <!-- ZONA INFORMATIVA -->
                    <!-- ZONA INFORMATIVA -->

                 	<div class="titleM1 colorBlue t24 ">Contáctanos</div>
                    <?php $ml1 = false; $ml2 = false; $ml3 = true; ?>
                    <?php include "views/redtron/info/contacto.php"; ?>

                    <!-- /ZONA INFORMATIVA/ -->
                    <!-- /ZONA INFORMATIVA/ -->
                    <!-- /ZONA INFORMATIVA/ -->

                </div>

				<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->
				<?php include (APPLICATION_SECTIONS . 'col_izquierdad_redtron.php');?>
				<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->
			</div>
		</div>
	</div>
</div>
