<!--Los estilos se encuentran en la carpeta CSS => tron_red_amigo_general.css -->
<!--La funcion de la (( Linea Industrial // linea 58 )) se encuetra en la carpeta JS => tron_redtron_formulario.js -->

<div class="contenedor"><!--Contenedor-De-La-Pagina-->
<div class="row"><!--Fila-->

<!--Boton de Ir Arriba -->

  <?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?>

<!--Boton de Ir Arriba -->

<!--Campo de la pagina redtron -->

   <?php include (APPLICATION_SECTIONS . 'redtron_btn_superior_desactive.php');?>

<!--Campo de la pagina redtron -->

    <div class="col-lg-9  col-md-9  col-sm-9"><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->

       <div class="row"><!--Titulo-->
       	   <div class="col-lg-12 col-md-12 col-sm-12">
       	   	  <h1 class="titulo-principal">Contáctanos</h1> <br>
       	   </div>
       </div><!--Titulo-->

     <div class="col-lg-12 col-md-12 col-sm-12"><!--Contáctanos -->
          <p>Contáctate con nosotros, estamos a tu disposición.</p>
          <p><strong>Horarios de Atención:</strong>Lunes a Viernes de 7:30 am a 12:00 m y 1:30 pm a 6:00 pm.</p>
          <p><strong>Línea gratuita al cliente:</strong>01 8000 18 TRON <small>(8766)</small></p>
          <p><strong>PBX:</strong>(2) 488 1616, Cali - Colombia.</p>
     </div><!--Contáctanos -->

     <div class="col-lg-12"><!--Formulario de Contacto -->
          <div> <p class="contenido-titulos">Formulario de Contacto</p></div><br>
             <div class="cont-formulario"><!--Contenedor del formulario -->
              <form role="form">

           		<div class="col-lg-12 col-md-12 col-sm-12"><!--Nombre-Usuario -->
           			<div class="form-group">
           				<label for="nombre_usuario" class="text-label">Nombre</label>
           				<input type="text" class="form-control" id="nombre_usuario" >
           			</div>
           		</div><!--Nombre-Usuario -->

             <div class=" col-lg-8 col-md-8 col-sm-8"><!--Email -->
	             	<div class="form-group">
	             		<label for="email" class="text-label">Email</label>
	             		<input type="text" class="form-control"  id="email">
	             	</div>
             </div><!--Email -->

             <div class="col-lg-4 col-md-4 col-sm-4"><!--Telefono -->
                 <div class="form-group">
                 	   <label for="telefono" class="text-label">Teléfono</label>
                 	   <input type="text" class="form-control"  id="telefono">
                 </div>
             </div><!--Telefono -->

             <div class="col-lg-12 col-md-12 col-sm-12">
             	   <div class="form-group">
             	   	  <label for="comentarios" class="text-label">Comentarios</label>
             	   	  <textarea class="form-control" rows="4" id="comentarios"></textarea>
             	   </div>

             </div>



           <div class="col-lg-12 col-md-12 col-sm-12">
		           	<div class="btn-enviar-cancelar">
			           		<button type="button" class="btn btn-danger" id="btn_enviar">Enviar</button>
			           		<button type="button" class="btn btn-danger" id="btn_cancelar">Cancelar</button>
                   <div  style="display: none; width: 60%;">
                      <img src="<?=BASE_IMG_EMPRESA;?>cargando.gif" alt=""> Enviando información. Espere unos segundos...<br />
                   </div>
		           	</div>
           </div>
          </form>
         </div><!--Contenedor del formulario -->
     </div><!--Formulario de Contacto -->
   </div><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->


<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

   <?php include (APPLICATION_SECTIONS . 'col_izquierdad_redtron.php');?>

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

</div><!--Fin-Fila-->
</div><!--Contenedor-De-La-Pagina-->
<br><br> <br>
