<?php
    $Pedido_Minimo_Tron   = Session::Get('valor_minimo_pedido_productos');
    $Pedido_Minimo_Indus  = Session::Get('pedido_minimo_productos_fabricados_ta');
?>

<div class="ionix">
    <div class="general">    
    	<div class="contenido-index mb30 pAA30">
        
        	<?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?><!--Boton de Ir Arriba -->
            <?php include (APPLICATION_SECTIONS . 'redtron_btn_superior2.php');?>
            
            <div class="row">

				<div class="col-sm-9 col-xs-12">                
                
                	<!-- ZONA INFORMATIVA -->
                    <!-- ZONA INFORMATIVA -->
                    <!-- ZONA INFORMATIVA -->                    
                    
                 	<div class="titleM1 colorBlue t24">Funcionalidades Interesantes</div>
                    <?php $ml1 = false; $ml2 = true; $ml3 = true; ?>
                    <?php include "views/redtron/info/funcionalidades.php"; ?>
                    
                    <!-- /ZONA INFORMATIVA/ -->
                    <!-- /ZONA INFORMATIVA/ -->
                    <!-- /ZONA INFORMATIVA/ -->                    
                    
                </div>

				<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->
				<?php include (APPLICATION_SECTIONS . 'col_izquierdad_redtron.php');?>
				<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->
			</div>
		</div>
	</div>
</div>


