<div class="contenedor"><!--Contenedor-De-La-Pagina-->
<div class="row"><!--Fila-->

<!--Boton de Ir Arriba -->

  <?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?>

<!--Boton de Ir Arriba -->

<!--Campo de la pagina redtron -->

   <?php include (APPLICATION_SECTIONS . 'redtron_btn_superior_desactive.php');?>

<!--Campo de la pagina redtron -->


    <div class="col-lg-9  col-md-9  col-sm-9"><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->
       <div class="row"><!--Titulo-->
       	   <div class="col-lg-12 col-md-12 col-sm-12">
       	   	  <h1 class="titulo-principal">Garantía de Calidad</h1> <br>
       	   </div>
       </div><!--Titulo-->

       <div class="col-lg-12 col-md-12 col-sm-12">
		       	<p class="text-justificado">Tecnologías Aplicadas S.A y la Tienda Virtual TRON Entre amigos alcazamos, realiza convenios y negociaciones con grandes marcas de la industria nacional e internacional para poder otorgar a sus clientes los mejores precios, calidad y respaldo. <br>
		       		Cada producto comprado en la Tienda Virtual TRON posee una garantía que deriva de la empresa fabricante, estamos siempre dispuestos a ayudar a nuestros clientes para hacer eficientes y efectivas sus reclamaciones, de haberlas. <br>	<br><br>

		       	 <p class="text-justificado">Ante cualquier situación que se le presente, no dude en contactarnos:</p>
		         <p class="text-justificado"><strong>Horarios de Atención:</strong>Lunes a Viernes de 7:30 am a 12:00 m y 1:30 pm a 6:00 pm.</p>
		         <p class="text-justificado"><strong>PBX:</strong>(2) 488 1616.</p>
		         <p class="text-justificado"><strong>Línea gratuita al cliente:</strong>01 8000 18 TRON <small>(8766).</small></p>
		         <p class="text-justificado"><strong>Dirección:</strong> Cll 35 N° 4-31, Cali - Colombia.</p>

		       	</p>
       </div>
   </div><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->


<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

 <?php include (APPLICATION_SECTIONS . 'col-izquierdad-redtron10.php');?>

 <!--Llamado = col-izquierdad-redtron10 = en esta vista se presentan 10 campos => red de amigo , porductos tron ect -->

 <!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

</div><!--Fin-Fila-->
</div><!--Contenedor-De-La-Pagina-->
<br><br> <br>
