<!--Los estilos se  encuentran en la carpeta CSS => documento tron_red_general.css-->

<div class="contenedor"><!--Contenedor-De-La-Pagina-->
<div class="row"><!--Fila-->

<!--Boton de Ir Arriba -->

  <?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?>

<!--Boton de Ir Arriba -->

<!--Campo de la pagina redtron -->

   <?php include (APPLICATION_SECTIONS . 'redtron_btn_superior.php');?>

<!--Campo de la pagina redtron -->

    <div class="col-lg-9  col-md-9  col-sm-9"><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->
       <div class="row"><!--Titulo-->
       	   <div class="col-lg-12 col-md-12 col-sm-12">
       	   	  <h1 class="titulo-principal">El Kit de Inicio</h1> <br>
       	   </div>
       </div><!--Titulo-->

<!--//////////////////////////////////////-El Kit de Inicio-///////////////////////////////////////////////-->

	<div class="col-lg-12 col-md-12 col-sm-12"><!--El Kit de Inicio -->
		   <p>El Kit de Inicio es un paquete especial que contiene cojines de todos los productos, sus  envases vacíos, sus tapas y/o válvulas y un obsequio de bienvenida. <br><br>
			Es el primer pedido para conocer y evaluar los productos TRON adquiriendo los envases dosificadores que no se requieren volver a comprar</p>

			   <div class="cont-img-kit">
				     <img src="<?= BASE_IMG_PRODUCTOS ;?>tron_1.jpg" class="img-responsive img-kit"><!--IMG del KIT -->
			   </div>
		</div><!--El Kit de Inicio -->

<!--////////////////////////////////////-Contenido del Kit de Inicio-///////////////////////////////////////////////-->

  <div class="col-lg-12 col-md-12 col-sm-12"><!--Contenido del Kit de Inicio -->
  	   <div> <p class="contenido-titulos">Contenido del Kit de Inicio</p></div><br><!--Titulo-->

       <div>
       	  <table class="table table-condensend table-hover contenido-tablas">

       	      <thead><!--Emcabezado -->
                  <tr>
                     <th>Concepto</th>
                     <th class="text-center">Cantidad</th>
                  </tr>
       	      </thead><!--Emcabezado -->

       	      <tbody><!--Cuerpo -->
                 <tr>
                 	  <td>Envases dosificadores vacíos</td>
                 	  <td class="text-center">4</td>
                 </tr>
                 <tr>
                 	  <td>Tapa o valvula especializada para el envase</td>
                 	  <td class="text-center">4</td>
                 </tr>
                 <tr>
                 	  <td>Cojines de concentrado TRON Detergente para lavar ropa</td>
                 	  <td class="text-center">1</td>
                 </tr>
                 <tr>
                 	  <td>Cojines de concentrado TRON Limpiador desinfectacte multiusos</td>
                 	  <td class="text-center">1</td>
                 </tr>
                 <tr>
                 	  <td>Cojines de concentrado TRON Lavaloza de alto rendimiento</td>
                 	  <td class="text-center">1</td>
                 </tr>
                 <tr>
                 	  <td>Cojines de concentrado TRON Desinfectante de baños</td>
                 	  <td class="text-center">1</td>
                 </tr>
                 <tr>
                 	  <td>Obsequio de bienvenida</td>
                 	  <td class="text-center">3</td>
                 </tr>

       	      </tbody><!--Cuerpo -->
       	  </table>
       </div>
  </div><!--Contenido del Kit de Inicio -->
</div><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

   <?php include (APPLICATION_SECTIONS . 'col_izquierdad_redtron.php');?>

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

</div><!--Fin-Fila-->
</div><!--Contenedor-De-La-Pagina-->
<br><br> <br>

