<div class="contenedor"><!--Contenido`de la pagina -->
	<div class="row"><!--contenido de la informacion de la pagina-->

<!--Boton de Ir Arriba -->

  <?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?>

<!--Boton de Ir Arriba -->

<!--Campo de la pagina redtron -->

<?php include (APPLICATION_SECTIONS . 'redtron_tienda_active.php');?>

<!--Campo de la pagina redtron -->

         <div class="col-lg-9">
           <div class="row">
            <div class="cont-titulo-pagos"><!--Titulo -->
                  <h1 class="titulo-principal text-center">Medios de Pago</h1>
            </div><!--Titulo -->
           </div>

            <div class="col-lg-12">
                 <div class="img-medios-pagos"><!--Contenedor de la IMG -->
                   <img src="<?= BASE_IMG_TIENDA ;?>medio_pago.png" class="img-responsive img-pagos" >
             </div><!--Contenedor de la IMG -->
            </div>
         </div>

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

  <?php include (APPLICATION_SECTIONS . 'col_izquierdad_redtron4.php');?>

<!-- llamado =  col_izquierdad_redtron4.php => se enceuntra 4 campos en la columna = red de amigos tron , porductos tron ect-->

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

</div><!--contenido de la informacion de la pagina-->
</div><!--Contenido`de la pagina -->
<br><br><br>


