<div class="contenedor"><!--Contenedor-De-La-Pagina-->
<div class="row"><!--Fila-->

<!--Boton de Ir Arriba -->

  <?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?>

<!--Boton de Ir Arriba -->

<!--Campo de la pagina redtron -->

   <?php include (APPLICATION_SECTIONS . 'redtron_btn_superior.php');?>

<!--Campo de la pagina redtron -->

    <div class="col-lg-9  col-md-9  col-sm-9"><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->
       <div class="row"><!--Titulo-->
       	   <div class="col-lg-12 col-md-12 col-sm-12">
       	   	  <h1 class="titulo-principal">Pases De Cortesia</h1> <br>
       	   </div>
       </div><!--Titulo-->


    <div class="col-lg-3 col-md-3 col-sm-3 contenido-indice"><!--Idice-->
       <h5><strong>INDICE</strong></h5><!--Titulo-->

        <nav class="indice">
           <ul class="list-unstyled">

              <li><a href="#introduccion">Introduccion</a></li>
              <li><a href="#funciona">¿Como Funciona?</a></li>
              <li><a href="#bene-envia">Beneficios para quien lo eniva</a></li>
              <li><a href="#bene-recibe">Beneficio para quien recibe</a></li>
              <li><a href="#obtenerlos">¿Como obtenerlos?</a></li>
              <li><a href="#premiunm">Pases Premium</a></li>

           </ul>
        </nav>
    </div><!--Idice-->

    <div class="col-lg-9 col-md-9 col-sm-9"><!--Informacion-Contendo-Introduccion -->

    	 <div><a name="introduccion"></a><p class="contenido-titulo-Introduccion">Introducción</p> </div> <br><!--Titulo -->

    	 <p class="text-introduccion">Los Pases de Cortesía son una herramienta exclusiva de los Empresarios TRON, creada para facilitar la difusión y promoción de la Tienda Virtual y el Modelo de Negocio TRON Entre amigos alcanzamos, por lo tanto, son sujetos a recibirlos personas que no se encuentran registradas en ninguno de los tres (3) planes. <br><br>
    	 	Los Empresarios TRON, pueden enviarlos a sus amigos y conocidos beneficiando a éstos de los mismos Precios Especiales a que ellos tienen derecho, con la ventaja de que en el link que utilizan para vincular con la página, va asociada la identificación de quien lo envía recibiendo beneficios si la compra es efectiva. Ver Resultado de uso más abajo.
       </p>
    </div><!--Informacion-Contendo-Introduccion -->


    <div class="col-lg-12 col-md-12 col-sm-12"><!--COnt-¿Cómo funcionan los Pases de Cortesía?-->
    	   <div><a name="funciona"></a><p class="contenido-titulos">¿Cómo funcionan los Pases de Cortesía?</p></div><!--Titulo -->
        <p class="text-float-left">
        	Después de iniciada sesión, desde Mi Cuenta, puedes ingresar a la zona de Pases de Cortesía y enviar uno a quien desees. <br>
        	Cuando el beneficiario entra a la Tienda a través del link enviado con el pase, recibe inmediatamente tus precios preferenciales. Si en esa oportunidad no realiza la compra, cuando se decida, dentro del término de la vigencia, puede volver a entrar, siempre a través del link enviado con el pase.
         <br><br>
        </p>

        <div>
        	  <img src="<?= BASE_IMG_EMPRESA ;?>pases-version2.png" class="imagen-float-right">
        </div>
    </div><!--COnt-¿Cómo funcionan los Pases de Cortesía?-->

<!--///////////////////////////////////////////////////-Beneficios para quien lo envía-///////////////////////////////////////////-->

   <div class="col-lg-12 col-md-12 col-sm-12"><!--Contenido-Beneficios -->
      <div><a name="bene-envia"></a><p class="contenido-titulos">Beneficios para quien lo envía</p></div><!--Titulos-->
       <p>El pase enviado por un usuario registrado en el Plan Empresario TRON, lleva implícito su código de usuario y si quien recibe el pase lo aprovecha y compra, puede suceder una de estas tres situaciones: </p> <br><br>

       <div>
       	  <table class="table table-condesed table-hover contenido-tablas tabla-pases-cortesia">
       	  	   <thead><!--Emcabezado -->
       	  	   	   <tr>
       	  	   	   	   <th>Se registra en el plan:</th>
       	  	   	   	   <th>El empresario TRON gana:</th>
       	  	   	   </tr>
       	  	   </thead><!--Emcabezado -->

       	  	   <tbody><!--Cuerpo -->

       	  	   	   <tr>
       	  	   	   	  <td>Comprador Ocasional</td>
       	  	   	   	  <td>Un (1) Pase de Cortesía.</td>
       	  	   	   </tr>
       	  	   	   <tr>
       	  	   	   	  <td>Cliente TRON</td>
       	  	   	   	  <td>Comisiones sobre todas las compras que ese amigo <br> haga en su vida.</td>
       	  	   	   </tr>
       	  	   	   <tr>
       	  	   	   	  <td>Comprador Ocasional</td>
       	  	   	   	  <td>Todo lo anterior + BONIFICACIÓN (ver tipos y tabla de <br> bonificaciones más abajo).</td>
       	  	   	   </tr>

       	  	   </tbody><!--Cuerpo -->
       	  </table>
       </div>

   </div><!--Contenido-Beneficios -->

<!--///////////////////////////////////////////////////-Pases Premium-///////////////////////////////////////////////////////////-->


   <div class=" col-lg-12 col-md-12 col-sm-12"><!--Contenido-Requisitos -->
      <div><a name="premiunm"></a><p class="contenido-titulos">Pases Premium</p></div><!--Titulos-->

      <p>Como premio adicional, cuando 5 pases enviados sean efectivos en el mes (tus amigos compren a través de ellos), recibirás un Pase Premium, el cual te otorgará Precios de Escala C en toda la tienda sin importar la cantidad que compres por una vez. Una vez recibido este pase, tienes 30 días para utilizarlo.
      </p>
   </div><!--Pases Premium-->

<!--////////////////////////////////////////////-Beneficios para quien lo recibe-/////////////////////////////////////////////////-->

   <div class="col-lg-12 col-md-12 col-sm-12"><!--Contenido-Beneficios para quien lo recibe-->
      <div><a name="bene-recibe"></a><p class="contenido-titulos">Beneficios para quien lo recibe</p></div><!--Titulo-->
      <p>Los beneficios dependen del plan en el que se registre quien lo recibe: </p> <br>
      <div>
      	  <table class="table table-condensed table-hover contenido-tablas tabla-pases-cortesia">

      	  	   <thead><!--Emcabezado -->
      	  	   	   <tr>
      	  	   	   	  <th>Se registra en el plan:</th>
      	  	   	   	  <th>Quien lo recibe obtiene:</th>
      	  	   	   </tr>
      	  	   </thead><!--Emcabezado -->

      	  	   <tbody><!--Cuerpo -->
      	  	   	   <tr>
      	  	   	   	   <td>Comprador Ocasional</td>
      	  	   	   	   <td>Precios Especiales de los Amigos TRON.</td>
      	  	   	   </tr>
      	  	   	   <tr>
      	  	   	   	   <td>Cliente TRON</td>
      	  	   	   	   <td>Precios Escala A sin importar la cantidad comprada.</td>
      	  	   	   </tr>
      	  	   	   <tr>
      	  	   	   	   <td>Empresario TRON</td>
      	  	   	   	   <td>Precios Escala C sin importar la cantidad comprada.</td>
      	  	   	   </tr>
      	  	   </tbody><!--Cuerpo -->

      	  </table>
      </div>

   </div><!--Contenido-Beneficios para quien lo recibe-->

<!--////////////////////////////////////-¿Cómo obtener los Pases de Cortesía?-//////////////////////////////////////////////-->

     <div class=" col-lg-12 col-md-12 col-sm-12"><!--¿Cómo obtener los Pases de Cortesía? -->
     	   <div><a name="obtenerlos"></a><p class="contenido-titulos" >	¿Cómo obtener los Pases de Cortesía?</p></div><!--Titulo-->
         <p>Hay varias maneras de obtener Pases de Cortesía:</p>
            <ul>
               <li>Al registrarse como Empresario TRON se obtienen 6 Pases de Cortesía.</li>
               <li>Cuando envías el pase a un amigo y él lo utiliza comprando, el pase se te restituye vía e-mail y se te informa  ue fue exitoso.
               </li>
               <li>Cuando un Empresario TRON compra más de $ 50.000 en productos TRON para el hogar, gana 2 pases.</li>
               <li>Comprando el paquete especial de Pases de Cortesía en el menú Mi Cuenta. Con cargo automático a tu cuenta dinero. Si no tienes saldo a favor, no importa, tienes crédito.
               </li>
            </ul>
     </div><!--¿Cómo obtener los Pases de Cortesía? -->
   </div><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

   <?php include (APPLICATION_SECTIONS . 'col_izquierdad_redtron.php');?>

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

</div><!--Fin-Fila-->
</div><!--Contiene todo Sobre la pagina -->
<br><br><br>


