<?php
    $Pedido_Minimo_Tron   = Session::Get('valor_minimo_pedido_productos');
    $Pedido_Minimo_Indus  = Session::Get('pedido_minimo_productos_fabricados_ta');
?>


<div class="contenedor"><!--Contenedor-De-La-Pagina-->
<div class="row"><!--Fila-->

<!--Boton de Ir Arriba -->

  <?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?>

<!--Boton de Ir Arriba -->

<!--Campo de la pagina redtron -->

<?php include (APPLICATION_SECTIONS . 'redtron_tienda_active.php');?>

<!--Campo de la pagina redtron -->

    <div class="col-lg-9  col-md-9  col-sm-9"><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->
       <div class="row"><!--Titulo-->
       	   <div class="col-lg-12 col-md-12 col-sm-12">
       	   	  <h1 class="titulo-principal">Planes de Registro</h1> <br>
       	   </div>
       </div><!--Titulo-->

<!--///////////////////////////////////////////////////-PLAN EMPRESARIO TRON-/////////////////////////////////////////////////////-->


    <div class="col-lg-12 col-md-12 col-sm-12">
        <div> <p class="contenido-titulos">PLAN EMPRESARIO TRON</p></div>

        <div class="col-lg-8 col-md-8  col-sm-8 "><!--text-float-left -->
			        <p class="text-tron">Es un plan para las personas que además de querer beneficiarse de los productos TRON desean obtener ingresos adicionales a través del modelo de negocio que brinda la red TRON Entre amigos alcanzamos. <br><br>
			        		Las personas inscritas en el Plan Empresario TRON recibirán un código que les permitirá inscribir amigos y podrán hacer una red de consumidores para ganar comisiones por las compras que realicen sus amigos y los amigos de sus amigos, recibirá comisiones hasta el sexto(6to) nivel en profundidad,
			        		<a id="soy" href="<?= BASE_URL ;?>redtron/red_de_amigos_tron#estructura">ver estructura de la red.</a></p>
        </div><!--text-float-left -->

        <div class=" col-lg-4 col-md-4  col-sm-4 "><!--IMG-float-right -->
            <img src="<?= BASE_IMG_EMPRESA ;?>empresarioI.png" class="img-responsive">
        </div><!--IMG-float-right -->

        <div class=" col-lg-12 col-md-12 col-sm-12"><!--text-posicion -bajo -->
            <p class="text-tron">Cada uno de los Empresarios TRON tendrá cuatro (4) frontales en el primer nivel inicialmente, el Empresario TRON recibirá bonificaciones por cada amigo registrado en el Plan Empresario TRON, <a href="<?= BASE_URL ;?>redtron/Bonificaciones">ir a la sección de bonificaciones</a>, el Empresario TRON también podrá inscribir amigos, que no deseen crear red, en el Plan Cliente TRON, formar un grupo con ellos aparte de la red y ganar comisión por las compras que ellos realicen.
            </p>
        </div><!--text-posicion -bajo -->

        <div class="col-lg-12 col-md-12 col-sm-12">
        	  <div class="lista-empresario"> <p>En síntesis, el Empresario TRON contará con:</p><br>
        	  <ul class="list-unstyled lista-empresario-tron">

             <!--Las listas estan horganisadas de la forma = li => span => img => a => text cada etiqueta tiene una clase. -->
        	  	  <li class="lista-empresario-tron"><span class="img-span"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" alt=""></span>Precios Especiales para Amigos TRON.</li>
        	  	  <li class="lista-empresario-tron"><span class="img-span"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" alt=""></span>Invitación a capacitaciones y eventos sobre el modelo de negocio.</li>

        	  	  <li class="lista-empresario-tron"><span class="img-span"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" alt=""></span><a href="#">Pases de Cortesía.</a></li>

        	  	  <li class="lista-empresario-tron"><span class="img-span"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" alt=""></span>Código de usuario para invitar amigos a tu red.</li>
        	  	  <li class="lista-empresario-tron"><span class="img-span"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" alt=""></span><a href="#">Comisiones.</a></li>
        	  	  <li class="lista-empresario-tron"><span class="img-span"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" alt=""></span><a href="#">Bonificaciones.</a></li>
        	  	  <li class="lista-empresario-tron"><span class="img-span"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" alt=""></span>Primas Anuales.</li>
        	  	  <li class="lista-empresario-tron"><span class="img-span"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" alt=""></span>Reconocimiento y estatus por logros alcanzados en tu red.</li>
        	  	  <li class="lista-empresario-tron"><span class="img-span"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" alt=""></span>Acceso a Informes administrativos sobre el desempeño de tu red.</li>
        	  </ul><br><br>
        	 </div>
        </div>

        <!--Boton-registrar-Empresario TRON -->
              <div class="col-lg-3">
                 <a href="#" type="button" class="botones_tron">Registrate ahora!</a>
              </div>
        <!--Boton-registrar-Empresario TRON -->
    </div><!--PLAN EMPRESARIO TRON -->

<!--////////////////////////////////////////////////-PLAN CLIENTE TRON-///////////////////////////////////////////////////////////-->

  <div class="col-lg-12 col-md-12 col-sm-12"><!--PLAN CLIENTE TRON -->
       <div> <p class="contenido-titulos">PLAN CLIENTE TRON</p></div>

       <div class="col-lg-4 col-md-4  col-sm-4"><!--img-float-left -->
           <img src="<?= BASE_IMG_EMPRESA ;?>amigoI.png"/>
       </div><!--img-float-left -->

       <div class="col-lg-8 col-md-8  col-sm-8"><!--text-float-left -->
           <p class="text-tron">Como su nombre lo indica este es el Plan de las personas que desean aprovechar todos los beneficios que ofrecen los productos TRON, convirtiéndose en consumidores habituales de ellos con una compra mensual mínima de <?= $Pedido_Minimo_Tron ;?>. El hacerlo les da derecho a acceder a precios preferenciales aún mejores que en el Plan Comprador Ocasional, no solo en los productos TRON sino también en toda la tienda virtual. Para registrarse en este Plan se debe adquirir el kit de Inicio de productos TRON para el hogar ó comprar <?= $Pedido_Minimo_Indus ;?> en productos Industriales fabricados por Balquimia S.A.S.

           <img src="<?= BASE_IMG_PRODUCTOS ;?>balquimia.png" width="100px"/>
           </p>
       </div><!--text-float-left -->

       <div class="col-lg-12 col-md-12  col-sm-12">
           <p>En síntesis, el Cliente TRON contará con:</p><br>

          <!--Las listas estan horganisadas de la forma = li => span => img => a => text cada etiqueta tiene una clase. -->
            <ul class="list-unstyled">
            	  <li class="lista-empresario-tron"><span class="img-span"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></span>Precios Especiales para Amigos TRON.</li>
            	  <li class="lista-empresario-tron"><span class="img-span"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></span>Invitación a capacitaciones y eventos sobre el modelo de negocio <small>(opcional)</small>.</li>
            </ul><br><br>
       </div>

       <!--Boton-registrar-PLAN CLIENTE TRON-->
        <div class="col-lg-3 col-md-3 col-sm-3">
       	   <a href="#" type="button" class="botones_tron">Registrate ahora!</a>
        </div>
       <!--Boton-registrar-PLAN CLIENTE TRON-->
  </div><!--PLAN CLIENTE TRON -->

<!--///////////////////////////////////-PLAN COMPRADOR OCASIONAL-////////////////////////////////////////////////////////////-->

   <div class="col-lg-12 col-md-12 col-sm-12"><!--PLAN COMPRADOR OCASIONAL -->
       <div> <p class="contenido-titulos">PLAN COMPRADOR OCASIONAL</p></div>

   	   <div class="col-lg-8"><!--text-float-left -->
           <p class="text-tron">En este plan se pueden registrar todas las personas que quieran comprar en nuestra tienda virtual y desean beneficiarse de los precios especiales, ofertas y concursos para ganar descuentos.
           </p>
   	   </div><!--text-float-left -->

   	   <div class="col-lg-4"><!--IMG-float-right -->
          <img src="<?= BASE_IMG_EMPRESA ;?>visitanteI.png"/>
   	   </div><!--IMG-float-right -->

   	   <!--Boton-registrar-PLAN COMPRADOR OCASIONAL-->
         <div class="col-lg-3 col-md-3 col-sm-3 boton-ocacional">
       	    <a href="#" type="button" class="botones_tron">Registrate ahora!</a>
         </div>
       <!--Boton-registrar-PLAN COMPRADOR OCASIONAL-->

    </div><!--PLAN COMPRADOR OCASIONAL -->
  </div><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

  <?php include (APPLICATION_SECTIONS . 'col_izquierdad_redtron4.php');?>

<!-- llamado =  col_izquierdad_redtron4.php => se enceuntra 4 campos en la columna = red de amigos tron , porductos tron ect-->

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

</div><!--Fin-Fila-->
</div><!--Contenedor-De-La-Pagina-->
<br><br> <br>
