<!--Los estilos se  encuentran en la carpeta CSS => documento tron_red_general.css-->

<div class="contenedor"><!--Contenedor-De-La-Pagina-->
<div class="row"><!--Fila-->

<!--Boton de Ir Arriba -->

  <?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?>

<!--Boton de Ir Arriba -->

<!--Campo de la pagina redtron -->

   <?php include (APPLICATION_SECTIONS . 'redtron_btn_superior.php');?>

<!--Campo de la pagina redtron -->


    <div class="col-lg-9  col-md-9  col-sm-9"><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->
       <div class="row"><!--Titulo-->
       	   <div class="col-lg-12 col-md-12 col-sm-12">
       	   	  <h1 class="titulo-principal">Los Productos Tron</h1> <br>
       	   </div>
       </div><!--Titulo-->


    <div class="col-lg-3 col-md-3 col-sm-3 contenido-indice"><!--Idice-->
       <h5><strong>ÍNDICE</strong></h5><!--Titulo-->

        <nav class="indice">
           <ul class="list-unstyled">

              <li><a href="#introduccion">Introdución</a></li>
              <li><a href="#presentacion-produc">Presentación de Productos TRON</a></li>
              <li><a href="#tron-ropa">TRON Detergente para lavar ropa</a></li>
              <li><a href="#tron-baño">TRON Desifectante para baños</a></li>
              <li><a href="#tron-multiusos">TRON Desifectante multiusos</a></li>
              <li><a href="#tron-rendimiento">TRON Lavaloza de alto rendimiento</a></li>
              <li><a href="#precios">Precios</a></li>

           </ul>
        </nav>
    </div><!--Idice-->

    <div class="col-lg-9 col-md-9 col-sm-9"><!--Informacion-Contendo-Introduccion -->

    	 <div><p class="contenido-titulo-Introduccion">Introducción</p> </div> <br><!--Titulo -->

    	 <p class="text-introduccion">BALQUIMIA S.A.S ha desarrollado 4 increibles productos de aseo para el hogar de máxima calidad, éstos son los productos TRON. <br><br>
    	 	Productos creados para la limpieza, higiene y desinfección del hogar, orientados a entornos y objetos cotidianos como la ropa, los baños, pisos, loza y cocina.
    	 </p><a name="presentacion-produc"></a> <br><br><br>

    	  <div class="row">
    	  	<p class="text-right consejo-rojo-right"> <em> Simplemente pruébalos, <br>
    	  		¡Te sorprenderás! </em>
    	  		</p>
    	  </div>
    </div><!--Informacion-Contendo-Introduccion -->


<!--/////////////////////////////////////////////-Presentación de Productos TRON-/////////////////////////////////////////////////-->

    <div class="col-lg-12 col-md-12 col-sm-12"><!--Contenedor - Presentacion del Producto-->
    	  <div><p class="contenido-titulos">Presentación de Productos TRON</p> </div><!--Titulo-->
          <div>
            <a name="tron-ropa"></a>
          </div>

          <div>
       	      <iframe class="video_presentacion_producto" src="//www.youtube.com/embed/IM87aby0DNQ" frameborder="0" allowfullscreen></iframe>

          </div>

    </div><!--Contenedor - Presentacion del Producto-->



<!--/////////////////////////////////////////////-TRON Detergente para lavar-/////////////////////////////////////////////////////-->

    <div class=" col-lg-12 col-md-12 col-sm-12">
        <div><p class="contenido-titulos"><a name="tron-baño"></a>TRON Detergente para lavar ropa</p> </div> <br><!--Titulo -->

        <div class=" col-lg-6"><!--Texto-Float-Left -->
            <p>
               Realza los blancos. <br>
               Protege los colores <br>
               Producto amigable con el medio ambiente. <br><br>
               Fragancias: <em>Jardín de Flores y Alegría Primaveral.</em>
            </p><br>

            <p class="avisos-verder-left"><em>¡Sensación de frescura en tu ropa!</em> </p><!--Aviso =  ¡Sensación de frescura en tu ropa! -->
        </div><!--Texto-Float-Left -->

        <div class=" col-lg-6"><!--IMG-float-right -->
            <img src="<?= BASE_IMG_PRODUCTOS ;?>p_tron1.jpg" class="img-responsive img-producto-detergente">

        </div><!--IMG-float-right -->
    </div>

<!--/////////////////////////////////////////////-TRON Desinfectante de baños-/////////////////////////////////////////////////////-->

     <div class=" col-lg-12 col-md-12 col-sm-12">
        <div><p class="contenido-titulos"><a name="tron-multiusos"></a>TRON Desinfectante de baños</p> </div> <br><!--Titulo -->

        <div class=" col-lg-6"><!--Texto-Float-Left -->
            <p>
               Alto poder desengrasante. <br>
               Elimina el 99,9% de las bacterias. <br>
               Producto amigable con el medio ambiente. <br><br>
               Fragancias:  <em>Frescura Otoñal y Ultramar. </em>
            </p><br>

            <p class="avisos-verder-left"><em>¡Limpieza duradera!</em></p><!--Aviso =  ¡Limpieza duradera! -->
        </div><!--Texto-Float-Left -->

        <div class=" col-lg-6"><!--IMG-float-right -->
            <img src="<?= BASE_IMG_PRODUCTOS ;?>p_tron2.jpg" class="img-responsive img-producto-detergente">

        </div><!--IMG-float-right -->
    </div>

<!--/////////////////////////////////////////////-TRON Desinfectante multiusos-/////////////////////////////////////////////////////-->

     <div class=" col-lg-12 col-md-12 col-sm-12">
        <div><p class="contenido-titulos"><a name="tron-rendimiento"></a>TRON Desinfectante multiusos</p> </div> <br><!--Titulo -->

        <div class=" col-lg-6"><!--Texto-Float-Left -->
            <p>
               Aroma perdurable.<br>
               Elimina el 99,9% de las bacterias. <br>
               Producto amigable con el medio ambiente. <br><br>
               Fragancias:  <em>Canela, Floral, Talco de Bebé y Lavanda.</em>
            </p><br>

            <p class="avisos-verder-left"><em>¡Sanidad y ambientación a la vez!</em></p><!--Aviso =  ¡Sanidad y ambientación a la vez! -->
        </div><!--Texto-Float-Left -->

        <div class=" col-lg-6"><!--IMG-float-right -->
            <img src="<?= BASE_IMG_PRODUCTOS ;?>p_tron3.jpg" class="img-responsive img-producto-detergente">
        </div><!--IMG-float-right -->
    </div>

<!--/////////////////////////////////////////////-TRON Lavaloza de alto rendimiento-/////////////////////////////////////////////////////-->


     <div class=" col-lg-12 col-md-12 col-sm-12">
        <div><p class="contenido-titulos"><a name="precios"></a>TRON Lavaloza de alto rendimiento</p> </div> <br><!--Titulo -->

        <div class=" col-lg-6"><!--Texto-Float-Left -->
            <p>
               Suave con tus manos.<br>
               Alto poder desengrasante. <br>
               Producto amigable con el medio ambiente. <br><br>
               Fragancias:  <em>Naranja Mandarina y Lima Limón.</em>
            </p><br>

            <p class="avisos-verder-left"><em>¡Fácil enjuagabilidad!</em></p><!--Aviso =  ¡Fácil enjuagabilidad! -->
        </div><!--Texto-Float-Left -->

        <div class=" col-lg-6"><!--IMG-float-right -->
            <img src="<?= BASE_IMG_PRODUCTOS ;?>p_tron4.jpg" class="img-responsive img-producto-detergente">
        </div><!--IMG-float-right -->
    </div>

<!--/////////////////////////////////////////////-Precios-/////////////////////////////////////////////////////-->

      <div class=" col-lg-12 col-md-12 col-sm-12">
        <div><p class="contenido-titulos">Precios</p> </div> <br><!--Titulo -->
        <p>Gracias a nuestro novedoso sistema de producto concentrado, empacado en cojines y que actúa como repuesto, mermamos costos, reducimos la contaminación ambiental y lo más importante, no requerimos de menor calidad para competir con excelentes precios. <br><br>
        	Bajo el menú PRODUCTOS TRON, encontrarás una zona especial donde podrás realizar tus compras, observa como los precios disminuyen en la medida que aumentas la cantidad produtos. </p>
    </div>
  </div><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->


<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

   <?php include (APPLICATION_SECTIONS . 'col_izquierdad_redtron.php');?>

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

</div><!--Fin-Fila-->
</div><!--Contenedor-De-La-Pagina-->
<br><br> <br>
