<?php
    $Pedido_Minimo_Tron   = Session::Get('valor_minimo_pedido_productos');
    $Pedido_Minimo_Indus  = Session::Get('pedido_minimo_productos_fabricados_ta');
?>
<!--Los estilos se encuentran en la carpeta CSS => tron_red_amigo_general.css -->
<div class="contenedor"><!--Contenedor-De-La-Pagina-->
<div class="row"><!--Fila-->

<!--Boton de Ir Arriba -->

  <?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?>

<!--Boton de Ir Arriba -->

<!--Campo de la pagina redtron -->

   <?php include (APPLICATION_SECTIONS . 'redtron_btn_superior.php');?>

<!--Campo de la pagina redtron -->

    <div class="col-lg-9  col-md-9  col-sm-9"><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->
       <div class="row"><!--Titulo-->
       	   <div class="col-lg-12 col-md-12 col-sm-12">
       	   	  <h1 class="titulo-principal">La	Red de Amigos TRON</h1> <br>
       	   </div>
       </div><!--Titulo-->


    <div class="col-lg-3 col-md-3 col-sm-3 contenido-indice"><!--Idice-->
       <h5><strong>ÍNDICE</strong></h5><!--Titulo-->

        <nav class="indice">
           <ul class="list-unstyled">
              <li><a href="#introducion">Introdución</a></li>
              <li><a href="#diferencias">Diferencias con Multinivel tradicional</a></li>
              <li><a href="#beneficios">Beneficios</a></li>
              <li><a href="#requisitos">Requisitos</a></li>
              <li><a href="#estructura" id="carlos">Estructura de la red</a></li>
              <li><a href="#diferencias_ilegales">Diferencias en las redes legales de las ilegales</a></li>
           </ul>
        </nav>
    </div><!--Idice-->




    <div class="col-lg-9 col-md-9 col-sm-9"><!--Informacion-Contendo-Introduccion -->
    	 <div></a><p class="contenido-titulo-Introduccion">Introducción</p></div> <br><!--Titulo -->
       <p class="text-introduccion"> <strong>El multinivel de los no-vendedores. <a name="diferencias"></a></strong><br>
       La Red TRON es un modelo de negocio que permite tener ganancias de una manera sencilla y cómoda para tí. Sin tomar pedidos, sin cobrar, sin manejar inventarios. Sólo pasando la voz a tus amigos, parientes o compañeros de trabajo. <br><br>
       Puedes ingresar amigos a tu red sin siquiera contactarlos personalmente, haciendo uso de las herramientas que encontrarás en la sección Funcionalidades Interesantes.
       </p>
    </div><!--Informacion-Contendo-Introduccion -->



    <div class="col-lg-12 col-md-12 col-sm-12"><!--Cont-Diferencias -->
    	   <div><p class="contenido-titulos">Diferencias con Multinivel Tradicional</p></div><!--Titulo -->
        <p>
        	 La Red TRON es un modelo de negocio inspirado en los multiniveles tradicionales pero con diferencias interesantes orientadas a facilitar la gestión de sus usuarios. <br><br>
        </p>

        <div><!--Contenido-Primera-Tabla -->
           <table class="table table-condensed table-hover contenido-tablas">

           	   <thead><!--Emcabezado -->
           	   	   <tr>
           	   	   	   <th class="text-center" >Consideraciones</th>
           	   	   	   <th class="text-center" >Multiniveles tradicionales</th>
           	   	   	   <th class="text-center" >TRON Entre amigos alcanzamos</th>
           	   	   </tr>
           	   </thead><!--Emcabezado -->

           	   <tbody><!--Cuerpo -->
           	   	  <tr>
           	   	  	  <td>Indispensable realizar eventos o reuniones para convocar personas a que ingresen a la Red.</td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-rojo.png" alt=""></td><!--IMG = calificacion -->
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-verde.png" alt=""></td><!--IMG = calificacion -->
           	   	  </tr>

           	   	  <tr>
           	   	  	  <td>Hay que tomar pedidos.</td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-rojo.png"/></td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-verde.png"/></td>
           	   	  </tr>

           	   	  <tr>
           	   	  	  <td>Hay que cobrar.</td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-rojo.png"/></td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-verde.png"/></td>
           	   	  </tr>

           	   	  <tr>
           	   	  	  <td>Hay compromiso de cumplir cuota de ventas.</td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-rojo.png"/></td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-verde.png"/></td>
           	   	  </tr>

           	   	  <tr>
           	   	  	  <td>Hay que manejar inventarios, contar con espacio y hay que clasificarlos.</td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-rojo.png"/></td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-verde.png"/></td>
           	   	  </tr>

           	   	  <tr>
           	   	  	  <td>Hay que entregar los pedidos asumiendo los costos de transporte.</td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-rojo.png"/></td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-verde.png"/></td>
           	   	  </tr>

           	   	  <tr>
           	   	  	  <td>Es suficiente para crear red si ingreso al menos a 4 amigos.	</td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png"/></td>
           	   	  	  <td class="text-center"><a name="beneficios"></a><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td>
           	   	  </tr>

           	   	  <tr>
           	   	  	  <td>Todos los consumidores de los productos ofrecidos se benefician de las bondades de la red.</td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png"/></td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td>
           	   	  </tr>

           	   	  <tr>
           	   	  	  <td>Los productos ofrecidos son de compra mensual indispensable. (Parte de la canasta familiar).</td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png"/></td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td>
           	   	  </tr>

           	   	  <tr>
           	   	  	  <td>El consumo del mercado es de miles de millones de pesos.</td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png"/></td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td>
           	   	  </tr>

           	   	  <tr>
           	   	  	  <td>Los productos pueden salir gratis después de un tiempo.	</td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png"/></td>
           	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td>
           	   	  </tr>

           	   </tbody><!--Cuerpo -->
           </table>

        </div><!--Contenido-Primera-Tabla -->
    </div><!--Cont-Diferencias -->

<!--///////////////////////////////////////////////////-BENEFICIOS-//////////////////////////////////////////////////////////////-->

   <div class=" col-lg-12 col-md-12 col-sm-12"><!--Contenido-Beneficios -->
      <div> <p class="contenido-titulos">Beneficios</p></div><!--Titulos-->

       <table class="table table-condesed table-hover contenido-tablas">

       	   <thead><!--Emcabezado-->
       	   	   <tr>
       	   	   	  <th></th><!--No se Necesita De Emcabezado -->
       	   	   </tr>
       	   </thead><!--Emcabezado-->

       	   <tbody><!--Cuerpo-->
       	   	  <tr>
       	   	  	  <td>PRECIOS ESPECIALES, OFERTAS Y CONCURSOS PARA GANAR DESCUENTOS</td>
       	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td><!--IMG-Calificacion-->
       	   	  </tr>

       	   	  <tr>
       	   	  	<td>PRECIOS PARA AMIGOS TRON <br>
       	   	  		<small>Beneficio que adquieren aquellas personas que consumen mensualmente los productos TRON de aseo y desinfección para el hogar o los productos de la línea industrial fabricados por Balquimia S.A.S. y en su primer pedido compraron kit de inicio o su equivalente en productos industriales.</small>
       	   	  	</td>
       	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td><!--IMG-Calificacion-->
       	   	  </tr>

       	   	  <tr>
       	   	  	  <td>INVITACIÓN A CAPACITACIONES Y EVENTOS SOBRE EL MODELO DE NEGOCIO</td>
       	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td><!--IMG-Calificacion-->
       	   	  </tr>


       	   	  	  <td>PASES DE CORTESÍA <br>
       	   	  	  <small>Para que le otorgue a tus amigos potenciales los Precios Especiales a los que tú tienes derecho, incentivandolos de manera discreta a unirse a tu red.</small>
       	   	  	  </td>
       	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td>
       	   	  </tr>


       	   	  <tr>
       	   	  	  <td>ADQUISICIÓN DE CÓDIGO DE USUARIO PARA INVITAR AMIGOS A LA RED</td>
       	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td><!--IMG-Calificacion-->
       	   	  </tr>

       	   	  <tr>
       	   	  	  <td>COMISIONES <br>
       	   	  	   <small>Sobre las compras de las personas que ingreses a la red y las que ellos ingresen hasta por 6 niveles y comisiones aún más especiales sobre las compras de quienes quieren sólo consumir los productos TRON sin pertenecer a la Red.</small><a name="requisitos"></a>
       	   	  	  </td>
       	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td><!--IMG-Calificacion-->
       	   	  </tr>

       	   	  <tr>
       	   	  	  <td>BONIFICACIONES <br>
       	   	  	  	<small>Por amigos que se inscriban a la red con tu código de usuario y por los que inscriban tus amigos y los amigos de tus amigos hasta 6 niveles de profundidad.</small>
       	   	  	  	</td>
       	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td><!--IMG-Calificacion-->
       	   	  </tr>

       	   	 <tr>
       	   	 <td>PRIMAS ANUALES <br>
       	   	 		<small>Año tras año, los miembros de tu Red renovarán el Derecho de Permanencia y por ello recibirás una prima.</small>
       	   	 </td>
       	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td><!--IMG-Calificacion-->
       	   	  </tr>

       	   	  <tr>
       	   	  	  <td>INFORMACIÓN CONTINUA SOBRE TU NEGOCIO <br>
       	   	  	  <small>Contarás con reportes especializados sobre el desempeño de tu Red para que puedas administrar a tu gusto.</small>
       	   	  	  </td>
       	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td><!--IMG-Calificacion-->
       	   	  </tr>

       	   	  <tr>
       	   	  	  <td>RECONOCIMIENTO Y ESTATUS POR LOGROS ALCANZADOS EN LA RED</td>
       	   	  	  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png"/></td><!--IMG-Calificacion-->
       	   	  </tr>
       	   </tbody><!--Cuerpo-->
       </table>
   </div><!--Contenido-Beneficios -->

<!--///////////////////////////////////////////////////-REQUISITOS-//////////////////////////////////////////////////////////////-->


   <div class=" col-lg-12 col-md-12 col-sm-12"><!--Contenido-Requisitos -->
      <div><p  class="contenido-titulos">Requisitos <a name="estructura"></a></p></div><!--Titulos-->

      <p>Para pertenecer a la Red TRON se debe cumplir los siguientes requisitos:</p>
      <ul>
      	  <li>Registrarse como Empresario TRON y para ello se debe comprar el Kit de Inicio y pagar los Derechos de Inscripción.</li>
         <li>Comprometerse con ingresar como mínimo 4 amigos que se registren en el plan Empresarios TRON.</li>
         <li>Asesorar y motivar a los amigos ingresados para que estos a su vez puedan ingresar también los cuatro (4) amigos que les corresponde.</li>
         <li>Comprar como mínimo <?= $Pedido_Minimo_Tron ;?> pesos mensuales en productos  TRON que se encuentran en la zona HOGAR Y PERSONAL ó si eres comprador de productos industriales, comprar como mínimo <?= $Pedido_Minimo_Indus ;?>  pesos mensuales en productos de la zona INDUSTRIAL fabricados por Balquimia S.A.S. y marcados en la Tienda Virtual con el símbolo :
             <img src="<?= BASE_IMG_PRODUCTOS ;?>balquimia.png" width="100px" />
         </li>
      </ul>
   </div><!--Contenido-Requisitos -->

<!--///////////////////////////////////////////////////-Estructura-//////////////////////////////////////////////////////////////-->

   <div class="col-lg-12 col-md-12 col-sm-12"><!--Contenido-Esctructura-->
      <div>	<p class="contenido-titulos">Estructura de la Red</p></div><!--Titulo-->
      <p>	La Red de Amigos TRON tiene una estructura que permite un crecimiento exponencial, ya que cada persona puede tener cuatro (4) Frontales y cada uno de ellos se puede expandir hasta seis (6) niveles de profundidad, dando como resultado recibir comisiones de una red de más de 5400 usuarios y ése, no es el límite.
      </p>
      <p class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>estructura.jpg" /> <a name="diferencias_ilegales"></a></p>

   </div><!--Contenido-Esctructura-->

<!--////////////////////////////////////-Diferencias entre redes legales e ilegales-//////////////////////////////////////////////-->

     <div class=" col-lg-12 col-md-12 col-sm-12"><!--Diferencias entre redes legales e ilegales <-->
     	   <div><p class="contenido-titulos" >	Diferencias entre redes legales e ilegales</p></div><!--Titulo-->
     	   <p>Existen diferencias fácilmente reconocibles entre las redes legales y las ilegales:</p>
     	   <table class="table table-condesed table-hover contenido-tablas">
     	       <thead>	<!--Emcabezado-->
     	          <tr>
          	   	   <th class="text-center" >Consideraciones</th>
          	   	   <th class="text-center" >Multiniveles tradicionales</th>
          	   	   <th class="text-center" >TRON Entre amigos alcanzamos</th>
     	          </tr>
     	       </thead><!--Emcabezado-->

     	       <tbody><!--cuerpo-->
     	       	<tr>
     	       		  <td>Hay inversión de dinero a cambio de altos intereses.</td>
     	       		  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-rojo.png" /></td>
     	       		  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-verde.png" /></td>
     	       	</tr>

     	       	<tr>
     	       		  <td>Hay posibilidad de operaciones ilegales como lavado de activos.</td>
     	       		  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-rojo.png" /></td>
     	       		  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-verde.png" /></td>
     	       	</tr>

     	       	<tr>
     	       		  <td>A través de la red se dan a conocer y se comercializan productos de consumo.</td>
     	       		  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" /></td>
     	       		  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" /></td>
     	       	</tr>

     	       	<tr>
     	       		  <td>Hay respaldo de empresas legalmente constituidas y con reconocida trayectoria.</td>
     	       		  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" /></td>
     	       		  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" /></td>
     	       	</tr>

     	       	<tr>
     	       		  <td>Se cuenta con registro en Cámara de Comercio, Capacidad de Producción, Registros Sanitarios, Marcas registradas, Revisoría Fiscal, Procesos normalizados.</td>
     	       		  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" /></td>
     	       		  <td class="text-center"><img src="<?= BASE_IMG_TIENDA ;?>positivo-verde.png" /></td>
     	       	</tr>

     	       </tbody><!--cuerpo-->
     	   </table>
     </div><!--Diferencias entre redes legales e ilegales -->
   </div><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->


<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

   <?php include (APPLICATION_SECTIONS . 'col_izquierdad_redtron.php');?>

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

</div><!--Fin-Fila-->
</div><!--Contenedor-De-La-Pagina-->
<br><br> <br>
