<div class="contenedor"><!--Contenedor-De-La-Pagina-->
<div class="row"><!--Fila-->

<!--Boton de Ir Arriba -->

  <?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?>

<!--Boton de Ir Arriba -->

<!--Campo de la pagina redtron -->

   <?php include (APPLICATION_SECTIONS . 'redtron_btn_superior_desactive.php');?>

<!--Campo de la pagina redtron -->

    <div class="col-lg-9  col-md-9  col-sm-9"><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->
       <div class="row"><!--Titulo-->
       	   <div class="col-lg-12 col-md-12 col-sm-12">
       	   	  <h1 class="titulo-principal">Balquimia S.A.S.</h1> <br>
       	   </div>
       </div><!--Titulo-->

        <div class="col-lg-12 col-md-12 col-sm-12"><!--Tecnologías  -->
            <div class="col-lg-3 col-md-3 col-sm-3"><!--IMG-Tecnologias-->
            	  <img src="<?= BASE_IMG_PRODUCTOS ;?>tecnoaplicadas.jpg" class="img-responsive">
            </div><!--IMG-Tecnologias-->

            <div class="col-lg-9 col-md-9 col-sm-9"><!--text-float-right -->
            	    <p class="text-justificado">Balquimia S.A.S. es una empresa colombiana con experiencia en el mercado industrial. Desarrollamos y fabricamos productos de la más alta calidad, con el proposito de brindar las mejores soluciones en limpieza, desinfección y mantenimiento industrial, en sectores como el alimentario, artes gráficas, hotelero, sanidad portátil, materias primas para los industriales del aseo y del reencauche.</p>
            </div><!--text-float-right -->

            <div class="col-lg-12"><!-- text-posicion-baja-->
                <p class="text-justificado">Detergentes, Desinfectantes, Desengrasantes, Desoxidantes, Dieléctricos, Desincrustantes, Removedores de tintas, Desmoldantes, Despercudidores, Abrillantadores y Ceras de varios tipos, son algunos de los productos que usted puede encontrar en Balquimia S.A.S. </p> <br><br>


                <p><strong>PBX:</strong> (2) 488 1616.</p>
                <p><strong>Línea gratuita al cliente:</strong>01 8000 18 TRON <em>(8766).</em></p>
                <p><strong>Dirección:</strong> Cll 35 N° 4-31, Cali - Colombia. </p>
                <h3>Visítanos en: <a href="http://www.balquimia.com/" target="_blank">www.balquimia.com</a></h3>
            </div><!-- text-posicion-baja-->



        </div><!--Tecnologías  -->

   </div><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

 <?php include (APPLICATION_SECTIONS . 'col-izquierdad-redtron10.php');?>

 <!--Llamado = col-izquierdad-redtron10 = en esta vista se presentan 10 campos => red de amigo , porductos tron ect -->

 <!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

</div><!--Fin-Fila-->
</div><!--Contenedor-De-La-Pagina-->
<br><br> <br>
