<div class="contenedor"><!--Contenedor-De-La-Pagina-->
<div class="row"><!--Fila-->

<!--Boton de Ir Arriba -->

  <?php include (APPLICATION_SECTIONS . 'btn_ir_arriba.php');?>

<!--Boton de Ir Arriba -->

<!--Campo de la pagina redtron -->

<?php include (APPLICATION_SECTIONS . 'redtron_tienda_active.php');?>

<!--Campo de la pagina redtron -->

    <div class="col-lg-9  col-md-9  col-sm-9"><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->


       <div class="row"><!--Titulo-->
           <div class="col-lg-12 col-md-12 col-sm-12">
              <h1 class="titulo-principal">Transporte</h1> <br>
           </div>
       </div><!--Titulo-->


       <div class="col-lg-12 col-md-12 col-sm-12"><!--Informacion-Contendo-Transporte -->
       <p class="text-introduccion">La Tienda Virtual le ha asignado a cada producto un subsidio al transporte. Gracias a este subsidio, el valor a pagar por este concepto siempre será menor al valor real del transporte e incluso puede ser gratis. <br><br>
       		Si deseas saber cuanto valdría el transporte de un producto ó de un pedido con varios productos, inicia sesión para que el sistema reconozca cual es tu ciudad, selecciona el o los productos de tu interés y situate en el carrito de compras mediante un clic en el ícono que lo representa, arriba, a la derecha. En el carrito de compras podrás observar cómo cambia el valor del transporte en la medida que aumentas o disminuyes productos y/o cantidades. <br><br>
       		Es interesante anotar que aunque un producto de forma individual ostente un costo de flete, al sumarse todos los subsidios en un pedido de varios productos, el valor del transporte puede ser cero (0). </p>
       	</div><!--Informacion-Contendo-Transporte -->
   </div><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

  <?php include (APPLICATION_SECTIONS . 'col_izquierdad_redtron4.php');?>

<!-- llamado =  col_izquierdad_redtron4.php => se enceuntra 4 campos en la columna = red de amigos tron , porductos tron ect-->

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

</div><!--Fin-Fila-->
</div><!--Contenedor-De-La-Pagina-->
<br><br> <br>
