
<div class="ionix">
    <div class="general">
        <div class="contenido-index">

            <div class="mukSlide">
                <div class="mukSlide1">
                    <?php include "public/wowTRON/slide.php"; ?>
                </div>

                <?php include (APPLICATION_SECTIONS . 'index/menu_lateral_derecho.php');?>

            </div>
            <br style="clear:both;" />

        </div>
    </div>
</div>



<div class="ionix">
    <div class="general pAA30">

<div class="row">
	<div class="col-sm-12">
        <div class="avisos4">
            <a href="<?= BASE_URL ;?>productos/productos_tron">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>cat1.png" id="prv">
            </a>
        </div>


        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/18/Productos Naturales/2">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>cat3.png" id="prv" />
            </a>
        </div>



        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/19/Tecnologia/2">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>cat4.png" id="prv" />
            </a>
        </div>

        <br style="clear:both" />
    </div>
    </div>
    </div>
</div>




<?php include (APPLICATION_SECTIONS . 'productos_destacados_ofertas_noved.php');?>


