
<div class="ionix">
    <div class="general">
        <div class="contenido-index">

            <div class="mukSlide">
                <div class="mukSlide1">
                    <?php include "public/wowTRON/slide.php"; ?>
                </div>
                <div class="mukSlide2">
                    <div class="mukSlideIn">
                        <a href="<?= BASE_URL ;?>redtron/red_de_amigos_tron">
                        <div class="tabAll">
                            <div class="tabIn taC">
                                <div class="col-sm-6 col-xs-6 vcenter taC">
                                    <img src="<?= BASE_IMG_CATEGORIAS_INDEX; ?>icoS2.png" />
                                </div><!--
                                --><div class="col-sm-6 col-xs-6 vcenter taL" style="padding:0 10px 0 0;">
                                    La red de amigos TRON
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="mukSlideIn">
                        <a href="<?= BASE_URL ;?>terceros/plan_compensacion">
                        <div class="tabAll">
                            <div class="tabIn taC">
                                <div class="col-sm-6 col-xs-6 vcenter taC">
                                    <img src="<?= BASE_IMG_CATEGORIAS_INDEX; ?>compensacion.png" />
                                </div><!--
                                --><div class="col-sm-6 col-xs-6 vcenter taL" style="padding:0 10px 0 0;">
                                    Plan de Compensación
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="mukSlideIn">
                        <a href="<?= BASE_URL ;?>redtron/Planes_de_Registro">
                        <div class="tabAll">
                            <div class="tabIn taC">
                                <div class="col-sm-6 col-xs-6 vcenter taC">
                                    <img src="<?= BASE_IMG_CATEGORIAS_INDEX; ?>planes.png" />
                                </div><!--
                                --><div class="col-sm-6 col-xs-6 vcenter taL" style="padding:0 10px 0 0;">
                                    Planes de Registro
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="mukSlideIn">
                        <a href="<?= BASE_URL ;?>redtron/funcionalidades_interesantes">
                        <div class="tabAll">
                            <div class="tabIn taC">
                                <div class="col-sm-6 col-xs-6 vcenter taC">
                                    <img src="<?= BASE_IMG_CATEGORIAS_INDEX; ?>icoS4.png" />
                                </div><!--
                                --><div class="col-sm-6 col-xs-6 vcenter taL" style="padding:0 10px 0 0;">
                                    Funciones Interesantes
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>
            </div>
            <br style="clear:both;" />

        </div>
    </div>
</div>



<div class="ionix">
    <div class="general pAA30">

        <div class="avisos4">
            <a href="<?= BASE_URL ;?>productos/productos_tron">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>cat1.png" id="prv">
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/20/Maquillaje/2"
            class="lista-productos" id-categoria="20" nombre-categoria="MAQUILLAJE">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>cat2.png" id="prv" />
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/18/Productos Naturales/2">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>cat3.png" id="prv" />
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/19/Tecnología/2">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>cat4.png" id="prv" />
            </a>
        </div>

        <br style="clear:both" />

    </div>
</div>




<?php include (APPLICATION_SECTIONS . 'productos_destacados_ofertas_noved.php');?>

