<div class="ionix">
    <div class="general">
    	<div class="contenido-index">
    
            <div class="mukSlide">
                <div class="mukSlide1">
                    <?php include "public/wowTRON/slide.php"; ?>
                </div>
                <div class="mukSlide2">
                    <div class="mukSlideIn">
                    	<a href="<?= BASE_URL ;?>redtron/red_de_amigos_tron">
                        <div class="tabAll">
                            <div class="tabIn taC">
                                <div class="col-sm-6 col-xs-6 vcenter taC">
                                    <img src="public/images/categorias_index/icoS1.png" />
                                </div><!--
                                --><div class="col-sm-6 col-xs-6 vcenter taL" style="padding:0 10px 0 0;">
                                    La red de amigos TRON
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="mukSlideIn">
                    	<a href="<?= BASE_URL ;?>redtron/pases_de_cortesia">
                        <div class="tabAll">
                            <div class="tabIn taC">
                                <div class="col-sm-6 col-xs-6 vcenter taC">
                                    <img src="public/images/categorias_index/icoS2.png" />
                                </div><!--
                                --><div class="col-sm-6 col-xs-6 vcenter taL" style="padding:0 10px 0 0;">
                                    Pases de cortesía
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="mukSlideIn">
                    	<a href="<?= BASE_URL ;?>redtron/Planes_de_Registro">
                        <div class="tabAll">
                            <div class="tabIn taC">
                                <div class="col-sm-6 col-xs-6 vcenter taC">
                                    <img src="public/images/categorias_index/icoS3.png" />
                                </div><!--
                                --><div class="col-sm-6 col-xs-6 vcenter taL" style="padding:0 10px 0 0;">
                                    Planes de registro
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="mukSlideIn">
                        <a href="<?= BASE_URL ;?>redtron/productos_tron">
                        <div class="tabAll">
                            <div class="tabIn taC">
                                <div class="col-sm-6 col-xs-6 vcenter taC">
                                    <img src="public/images/categorias_index/icoS4.png" />
                                </div><!--
                                --><div class="col-sm-6 col-xs-6 vcenter taL" style="padding:0 10px 0 0;">
                                    Funciones Interesantes
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>
            </div>
            <br style="clear:both;" /> 
               
    	</div>
    </div>
</div>



<div class="ionix">
    <div class="general pAA30">

        <div class="avisos4">
            <a href="<?= BASE_URL ;?>productos/productos_tron">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>cat1.png" id="prv">
            </a>
        </div>
        
        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/20/Maquillaje/2"
            class="lista-productos" id-categoria="20" nombre-categoria="MAQUILLAJE">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>cat2.png" id="prv" />
            </a>
        </div>
        
        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/18/Productos Naturales/2">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>cat3.png" id="prv" />
            </a>
        </div>
        
        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/19/Tecnología/2">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>cat4.png" id="prv" />
            </a>
        </div>
        
        <br style="clear:both" />
    
    </div>
</div>




<?php include (APPLICATION_SECTIONS . 'productos_destacados_ofertas_noved.php');?>








<!-- ///  BORRAR JHON JAMES  /// -->
<!-- ///  BORRAR JHON JAMES  /// -->
<!-- ///  BORRAR JHON JAMES  /// -->
<!-- ///  BORRAR JHON JAMES  /// -->
<!-- ///  BORRAR JHON JAMES  /// -->
<!-- ///  BORRAR JHON JAMES  /// -->
<!-- ///  BORRAR JHON JAMES  /// -->
<!-- ///  BORRAR JHON JAMES  /// -->
<!-- ///  BORRAR JHON JAMES  /// -->
<!-- ///  BORRAR JHON JAMES  /// -->







<div class="contenido-index" style="display:none;">
    
    <section id="public">
   
   
         <div class="row">

<!-- ///  slider-tron /// -->

           <div  id="cr-slide" >
             <div class="col-lg-10  col-md-10  col-sm-10 ">
                <section id="slide"class="carousel slide">
                    <ol class="carousel-indicators">
                      <li data-target="#slide" data-slide-to="0" class="active"></li>
                      <li data-target="#slide" data-slide-to="1"></li>
                      <li data-target="#slide" data-slide-to="2"></li>
                      <li data-target="#slide" data-slide-to="3"></li>
                      <li data-target="#slide" data-slide-to="4"></li>
                    </ol>

                    <div class="carousel-inner">
                       <div class="item active">
                         <a href="#"><img src= "<?= BASE_IMG_SLIDER ; ?>1.jpg" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="<?= BASE_URL ;?>redtron/comisiones"> <img src="<?= BASE_IMG_SLIDER ; ?>2.jpg" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="<?= BASE_URL ;?>redtron/red_de_amigos_tron"> <img src="<?= BASE_IMG_SLIDER ; ?>3.jpg" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="<?= BASE_URL ;?>redtron/planes_de_registro"> <img src="<?= BASE_IMG_SLIDER ; ?>4.jpg" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="<?= BASE_URL ;?>redtron/productos_tron"> <img src="<?= BASE_IMG_SLIDER ; ?>5.jpg" class="adaptar"> </a>
                       </div>-

                    </div>

                    <a href="#slide" class="left carousel-control" data-slide="prev">
                      <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>

                     <a href="#slide" class="right carousel-control" data-slide="next">
                      <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </section>
              </div>
           </div>

<!-- ///  slider-tron /// -->


<!-- /// Parte-derecha slider = red-amigos , pases-cortesia , planes , funcionalidades /// -->

          <div class="col-lg-2 col-md-2  col-sm-2" id="info-gn">
               <div class=" row" id="info">
                 <a href="<?= BASE_URL ;?>redtron/red_de_amigos_tron"> <img src="<?= BASE_IMG_EMPRESA ;?>la red.jpg"  class="img-responsive"> </a>
               </div>



               <div class=" row" id="info">
                 <a href="<?= BASE_URL ;?>redtron/pases_de_cortesia"> <img src="<?= BASE_IMG_EMPRESA ;?>pases.jpg"  class="img-responsive" alt=""> </a>
               </div>



               <div class=" row" id="info">
                 <a href="<?= BASE_URL ;?>redtron/Planes_de_Registro"> <img src="<?= BASE_IMG_EMPRESA ;?>planes.jpg"  class="img-responsive" alt="" /> </a>
               </div>


               <div class=" row" id="info">
                 <a href="<?= BASE_URL ;?>redtron/funcionalidades_interesantes"><img src="<?= BASE_IMG_EMPRESA ;?>funcionalidades.jpg" class="img-responsive" alt="" /> </a>
               </div>
         </div>

<!-- /// Parte-derecha slider = red-amigos , pases-cortesia , planes , funcionalidades /// -->

    </div>
   </section>

<!-- /// CATEGORIAS PRINCIPALES DEL INDEX /// -->

       <section id ="menu-izq-otros-productos">
            <div class="row" id="avisos">
              <div class="col-lg-3 col-md-3 col-sm-3">
                <a href="<?= BASE_URL ;?>productos/productos_tron">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>6.jpg" class="img-responsive" id="prv">  </a>
              </div>

              <div class="col-lg-3  col-md-3 col-sm-3">
                <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/20/Maquillaje/2"
                   class="lista-productos" id-categoria ="20" nombre-categoria="MAQUILLAJE">
                  <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>7.jpg" class="img-responsive" id="prv" />
                </a>
              </div>

              <div class="col-lg-3  col-md-3 col-sm-3">
                <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/18/Productos Naturales/2">
                  <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>8.jpg" class="img-responsive" id="prv" />
                </a>
              </div>

              <div class="col-lg-3  col-md-3 col-sm-3">
                <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/19/Tecnología/2">
                  <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>9.jpg" class="img-responsive" id="prv" />
                </a>
              </div>
            </div>
       </section>

<!-- /// CATEGORIAS PRINCIPALES DEL INDEX /// -->

 <!-- INICIA LAS SECCIONES DE DESTACADOS OFERTAS Y NOVEDADES -->
 <div id="contenido-productos">
 <?php include (APPLICATION_SECTIONS . 'productos_destacados_ofertas_noved.php');?>
 </div>
</div>

