<div class="contenido-industrial">
   <section id="public">
         <div class="row">
              <div  id="cr-slide">
             <div class="col-lg-10  col-md-10  col-sm-10 ">
                <section id="slide"class="carousel slide">
                    <ol class="carousel-indicators">
                      <li data-target="#slide" data-slide-to="0" class="active"></li>
                      <li data-target="#slide" data-slide-to="1"></li>
                      <li data-target="#slide" data-slide-to="2"></li>
                      <li data-target="#slide" data-slide-to="3"></li>
                      <li data-target="#slide" data-slide-to="4"></li>
                    </ol>

                    <div class="carousel-inner">
                       <div class="item active">
                         <a href="#">  <img src= "<?= BASE_IMG_SLIDER ; ?>1.jpg" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="#"> <img src="<?= BASE_IMG_SLIDER ; ?>2.jpg" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="#"> <img src="<?= BASE_IMG_SLIDER ; ?>3.jpg" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="#"> <img src="<?= BASE_IMG_SLIDER ; ?>4.jpg" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="#"> <img src="<?= BASE_IMG_SLIDER ; ?>5.jpg" class="adaptar"> </a>
                       </div>

                    </div>

                    <a href="#slide" class="left carousel-control" data-slide="prev">
                      <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>

                     <a href="#slide" class="right carousel-control" data-slide="next">
                      <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </section>
              </div>
           </div>

              <div class=" col-lg-2 col-md-2  col-sm-2" id="info-gn">
               <div class=" row" id="info">
                 <a href="<?= BASE_URL ;?>RedTron/red_de_amigos_tron"> <img src="<?= BASE_IMG_EMPRESA ;?>la red.jpg"  class="img-responsive"> </a>
               </div>


               <div class=" row" id="info">
                 <a href="<?= BASE_URL ;?>RedTron/pases_de_cortesia"> <img src="<?= BASE_IMG_EMPRESA ;?>pases.jpg"  class="img-responsive" alt=""> </a>
               </div>


               <div class=" row" id="info">
                 <a href="<?= BASE_URL ;?>RedTron/Planes_de_Registro"> <img src="<?= BASE_IMG_EMPRESA ;?>planes.jpg"  class="img-responsive" alt="" /> </a>
               </div>


               <div class=" row" id="info">
                 <a href="<?= BASE_URL ;?>RedTron/funcionalidades_interesantes"> <img src="<?= BASE_IMG_EMPRESA ;?>funcionalidades.jpg" class="img-responsive" alt="" /> </a>
               </div>
           </div>
           </div>
   </section>

<!-- CATEGORIAS PRINCIPALES DEL INDEX -->

      <!-- PRIMERA-FILA-CATEGORIAS PRINCIPALES DEL INDEX -->
      <section id ="menu-izq-otros-productos">
        <div class="row" id="avisos">
          <div class=" col-lg-3 col-md-3 col-sm-3">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/4/Línea Alimentaria/1">
              <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_alimentaria.jpg" class="img-responsive" id="prv">  </a>
            </div>

            <div class="col-lg-3  col-md-3 col-sm-3">
              <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/1/Línea Artes Gráficas/1"
                class="lista-productos" id-categoria ="20" nombre-categoria="MAQUILLAJE">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>liena_artes_graficas.jpg" class="img-responsive" id="prv" />
              </a>
            </div>

            <div class="col-lg-3  col-md-3 col-sm-3">
              <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/2/Línea Automotriz/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_automotriz.jpg" class="img-responsive" id="prv" />
              </a>
            </div>

            <div class="col-lg-3  col-md-3 col-sm-3">
              <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/5/Línea Hotelera/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_hotelera.jpg" class="img-responsive" id="prv" />
              </a>
            </div>
          </div>

        <!-- PRIMERA-FILA-CATEGORIAS PRINCIPALES DEL INDEX -->



        <!-- SEGUNDA-FILA-CATEGORIAS PRINCIPALES DEL INDEX -->

          <div class="row" id="avisos">
            <div class=" col-lg-3 col-md-3 col-sm-3">
              <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/3/Línea Mantenimiento Industrial/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_insdustrial.jpg" class="img-responsive" id="prv">  </a>
              </div>

              <div class="col-lg-3  col-md-3 col-sm-3">
                <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/8/Línea Materias Primas/1"
                  class="lista-productos" id-categoria ="20" nombre-categoria="MAQUILLAJE">
                  <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_materias_primas.jpg" class="img-responsive" id="prv" />
                </a>
              </div>

              <div class="col-lg-3  col-md-3 col-sm-3">
                <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/7/Línea Sanidad Portátil/1">
                  <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_sanidad.jpg" class="img-responsive" id="prv" />
                </a>
              </div>

              <div class="col-lg-3  col-md-3 col-sm-3">
                <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/6/Línea Textil/1">
                  <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_textil.jpg" class="img-responsive" id="prv" />
                </a>
              </div>
            </div>
          </section>


<!-- INICIA LAS SECCIONES DE DESTACADOS OFERTAS Y NOVEDADES -->
<div id="contenido-productos">
 <?php include (APPLICATION_SECTIONS . 'productos_destacados_ofertas_noved.php');?>
 </div>
</div>




