
<div class="ionix">
    <div class="general">
    	<div class="contenido-index">

            <div class="mukSlide">
                <div class="mukSlide1">
                    <?php include "public/wowTRON/slide.php"; ?>
                </div>
                <div class="mukSlide2">
                    <div class="mukSlideIn">
                    	<a href="<?= BASE_URL ;?>redtron/red_de_amigos_tron">
                        <div class="tabAll">
                            <div class="tabIn taC">
                                <div class="col-sm-6 col-xs-6 vcenter taC">
                                    <img src="<?= BASE_IMG_CATEGORIAS_INDEX; ?>icoS1.png" />
                                </div><!--
                                --><div class="col-sm-6 col-xs-6 vcenter taL" style="padding:0 10px 0 0;">
                                    La red de amigos TRON
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="mukSlideIn">
                    	<a href="<?= BASE_URL ;?>redtron/pases_de_cortesia">
                        <div class="tabAll">
                            <div class="tabIn taC">
                                <div class="col-sm-6 col-xs-6 vcenter taC">
                                    <img src="<?= BASE_IMG_CATEGORIAS_INDEX; ?>icoS2.png" />
                                </div><!--
                                --><div class="col-sm-6 col-xs-6 vcenter taL" style="padding:0 10px 0 0;">
                                    Pases de cortesía
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="mukSlideIn">
                    	<a href="<?= BASE_URL ;?>redtron/Planes_de_Registro">
                        <div class="tabAll">
                            <div class="tabIn taC">
                                <div class="col-sm-6 col-xs-6 vcenter taC">
                                    <img src="<?= BASE_IMG_CATEGORIAS_INDEX; ?>icoS3.png" />
                                </div><!--
                                --><div class="col-sm-6 col-xs-6 vcenter taL" style="padding:0 10px 0 0;">
                                    Planes de registro
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="mukSlideIn">
                        <a href="<?= BASE_URL ;?>redtron/productos_tron">
                        <div class="tabAll">
                            <div class="tabIn taC">
                                <div class="col-sm-6 col-xs-6 vcenter taC">
                                    <img src="<?= BASE_IMG_CATEGORIAS_INDEX; ?>icoS4.png" />
                                </div><!--
                                --><div class="col-sm-6 col-xs-6 vcenter taL" style="padding:0 10px 0 0;">
                                    Funciones Interesantes
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>
            </div>
            <br style="clear:both;" />

    	</div>
    </div>
</div>


<div class="ionix">
    <div class="general pAA30">

        <div class="avisos4">
            <a href="<?= BASE_URL ;?>productos/productos_por_categoria_individual/4/Línea Alimentaria/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_alimentaria.jpg" id="prv">
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/1/Línea Artes Gráficas/1"
            class="lista-productos">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>liena_artes_graficas.jpg" id="prv" />
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/2/Línea Automotriz/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_automotriz.jpg" id="prv" />
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/5/Línea Hotelera/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_hotelera.jpg" id="prv" />
            </a>
        </div>

        <br style="clear:both" /><br />

        <div class="avisos4">
            <a href="<?= BASE_URL ;?>productos/productos_por_categoria_individual/3/Línea Mantenimiento Industrial/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_insdustrial.jpg" id="prv">
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/8/Línea Materias Primas/1"
            class="lista-productos">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_materias_primas.jpg" id="prv" />
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/2/Línea Sanidad Portatil/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_sanidad.jpg" id="prv" />
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/6/Línea Textil/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_textil.jpg" id="prv" />
            </a>
        </div>

        <br style="clear:both" />

    </div>
</div>


<br /><br />
