<!--
<div class="ionix">
    <div class="general">
    	<div class="contenido-index">

            <div class="mukSlide">
                <div class="mukSlide1">
                      include "public/wowTRON/slide.php"; ?>
                </div>

                  include (APPLICATION_SECTIONS . 'index/menu_lateral_derecho.php');?>

            </div>
            <br style="clear:both;" />

    	</div>
    </div>
</div>
-->

<div class="ionix">
    <div class="general pAA30">

        <div class="avisos4">
            <a href="<?= BASE_URL ;?>productos/productos_por_categoria_individual/4/Línea Alimentaria/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_alimentaria.jpg" id="prv">
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/1/Línea Artes Gráficas/1"
            class="lista-productos">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>liena_artes_graficas.jpg" id="prv" />
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/2/Línea Automotriz/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_automotriz.jpg" id="prv" />
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/5/Línea Hotelera/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_hotelera.jpg" id="prv" />
            </a>
        </div>

        <br style="clear:both" /><br />

        <div class="avisos4">
            <a href="<?= BASE_URL ;?>productos/productos_por_categoria_individual/3/Línea Mantenimiento Industrial/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_insdustrial.jpg" id="prv">
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/8/Línea Materias Primas/1"
            class="lista-productos">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_materias_primas.jpg" id="prv" />
            </a>
        </div>

        <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/7/Línea Sanidad Portatil/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_sanidad.jpg" id="prv" />
            </a>
        </div>

      <!--  <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/6/Línea Textil/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>linea_textil.jpg" id="prv" />
            </a>
        </div>
-->

       <div class="avisos4">
            <a href="<?=BASE_URL;?>productos/productos_por_categoria_individual/6/Carros y Motos/1">
                <img src="<?= BASE_IMG_CATEGORIAS_INDEX ;?>cat5.png"   />
            </a>
        </div>

        <br style="clear:both" />

    </div>
</div>


<br /><br />
