<!--  Css => tron_mejor_experiencia_usuario.css -->

<div class="cont-info-pagina">
  <div class="row">
      <div class="col-lg-12">
			  	    <div>
			  	    	   <!-- Ventana modal -->
			  	    	   <?php include (APPLICATION_SECTIONS . 'mejor_experiencia_usuario.php');?>
			  	    </div>

			  	    <a href="#mejor_experiencia"   data-toggle="modal" data-target="#mejor_experiencia"></a>
      </div>
  </div>
</div> <!-- modal-body -->









