<div class="contenido-carrito-vacio">
    <div class="row">
        <div class="col-lg-12">
             <h2 class="titulo-car-vacio">No ha registrado productos en su carrito de <br> compras !</h2>
           <img src="<?= BASE_IMG_TIENDA ;?>no-productos.png" class="img-responsive img-carrito-vacio">
        </div>

      <div class="col-lg-12">

           <div class="contenedor-boton-comprar"><!--Cont-Boton-Comprar -->
              <a href="<?= BASE_URL ;?>index" class="carrito-comprar">Volver al Inicio</a>
          </div><!--Cont-Boton-Comprar -->

      </div>
    </div>
</div>
<br>