<div class="ionix">
	<div class="general taC pAA50">
    
		<?php if ( Session::Get('kit_combos_eliminados') == TRUE) : ?>
            <h4>Los Combos y el kit de inico, son productos exclusivos para los compradores ocasionales por lo tanto serán eliminados de tu carrito, pero como tienes el privilegio de ser cliente o empresario TRON puedes armar estos paquetes en la sección productos TRON.</h4>
        <?php endif;?>
    
    	<div class="tab">
        	<div class="tabIn p30 taR"><img src="<?= BASE_IMG_TIENDA ;?>empty.png" /></div>
            <div class="tabIn p30 taL"><h2 class="t20 color999">No ha registrado productos en su carrito de compras !</h2></div>
        </div>
        <div class="contenedor-boton-comprar"><!--Cont-Boton-Comprar -->
        <a href="<?= BASE_URL ;?>index" class="btn btn-danger">Volver al Inicio</a>
        </div><!--Cont-Boton-Comprar -->
    
	</div>
</div>


