<!--
    Los Estilos CSS => carpeta CSS => tron_carrito_identificacion.css
          ********* Carrito-paso Indentificacion  *******
-->

<div class="ionix">
	<div class="general pAA30">

        <center>
			<?php if (Session::Get('Id_Area_Consulta') ==  2) : ;?>
            	<img src="<?=  BASE_IMG_TIENDA ;?>line_identificacion.png" />
            <?php else : ?>
            	<img src="<?=  BASE_IMG_TIENDA ;?>line_identificacion_industrial.png" />
            <?php endif ;?>
        </center>

		<!-- //// division_pagina = identificacion /// -->
		<div class="">
			<h3 class="colorBlue ff2 t30 titleM1 mb20"><strong>Paso 1 </strong> <br> Identificación</h3>


			<div class="formulario"> <!-- Contenedor del formulario -->

				<div class="cont-seleccion-ident">
                    <form class="form-group" role="form">

                        <!-- Ingresar -->
                        <a href="#myModal" class="colorfff btn btn-success ingSeInf" data-toggle="modal" data-target="#myModal">
                            <span class="glyphicon glyphicon-user"></span>  Ingresar a mi Cuenta
                        </a>

                        <!-- Registrarse -->
                        <a href="<?= BASE_URL ;?>terceros/registro/" class="colorfff btn btn-success">
                            <span class="glyphicon glyphicon-list-alt"></span> &nbsp; Registrarme para finalizar compra
                        </a>

                        <!-- Pedido-Amigo -->
                        <a href="#" class="colorfff btn btn-success" id ="pedido-amigo">
                            <span class="registrar_amigo"></span> Hacer pedido para un Amigo
                        </a>

                    </form>
				</div>
			</div>

            <hr />

            <div class="cont-formulario pAA30 contFormPedAmig" style="display:none;">
                <form class="form-horizontal" role="form">

                <div class="form-group"><!--Cedula de tu amigo -->
                    <label for ="cedula-amigo" class="col-sm-5 col-xs-5 label-control text-label vcenter">Número cédula de tu amigo :</label><!--
                    --><div class="col-sm-7 col-xs-7 vcenter">
                    	<input type="text" class="form-control" id="cedula-amigo">
                    </div>
                </div>


                <div class="taR">
                	<button type ="button" class="btn-ing-por-amigo btn btn-danger" id ="btn-ing-por-amigo" >Ingresar por amigo</button>
                </div>

                </form>
            </div><!-- Contenedor del formulario -->

		</div>

        <br /><br /><br />

    </div>
</div>




