<!-- Los estilos Css se encuentran en el documento CSS => tron_carrito_forma_pago.css
                    ******** Paso 4 = Seleccion de froma de pago ********
-->
<div class="ionix">
	<div class="general pAA30">
		<div id="formaspago">

			<center>
				<?php if (Session::Get('Id_Area_Consulta') ==  2) : ;?>
                    <img src="<?=  BASE_IMG_TIENDA ;?>line_forma_pago.png" class="">
                <?php else : ?>
                    <img src="<?=  BASE_IMG_TIENDA ;?>line_forma_pago_industrial.png" class="">
                <?php endif ;?>
			</center>

			<h3 class="colorBlue ff2 t30 titleM1">
            	<strong>Paso 4 </strong> <br>
				<small class="sutb-titulo">seleccione la forma de pago.</small>
            </h3>

            <div class="option-pago1">
            	<div class="tabAll"><div class="tabIn">
            		<img src="<?= BASE_IMG_TIENDA ;?>forma-pago1.png" class="img-pago1" id="1" />
                </div></div>
            </div><!-- Forma-pago1 -->

            <div class="cont-btn-slec-forma-pago"><!-- contenedor del boton  -->
                <a href="<?= BASE_URL ;?>">
                    <button type="button" class="btn-forma-pagon btn btn-danger">Seleccionar forma de pago más tarde</button>
                </a>
            </div>

		</div>
		<br /><br /><br />

	</div>
</div>
