
<?php
     $numero_pedido         = Session::Get('numero_pedido');
     $vr_total_pedido       = Session::Get('vr_total_pedido');
     $baseIva               = Session::Get('Vr_Base_Iva');
     $pnombre               = utf8_encode(Session::Get('nombre_cliente'));
     $email                 = utf8_encode(Session::Get('email'));
     $identificacion        = Session::Get('identificacion');
     //$signature             = md5 ("4uiapnu24digpg1gb05pntuge3~511623~".$numero_pedido."~".$vr_total_pedido."~COP")
     $signature             = md5 ("6u39nqhq8ftd0hlvnjfs66eh8c~500238~TestPayU~".$vr_total_pedido."~COP");
     //<form name="formPaypal" action="https://gateway.payulatam.com/ppp-web-gateway" method="post" id="">
     //<input type="hidden" name="merchantId"          id="merchantId"             value="511623" />
    // <input type="hidden" name="accountId"           id="accountId"              value = "512832">
    // <input type="hidden" name="signature"           id="signature"              value = "<?= $signature ;
    //<input type="hidden" name="referenceCode"       id="referenceCode"          value = "<?= $numero_pedido ;
?>
<br />
<h2>Estamos ingresando al sistema de pagos en línea, espere unos segundos por favor....</h2>
<br /> <br /> <br /> <br /> <br />
<form name="formPaypal" action="https://stg.gateway.payulatam.com/ppp-web-gateway/" method="post" id="">

    <input type="hidden" name="description"         id="description"            value = "<?= "Pedido No. ".$numero_pedido ; ?>" />
    <input type="hidden" name="amount"              id="amount"                 value = "<?= $vr_total_pedido; ?>" />
    <input type="hidden" name="tax"                 id="tax"                    value = "<?= $vr_total_pedido -  $baseIva ;?>" />
    <input type="hidden" name="taxReturnBase"       id="taxReturnBase"          value = "<?= $baseIva ; ?>" />
    <input type="hidden" name="baseDevolucionIva"   id="baseDevolucionIva"      value = "0" />


    <input type="hidden" name="currency"            id="currency"               value = "COP">
    <input type="hidden" name="payerFullName"       id="buyerEmail"             value = "<?= $pnombre ;?>">
    <input type="hidden" name="buyerEmail"          id="buyerEmail"             value = "<?=  $email ; ?>">
    <input type="hidden" name="payerDocument"       id="payerDocument"          value = "<?= $identificacion ; ?>">
    <input name="confirmationUrl"                   type="hidden"               value = " <?= BASE_URL ;?>carrito/Forma_Pago_Pedido_Payu_Latam_Confirmacion" >



   <input type="hidden" name="merchantId"           id="merchantId"         value="500238" />
   <input type="hidden" name="ApiKey"               id="ApiKey"             value="6u39nqhq8ftd0hlvnjfs66eh8c~500238~TestPayU" />
   <input type="hidden" name="referenceCode"       id="referenceCode"       value = "<?= $numero_pedido ; ?>" />
   <input type="hidden" name="accountId"            id="accountId"          value="500537">
   <input type="hidden" name="signature"            id="signature"          value="be2f083cb3391c84fdf5fd6176801278">
   <input type="hidden" name="test"                 id="test"               value="1">
   <input type="hidden" name="buyerEmail"           id="buyerEmail"         value="jhonjamesmg@hotmail.com">

</form>

