<!--
    Los Estilos CSS => carpeta CSS => tron_carrito_identificacion.css
          ********* Carrito-paso Indentificacion  *******
-->

<div class ="contenedor"><!--contenedor principal -->
    <div class =" row">

     <!--- //// Linea de tiempo //// -->
          <div class="col-lg-12">
              <div>
                   <p class="text-center">
                      <?php if (Session::Get('Id_Area_Consulta') ==  2) : ;?>
                          <img src="<?=  BASE_IMG_TIENDA ;?>line_identificacion.png" class="line_tiempo">
                        <?php else : ?>
                          <img src="<?=  BASE_IMG_TIENDA ;?>line_identificacion_industrial.png" class="line_tiempo">
                        <?php endif ;?>
                   </p>
              </div>
          </div>
     <!--- //// Linea de tiempo //// -->


     <!-- //// division_pagina = identificacion /// -->
         <div class="cuerpo-pagina">

         <!-- Titulo -->
        	   <div class =" col-lg-12 col-md-12 col-sm-12">
               <div class="cont-titulo"><!-- Contenedor-titulo -->
               	   <h2 class="titulo"><strong>Paso 1 </strong> <br> Identificación </h2><!--Titulo -->
               </div><!-- Contenedor-titulo -->
        	   </div>

   <div class ="formulario"> <!-- Contenedor del formulario -->

        <!-- Seleccion = identificacion -->
        <div class =" col-lg-12 col-md-12 col-sm-12">
			        	<div class="cont-seleccion-ident">
                     <form class ="form-group" role ="form">

                    <!-- Ingresar -->
                      <div class ="cont-ingresar">
                         <a href="#myModal" class="seleccion-indt-label" data-toggle="modal" data-target="#myModal">
                            <span class="glyphicon glyphicon-user"></span>  Ingresar a mi Cuenta
                         </a>
                      </div>

                    <!-- Registrarse -->
                      <div class ="cont-registrar">
                           <a href="<?= BASE_URL ;?>terceros/registro/" class="seleccion-indt-label">
      		        			       <span class="glyphicon glyphicon-list-alt"></span> Registrarme para finalizar compra
                          </a>
      		        		</div>

                    <!-- Pedido-Amigo -->
      		        		<div class ="cont-pedido-amigo">
      		        			 <a href="#" class="seleccion-indt-label" id ="pedido-amigo">
                           <span class="registrar_amigo"></span> Hacer pedido para un Amigo
                        </a>
      		        		</div><!-- Pedido-Amigo -->

                     </form>
			        	</div>
        </div>
        <!-- Seleccion = identificacion -->


        <!-- /// Hacer pedido amigo /// -->
            <div class =" col-lg-12 col-md-12 col-sm-12 pedido-amigo" id="pedido_amigo">

                <div class="cont-formulario"><!-- Contenedor del formulario -->
                	   <form class="form-horizontal" role="form">

                         <div class="form-group"><!--Cedula de tu amigo -->
                         	   <label for ="cedula-amigo" class ="col-lg-5 label-control text-label">Número cedula de tu amigo :</label>
                             <div class="col-lg-7">
                               <input type ="text" class ="form-control" id ="cedula-amigo">
                             </div>
                         </div>

                        <!-- <div class="form-group">
                         	   <label for="usuario-amigo" class ="col-lg-5 label-control text-label">Código usuario de tu amigo :</label>
                            <div class="col-lg-7">
                               <input type="text" class= "form-control" id ="usuario-amigo">

                            </div>
                         </div>
                         -->

                         <div class ="cont-btn-ing-amigo"><!-- boton -->
                         	   <button type ="button" class ="btn-ing-por-amigo" id ="btn-ing-por-amigo" >Ingresar por amigo</button>
                         </div><!-- boton -->

                	   </form>
                </div><!-- Contenedor del formulario -->

            </div>

        <!-- /// Hacer pedido amigo /// -->

   </div><!-- Contenedor del formulario -->

         </div>
     <!-- //// division_pagina = identificacion /// -->


    </div>
</div><!--contenedor principal -->
<br><br><br>



