<!-- MARZO 03 DE 2015
    CONTENIDO DINÁMICO VIA AJAX DEL USUARIO SELECCIONADO -->
<?php
    //Session::Set('cantidad_direcciones',0);
    $CantidadDirecciones = Session::Get('cantidad_direcciones') ;
    $nombre_usuario_pedido = Session::Get('nombre_usuario_pedido');
 ?>


   <div class="fila-direcciones" style="width:100%;"><!-- Direccion -->
         <?php if  ( $CantidadDirecciones == 0 ) :?>
            <div class="text-center">
               <a type="button" class="btn btn-success btn-editar-direccion" nombre-usuario="<?=$nombre_usuario_pedido ;?>" href="#" ><h4>Crear dirección para enviar su pedido</h4></a>
            </div>
        <?php else :?>

           <span>Haga click sobre el recuadro y seleccione la dirección a donde será enviado el pedido. </span> <br>

           <div class="text-center"><br>
              <?php
               $I = 0;
               foreach($this->Direcciones as $Direccion) {
                    include (APPLICATION_CODS.'campos_direccion_usuario.php'); // Carga las variables direcciones
                    include (APPLICATION_SECTIONS.'carrito/carrito_crear_editar_direccion_datos.php');
                    }
                ?>
            <?php endif ;?>
           </div>
        <br>

        <div class="text-center">

            <?php if  ( $CantidadDirecciones >=1 && $CantidadDirecciones < 3 ) :?>
                <a type="button" class="btn btn-success btn-editar-direccion" nombre-usuario="<?=$nombre_usuario_pedido ;?>" href="#" >Crear otra dirección para enviar su pedido</a>
            <?php endif ;?>

            <?php if ( $CantidadDirecciones > 0 ) :?>
                    <button type="button" class="btn-continuar btn btn-primary">Continuar</button>
            <?php endif ;?>

        </div>

</div>

