<!-- Los Estilos css Se encuentran en CSS => tron_carrito_confi_envio.css -->
<?php
    $CantidadDirecciones = Session::Get('cantidad_direcciones') ;

 ?>

<div class="ionix"><!-- Contenedor principal -->
	<div class="general pAA30">

        <center>
			<?php if (Session::Get('Id_Area_Consulta') ==  2) : ;?>
            	<img src="<?=  BASE_IMG_TIENDA ;?>linea_confirmacion_envio.png" class="">
            <?php else : ?>
            	<img src="<?=  BASE_IMG_TIENDA ;?>linea_confirmacion_envio_industrial.png" class="">
            <?php endif ;?>
        </center>


  		<div>

        	<h3 class="colorBlue ff2 t30 titleM1">
            	<strong>Paso 2</strong><br>
        		<small class="sutb-titulo">Usuario Pedido y Confirmación dirección de envío</small>
            </h3>

  			<?php include(APPLICATION_SECTIONS .'barra_usuraios.php') ;?>

<br/>

			<!-- Formulario -->

            <!-- Direccion -->
			<?php include "views/carrito/finalizar_pedido_direccion_usuario.phtml"; ?>

			<?php include (APPLICATION_SECTIONS . '/carrito/carrito_crear_editar_direccion.php');?>
            <?php include (APPLICATION_SECTIONS . 'ventana_mensaje_error.php');?>

            <br /><br /><br />
		</div>
	</div>
</div>
