<div id="contenido-productos">
  <div class="carrito-compras">
     <div class=" row"><!--Inicio-Fila = Contenido De La Tabla -->
          <?php if (Session::Get('imagen_resumen_pedido')== TRUE) : ; ?>
          <div class="col-lg-12 col-md-12 col-sm-12">
              <div>
                   <p class="text-center">
                     <img src="<?=  BASE_IMG_TIENDA ;?>line_resumen_pedido.png">
                   </p>
              </div>
          </div>
        <?php else : ;?>
              <h3 class="text-center titulo">
                <strong>
                     Carrito de Compras
                </strong>
               </h3>
        <?php endif;?>
         <div class="col-lg-12 col-md-12 col-sm-12"><!--Tabla Cliente TRON -->
          <table class="table">

           <?php include (APPLICATION_SECTIONS . 'carrito_titulos.php');?>
           <?php include (APPLICATION_SECTIONS . 'carrito_contenido.php');?>
           <?php include (APPLICATION_SECTIONS . 'carrito_totales.php');?>

         </table>
       </div>
        <?php include (APPLICATION_SECTIONS . 'carrito_botones.php');?>
</div>
 </div>
 </div>

 <br><br><br>>
