<div class="ionix">
	<div class="general taC pAA50">



    	<div class="tab">
        	<div class="tabIn p30 taR"><img src="<?= BASE_IMG_TIENDA ;?>bono.png" /></div>
            <div class="tabIn p30 taL text-center"><h2 class="t20 color999">
            Apreciado usuario, <br>Tu pedido ha sido pagado utilizando tus puntos y/o comisiones. <br>
            Felicitaciones por tu gestión, ahora iniciaremos el proceso despacho.</h2></div>
        </div>
        <div class="contenedor-boton-comprar"><!--Cont-Boton-Comprar -->
        <a href="<?= BASE_URL ;?>index" class="btn btn-danger">Volver al Inicio</a>
        </div><!--Cont-Boton-Comprar -->

	</div>
</div>

