 <!--EL INICIO DEL BOY SE ENCUENTRA EN EL HEADER UBICADO EN application_sections/email/header.php :-->

<!-- EN ESTE ARCHIVO SÓLO SE COLOCA LA INFORMACIÓN, CUERPO DEL CORREO. EL CONTROLADOR Y METODO RESPECTIVO SE ENCARGA
     DE UNIR LAS PARTES
 -->

       	  <div>
                <h4>#_SALUDO_#</h4>
              <p style="text-align: justify;">

                Para activar tu cuenta de usuario y finalizar el registro, presiona el siguiente enlace : #_ENLACE_ACTIVA_CUENTA_#
                desde donde podrás cambiar tu contraseña y a partir de allí, ingresar a la tienda virtual.
              </p>
              <p>
                #_CODIGO_GENERADO_#
              </p>


       	  </div>

       </div>
  </body>


</html>

