<!DOCTYPE html>
<html lang='es'>
  <head>
      <meta charset='UTF-8' />
      <meta http-equiv='Content-Type' content='text/html;' />
      <title> </title>
  </head>

  <body>
       <div style="width: 85%; margin: 0px auto; text-align: justify; display: block;font-family: arial; ">
       	  <!-- Logo -->
       	  <div>
                <img src="#_LOGO_#" ><!--Logo tron -->
       	  </div><br>


       	  <!-- Texto -->
       	  <div>
                <h4>#_SALUDO_#</h4>
              <p style="text-align: justify;">

                Para activar tu cuenta de usuario y finalizar el registro, presiona el siguiente enlace : #_ENLACE_ACTIVA_CUENTA_#
                desde donde podrás cambiar tu contraseña y a partir de allí, ingresar a la tienda virtual.
              </p>
             <br>
       	  	<br>
       	  	<br>

       	  </div>

       </div>
  </body>





  <footer>
   <div style="width: 85%; margin: 0px auto; text-align: justify; display: block;font-family: arial; font-size: 12px; ">
     Tu éxito es el éxito de toda esta comunidad de amigos, por eso, si tienes dudas,
     consúltanos a: contactos@entreamigosalcanzamos.com que nuestra misión es servirte. <br /><br><br /> <em>
     TRON Entre amigos alcanzamos.</em> <br /><br /><br /> <hr />
     <p style='font-size:9px; text-align:justify;width:1000%; margin:0 auto;'>
     Este correo electrónico es generado automáticamente.</p>
   </div>
  </footer>

</html>

