
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <style type="text/css">
        body {
          /*font-family: 'Roboto', sans-serif;*/
          font-family: 'Raleway', sans-serif;
        }
    </style>
  </head>
<body>

						<div style="width: 80%;">
						<div  style="vertical-align: middle; text-align: center;  width: 60%;">
										<h1> BALQUIMIA S.A.S.</h1>
                    <h2> COMUNICADO A NUESTROS CLIENTES </h2>
                    <h3> FACTURACIÓN ELECTRÓNICA </h3>
										<br>
						</div>
            <div  style="text-align: justify;">
              Nos permitimos informar que actualmente <strong> BALQUIMIA S.A.S </strong> se encuentra en proceso de implementación
              de la factura electrónica de acuerdo con lo establecido en el decreto 2242 de 2015 emitido por la DIAN. <br><br>
              El proveedor tecnológico elegido es <strong> Carvajal Tecnología y Servicios S.A.S.</strong>
              <br> <br>
              Por lo anterior solicitamos nos envíen los siguientes datos a la dirección electrónica:
              contabilidad@balquimia.com
              <ol>
                <li>Rut actualizado </li>
                <li>Nombre de la persona de contacto</li>
                <li>Cargo de la persona de contacto</li>
                <li>Número de teléfono de la persona de contacto</li>
                <li>Correo de la persona de contacto <small>( Pueden ser varios correos )</small></li>
              </ol>

            <br>

            Toda comunicación a cerca de la factura así como su representación gráfica en formato PDF, será enviada al(os) correo(s) indicados por ustedes.
            <br><br><br>
            Agradecemos su respuesta a la mayor brevedad posible, cordialmente, <br><br>

              <div style ="text-align : left;">
              <img src="http://www.balquimiaventasonline.com/public/images/firmas/laura.png" ><!--Logo tron -->
              </div>

            </div>
      </div>
</body>
</html>





