

    <h3>¡ Opss... !.... ¿ Es un chiste ?</h3>
    <p style="text-align: justify;">
							Es cierto que nuestros productos son muy rendidores pero…. ¿ 3 meses sin comprar ? <br><br>
							Recuerda que por estatutos de la empresa, pasados  3 meses sin haber hecho sonar la registradora perderás el status de
							<strong>Empresario TRON</strong> y pasarás a ser <strong>Cliente TRON</strong>,
							claro que como cliente conservarás los mismos precios, pero te perderás la posibilidad de ganar comisiones sobre las compras
							que realicen los integrantes de tu red.
							<br>
							<br>
							Actualmente tienes: <strong> #_CANT_USUARIOS_# </strong> usuarios bajo tu red, los cuales podrías " Perder " si no realizas la compra reglamentaria de nuestros <strong>Productos TRON</strong> antes de que finalice este mes...<br>Tú decides... aún estás a tiempo.
    </p>






