<!DOCTYPE html>
<html lang='es'>
  <head>
      <meta charset='UTF-8' />
      <title> </title>
  </head>

  <body>
       <div style="padding-top: 150px; width: 95%; margin: 0px auto; text-align: justify; display: block; ">
       	  <!-- Logo -->
       	  <div>
            <a href="<?= BASE_URL ;?>">
             <img src= "<?= BASE_IMG_EMPRESA ; ?>logo.png" class="img-logo" >
           </a>
       	  </div><br>

       	  <!-- Texto -->
       	  <div>
       	  	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum consectetur repellat nostrum perspiciatis veritatis necessitatibus suscipit possimus quasi obcaecati. Magni possimus rem, culpa molestiae velit laudantium, porro voluptate commodi dignissimos.
       	  	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum consectetur repellat nostrum perspiciatis veritatis necessitatibus suscipit possimus quasi obcaecati. Magni possimus rem, culpa molestiae velit laudantium, porro voluptate commodi dignissimos.
       	  	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum consectetur repellat nostrum perspiciatis veritatis necessitatibus suscipit possimus quasi obcaecati. Magni possimus rem, culpa molestiae velit laudantium, porro voluptate commodi dignissimos.
       	  	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum consectetur repellat nostrum perspiciatis veritatis necessitatibus suscipit possimus quasi obcaecati. Magni possimus rem, culpa molestiae velit laudantium, porro voluptate commodi dignissimos.
       	  	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum consectetur repellat nostrum perspiciatis veritatis necessitatibus suscipit possimus quasi obcaecati. Magni possimus rem, culpa molestiae velit laudantium, porro voluptate commodi dignissimos. <br><br>
       	  	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum consectetur repellat nostrum perspiciatis veritatis necessitatibus suscipit possimus quasi obcaecati. Magni possimus rem, culpa molestiae velit laudantium, porro voluptate commodi dignissimos.
       	  	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum consectetur repellat nostrum perspiciatis veritatis necessitatibus suscipit possimus quasi obcaecati. Magni possimus rem, culpa molestiae velit laudantium, porro voluptate commodi dignissimos.
       	  	Lorem ipsum dolor sit amet, consect <br>
       	  	<br>
       	  	<br>

       	  </div>
       </div>
  </body>
  <footer>
  </footer>
</html>
 