<!-- vista => elimnar_cuenta_correo.phtml
     Css   => tron_eliminar_cuenta_correo.css   -->
<div  class="contenedor_eliminar_cuenta">
	<div class="info_eliminar_cuenta">
	    <div class="row">
	       <!-- logo tron -->
	    	   <div class="col-lg-12 col-md-12 col-sm-12">
	    	   	    <div>
   	   	    	    <div><!-- Titulo -->
   	   	    	    	  <h3 class="text-center titulo_eliminar_registro">¡ Ya hemos eliminado tu registro ! </h3>
   	   	    	    </div>
	    	   	    </div>
	    	   </div>
	    </div>

	    <div class="row">
	       <!-- informacion -->
	       <div class="col-lg-12 col-md-12 col-sm-12 ">
	           <div>
                 <p>De acuerdo a tu solicitud , hemos eliminado tu email de nuestro sitio</p>
                 <p class="text-center"><a href="#" class="vinculo_direccion">entreamigosalcanzamos.com</a></p>
	           </div>
	           <!-- img -->
	           <div>
	           	   <img src="<?= BASE_IMG_EMPRESA;?>eliminar-cuenta-correo.png" class="img_manos" >
	           </div><br>
	           <!-- text -->
	           <div>
	           	    <p>Te invitamos a que pronto nos visites y asi puedas conocer y beneficiarte de las ventajas de pertenecer a este modelo de negocio,</p>
                 <p class="text-center"><a href="#" class="vinculo_direccion">entreamigosalcanzamos.com</a></p>
	           </div>
	       </div>
	    </div>
	</div>
</div>

