 <!--EL INICIO DEL BOY SE ENCUENTRA EN EL HEADER UBICADO EN application_sections/email/header.php :-->

<!-- EN ESTE ARCHIVO SÓLO SE COLOCA LA INFORMACIÓN, CUERPO DEL CORREO. EL CONTROLADOR Y METODO RESPECTIVO SE ENCARGA
     DE UNIR LAS PARTES
 -->

       	  <div>
                <h4>#_SALUDO_#</h4>
              <p style="text-align: justify;">

                #_CODIGO_GENERADO_#
              </p>


       	  </div>

       </div>
  </body>


</html>

