 <!--EL INICIO DEL BOY SE ENCUENTRA EN EL HEADER UBICADO EN application_sections/email/header.php :-->

<!-- EN ESTE ARCHIVO SÓLO SE COLOCA LA INFORMACIÓN, CUERPO DEL CORREO. EL CONTROLADOR Y METODO RESPECTIVO SE ENCARGA
     DE UNIR LAS PARTES
 -->
       	  <div>
              <h4>Hola, #_NOMBRE_AMIGO_#</h4>
              <p style="text-align: justify; line-height: 20px">
                <em>#_NOMBRE_QUIEN_ENVIA_INVITACION_#</em>, te envía un enlace para que conozcas un modelo de negocio interesante donde podrás encontrar no sólo grandes descuentos sino también la posibilidad de generar ingresos para tí. <br/>
                <a href="#_ENLACE_#">Presiona este enlace</a>, vista nuestra página y conoce más acerca de esta gran oportunidad !!!
              </p>
              <br />
              <p style="text-align: right; font-style:italic; line-height: 20px">
                  #_MENSAJE_OPCIONAL_#
              </p>
              <br />
              <p style="text-align: right; font-style:italic; font-weight: bold;">
                  #_NOMBRE_QUIEN_ENVIA_INVITACION_#
              </p>



       	  </div>

       </div>
  </body>



</html>

