<!DOCTYPE html>
<html lang='es'>
  <head>
      <meta charset='UTF-8' />
      <meta http-equiv='Content-Type' content='text/html;' />
      <title> </title>
  </head>

  <body>
       <div style="width: 85%; margin: 0px auto; text-align: justify; display: block;font-family: arial; font-size: 14px;">
       	  <!-- Logo -->
       	  <div>
                <img src="#_LOGO_#" ><!--Logo tron -->
       	  </div><br>


       	  <!-- Texto -->
       	  <div>
              <h4>Hola, #_NOMBRE_AMIGO_#</h4>
              <p style="text-align: justify; line-height: 20px">
                <em>#_NOMBRE_QUIEN_ENVIA_INVITACION_#</em>, te envía un enlace para que conozcas un modelo de negocio interesante donde podrás encontrar no sólo grandes descuentos sino también la posibilidad de generar ingresos para tí. <br/>
                <a href="#_ENLACE_#">Presiona este enlace</a>, vista nuestra página y conoce más acerca de esta gran oportunidad !!!
              </p>
              <br />
              <p style="text-align: right; font-style:italic; line-height: 20px">
                  #_MENSAJE_OPCIONAL_#
              </p>
              <br />
              <p style="text-align: right; font-style:italic; font-weight: bold;">
                  #_NOMBRE_QUIEN_ENVIA_INVITACION_#
              </p>

             <br>
       	  	<br>
       	  	<br>

       	  </div>

       </div>
  </body>





  <footer>
   <div style="width: 85%; margin: 0px auto; text-align: justify; display: block;font-family: arial; font-size: 12px; ">
     Tu éxito es el éxito de toda esta comunidad de amigos, por eso, si tienes dudas,
     contáctanos en : contactos@entreamigosalcanzamos.com que nuestra misión es servirte. <br /><br><br /> <em>
     TRON Entre amigos alcanzamos.</em> <br /><br /><br /> <hr />
     <p style='font-size:9px; text-align:justify;width:1000%; margin:0 auto;'>
     Este correo electrónico es generado automáticamente.</p>
   </div>
  </footer>

</html>

