 <!--EL INICIO DEL BOY SE ENCUENTRA EN EL HEADER UBICADO EN application_sections/email/header.php :-->

<!-- EN ESTE ARCHIVO SÓLO SE COLOCA LA INFORMACIÓN, CUERPO DEL CORREO. EL CONTROLADOR Y METODO RESPECTIVO SE ENCARGA
     DE UNIR LAS PARTES
 -->


       	  <!-- Texto -->
       	  <div>
                <h4 style ="text-align: center;">RECUPERACIÓN DE CONTRASEÑA</h4>
              <p style="text-align: justify;">

                Has solicitado que el sistema recuerde tu contraseña en nuestro sitio. <br>
                Se ha generado una clave temporal que se usará para que puedas cambiar tu contraseña. <br>
                Presione Click en el siguiente enlace :   #_ENLACE_RECUPERA_PASSWORD_#   para continuar con el proceso.
              </p>

       	  </div>

       </div>
  </body>



</html>

