<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>¡ FELICIDADES !</title>

    <!-- CSS de Bootstrap -->
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" >
				<style type="text/css">
								.flex-parent{
								  display: -ms-flex;
								  display: -webkit-flex;
								  display: flex;
								}

								.flex-child{
								  display: -ms-flex;
								  display: -webkit-flex;
								  display: flex;
								  justify-content: center;
								  flex-direction: column;
								}
				</style>
  </head>
<body>
	<!--imagen del producto -->
	<div class="cont-img-producto" style="width: 40%; float: left; display: block; margin: 0px; display: block;">
						<img src="http://www.entreamigosalcanzamos.com/tron/public/images/empresa/globos.gif" class="img-responsive img-logo" style="text-decoration: none;border: none;">
	</div>
	<br>
	<br>

<!--text-de la derecha -->
<div style="vertical-align: middle;">
				<h3> ¡ FELICIDADES ! </h3>
					<p>
									Recibe nuestras más sinceras felicitaciones en tu cumpleaños.<br>
									Esperamos que este sea un dia muy especial para ti.<br><br>
									Es el deseo de nuestra red de usuarios : <br>
								 <strong>TRON Entre amigos alcanzamos.</strong>

							  <h5> Y por ser un mes tan especial, te invitamos a visitar  <a href="http://www.entreamigosalcanzamos.com">nuestra tienda virtual</a>
										en donde hemos puesto todos nuestros
									productos en... 	<img src="http://www.entreamigosalcanzamos.com/tron/public/images/empresa/en_oferta.png" class="img-responsive img-logo" style="text-decoration: none;border: none;"></h5>
					</p>
</div>



    <!-- Librería jQuery requerida por los plugins de JavaScript -->
    <script src="http://code.jquery.com/jquery.js"></script>
			<!-- Latest compiled and minified JavaScript -->
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" ></script>
  </body>
</html>



