<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>¡ FELICIDADES !</title>

    <!-- CSS de Bootstrap -->
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" >
<style type="text/css">
				.flex-parent{
				  display: -ms-flex;
				  display: -webkit-flex;
				  display: flex;
				}

				.flex-child{
				  display: -ms-flex;
				  display: -webkit-flex;
				  display: flex;
				  justify-content: center;
				  flex-direction: column;
				}
</style>
  </head>
  <body>
					<div class="container-fluid">
						<div class=" well row flex-parent">
							<div class=" well col-md-8">
										<img style="float:left;" src="<?=BASE_IMG_EMPRESA ;?>globos.gif"  >

										<div class=" well col-md-4 text-justify flex-child ">
										Recibe nuestras más sinceras felicitaciones hoy en el día de tu cumpleaños, esperamos sea un día especial, son los deseo de TRON entreamigosalcanzamos.com
										</div>

						</div>
					</div>
</div>


    <!-- Librería jQuery requerida por los plugins de JavaScript -->
    <script src="http://code.jquery.com/jquery.js"></script>



<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" ></script>
  </body>
</html>



