<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>¡ FELICIDADES !</title>



  </head>
<body>

					<div style="width: 85%; margin: 0px auto; text-align: justify; display: block;font-family: arial;font-size: 14px; ">
		 				<div style ="text-align : center;">
							<img src="http://www.entreamigosalcanzamos.com/tron/public/images/empresa/logo.png" ><!--Logo tron -->
				</div>


						<div  style="display: block; margin:0 auto 20px; text-align: center; float: left; width: 40%;">
											<img src="http://www.entreamigosalcanzamos.com/tron/public/images/empresa/globos.gif" class="img-responsive img-logo"
											style="text-decoration: none;border: none; max-width: 100%;">
						</div>

						<!--text-de la derecha -->
						<div  style="vertical-align: middle; text-align: left; float: left; width: 60%;">
										<h3> ¡ FELICIDADES ! </h3>
										Este es un día especial para ti y queremos celebrarlo, no sólo hoy, sino todo un mes.<br><br>
										Ve a nuestra tienda virtual <a href="http://www.entreamigosalcanzamos.com">Entreamigosalcanzamos.com</a>
										revísala, luego inicia sesión y ¡Oh!... <br><br>
										<strong>¡¡¡ MAGIA !!! </strong><br>
										Estamos llenos de sorpresas para ti.
						</div>
						<br style="clear: both;">






