 <!--EL INICIO DEL BOY SE ENCUENTRA EN EL HEADER UBICADO EN application_sections/email/header.php :-->

<!-- EN ESTE ARCHIVO SÓLO SE COLOCA LA INFORMACIÓN, CUERPO DEL CORREO. EL CONTROLADOR Y METODO RESPECTIVO SE ENCARGA
     DE UNIR LAS PARTES
 -->
<div>

    <h3>¡ FELICITACIONES !</h3>
    <p style="text-align: justify;">
        Nos complace informarte que un nuevo empresario se ha unido a tu red TRON Entreamigos Alcanzamos. <br>
        Su nombre es: <strong> #_NOMBRE_NUEVO_USUARIO_# </strong>
    </p>


</div>

