

<div class="container">
  <div class="contenido">
     <div class=" row">
        <div class=" col-lg-12 col-md-12 col-sm-12 info"><!--INFORMACION MES, AÑO , CONSULTA -->
            <h3 class="text-center"><strong>Comisiones Pagadas</strong></h3>
 
                <div class="info-consultas">
                  <strong>MES : </strong>
                   <select name="meses" id="seleccion">
                   <?php foreach ($this->Periodos as $Periodo) : ;?>
                        <option value="1"><?= $Periodo['nom_periodo'] ?></option>

                    <?php endforeach ;?>
                      </select>

               <button type="button" class="btn btn-default btn-sm consultar">Consultar</button>
                </div>
 
              <br>
              <br>
<table class="table table-bordered table-hover  tabla_info_compras">
            <thead><!-- cabezera -->
                  <tr>
                    <th class="text-center">TP.ING.</th>
                    <th class="text-center">PEDIDO</th>
                    <th class="text-center">FACTURA</th>
                    <th class="text-center">COMPRADOR</th>
                    <th class="text-center">TP.COMP.</th>
                    <th class="text-center">NIV.</th>
                    <th class="text-center">PRODUCTOS</th>
                    <th class="text-center">IVA</th>
                    <th class="text-center">BASE COMIS.</th>
                    <th class="text-center">GRUPO</th>
                    <th class="text-center">% COMIS.</th>
                    <th class="text-center">VR.COMIS.</th>
                    <th class="text-center">NRO. COMIS.</th>

                  </tr>
            </thead><!-- cabezera -->
            <tbody>
              <?php foreach ($this->Comisiones as $Comision) : ;?>
                <?php 
                    $compra_productos = number_format ( $Comision['compra_productos'],0,',','.');
                ?>
                      <tr>
                        <td><?= $Comision['gana_como'] ;?></td>
                        <td><?= $Comision['numero_pedido'] ;?></td>
                        <td><?= $Comision['numero_factura'] ;?></td>
                        <td><?= $Comision['comprador'] ;?></td>
                        <td><?= $Comision['tipocomprador'] ;?></td>
                        <td><?= $Comision['nivel'] ;?></td>
                        <td class="text-rigth"><?= $compra_productos ;?></td>
                        <td><?= $Comision['vr_iva'] ;?></td>
                        <td><?= $Comision['base_comision'] ;?></td>
                        <td class="text-center"><?= $Comision['codigo_grupo'] ;?></td>
                        <td><?= $Comision['porcentaje'] ;?></td>
                        <td><?= $Comision['total_comision'] ;?></td>
                        <td><?= $Comision['textidcomision'] ;?></td>
                      </tr>

               <?php endforeach ;?>
            </tbody>
  </table>
        </div><!--FIN INFORMACION MES, AÑO , CONSULTA echo '<option value="'.$Anios['anio'].'">'.$Anios['anio'].'</option>';-->
     </div>





     </div>
     </div>


