

<div class="container">
  <div class="contenido">
     <div class=" row">
        <div class=" col-lg-12 col-md-12 col-sm-12 info"><!--INFORMACION MES, AÑO , CONSULTA -->
            <h3 class="text-center"><strong>Comisiones y Bonificaciones Pagadas</strong></h3>
              <form>
                <div class="info-consultas">
                   <h5 class="mes"><strong>MES : </strong></h5>

                   <select name="meses" id="seleccion">
                      <option value="">Seleccionar</option>
                      <option value="">Enero</option>
                      <option value="">Febrero</option>
                      <option value="">Marzo</option>
                      <option value="">Abril</option>
                      <option value="">Mayo</option>
                      <option value="">Junio</option>
                      <option value="">Julio</option>
                      <option value="">Agosto</option>
                      <option value="">Septiembre</option>
                      <option value="">Octubre</option>
                      <option value="">Noviembre</option>
                      <option value="">Diciembre</option>
                   </select>

                   <h5 class="anio"><strong>AÑO : </strong></h5>
                       <select name="año" id="tpp_dos">
                           <option>2014</option>
                           <option>2015</option>
                           <option>2016</option>
                       </select>
                      <button type="button" class="btn btn-default btn-sm consultar">Consultar</button>
                </div>
              </form>
        </div><!--FIN INFORMACION MES, AÑO , CONSULTA -->
     </div>

<!--INICIA-TBAS-->
	  <ul  class="nav nav-tabs">
	  	 <li class="active"><a href="#COMISIONES" data-toggle="tab">COMISIONES</a></li>
	  	 <li><a href="#BONIFICACIONES" data-toggle="tab">BONIFICACIONES</a></li>
	  </ul>

	  <div class="tab-content"><!--CONTENIDO DEL TABS -->
      <div class="tab-pane fade in active" id="COMISIONES"><!-- COMISIONES -->
       <br>
       <br>


<!--INICIO TABLA -->
            <div>
               <table class="table table-bordered">
                <thead>
                  <tr>
                     <td>#</td>
                     <td>Producto</td>
                     <td>Present.</td>
                     <td>Ventanas</td>
                     <td>Comisiones</td>
                     <td>%</td>
                  </tr>
                </thead>

                   <tbody></tbody>





               </table>
            </div>

<!--FIN TABLA -->


      </div><!--FIN-COMISIONES -->


      <div class="tab-pane fade" id="BONIFICACIONES"><!--BONIFICACIONES -->

      <br><br>
        <div class="table-responsive"></div>
      </div>
	 </div><!--FIN-CONT-TABS -->
<!--FINAL-TBAS-->
</div>

  </div>



