<div class="container">
       <div class="contenido">

      <div class="info-consultas text-center">
<h3 class="text-center"><strong><?=  $this->nom_mes ;?></strong></h3>
        <?php foreach ($this->Periodos as $Periodo) : ;?>
             <button data-idmes = <?= $Periodo['idmes'] ;?>
                     data-anio  = <?= $Periodo['anio'] ;?>
                     data-mes   = <?= $Periodo['nom_periodo'].'-' ;?>
                     type="button"
                     id="Btnperiodo"
                     class="btn btn-default btn-primary Btnperiodo">
                     <?= $Periodo['nom_periodo'] ?>
            </button>

        <?php endforeach ;?>
      </div>

<br>
<?php if ( !$this->Comisiones ) : ?>

      <h1 class ="text-center">NO SE HAN GENERADO COMISIONES PARA EL PERIODO CONSULTADO </h1>
    <?php else :?>

      <div class="bloqIn  >
        <div class="p30 table-responsive">
          <table class="table table-bordered table-hover  tabla_info_compras table-condensed">
            <thead><!-- cabezera -->
              <tr>
                <th class="text-center">
                      <a class="Mytooltip text-left" href="#" >ORIGEN
                        <span> La procedencia de las comisiones que ganas.  </span>
                      </a>
                </th>
                <th class="text-center">PEDIDO</th>
                <th class="text-center">FACTURA</th>
                <th class="text-center">COMPRADOR</th>
                <th class="text-center">TP.COMP.</th>
                <th class="text-center">NIV.</th>
                <th class="text-center">PRODUCTOS</th>
                <th class="text-center">IVA</th>
                <th class="text-center">BASE COMIS.</th>
                <th class="text-center">GRUPO</th>
                <th class="text-center">% COMIS.</th>
                <th class="text-center">VR.COMIS.</th>
                <th class="text-center">
                      <a class="Mytooltip text-left" href="#" >#MES
                        <span> Comisión preferencial por 6 meses consecutivos cada vez que incorpores un Empresario o un Cliente. </span>
                      </a>
                </th>

              </tr>
            </thead><!-- cabezera -->
            <tbody style ="font-size:11px;">
              <?php
                  $Total_Ganado     = 0 ;
                  $Total_Ganado_Red = 0;
                  $Total_Ganado_Cli = 0;
                  $Total_Ganado_Otr = 0;
              ?>
              <?php foreach ($this->Comisiones as $Comision) : ;?>
                <?php
                    $compra_productos     = number_format ( $Comision['compra_productos'],0,',','.');
                    $vr_iva               = number_format ( $Comision['vr_iva'],0,',','.');
                    $base_comision        = number_format ( $Comision['base_comision'],0,',','.');
                    $porcentaje           = number_format ( $Comision['porcentaje'] ,3,',','.').'%';
                    $total_comision       = number_format ( $Comision['total_comision'],0,',','.');
                    $Gana_Como            = trim( $Comision['gana_como']) ;
                    $periodo_sys          = $Comision['periodo_sys'];
                    $periodo_sql          = $Comision['periodo_sql']; // Periodo que consulta el usuario
                    $cumple_condiciones   = $Comision['cumple_condiciones'];
                    $nivel                = $Comision['nivel'] ;
                    if ( $nivel == '0'){
                        $nivel = '';
                    }
                    if ( $Gana_Como == 'RED') {
                      $Total_Ganado_Red = $Total_Ganado_Red + $Comision['total_comision'];
                    }
                    if ( $Gana_Como == 'CLIENTE') {
                      $Total_Ganado_Cli = $Total_Ganado_Cli + $Comision['total_comision'];
                    }
                    if ( $Gana_Como == 'CLI/EMP') {
                      $Total_Ganado_Otr = $Total_Ganado_Otr + $Comision['total_comision'];
                    }

                    $Total_Ganado         =  $Total_Ganado_Red + $Total_Ganado_Cli + $Total_Ganado_Otr;
                ?>
                <tr>
                  <td><?= $Comision['gana_como'] ;?></td>
                  <td><?= $Comision['numero_pedido'] ;?></td>
                  <td><?= $Comision['numero_factura'] ;?></td>
                  <td><?= $Comision['comprador'] ;?></td>
                  <td><?= $Comision['tipocomprador'] ;?></td>
                  <td class="text-center"><?= $nivel  ;?></td>
                  <td class="text-right"><?= $compra_productos ;?></td>
                  <td class="text-right"><?= $vr_iva ;?></td>
                  <td class="text-right"><?= $base_comision ;?></td>
                  <td class="text-center"><?= $Comision['codigo_grupo'] ;?></td>
                  <td class="text-right"><?= $porcentaje;?></td>
                  <td class="text-right"><?= $total_comision ;?></td>
                  <td class="text-right"><?= $Comision['textidcomision'] ;?></td>
                </tr>

              <?php endforeach ;?>
            </tbody>

          </table>
        </div>

       </div>

<br>
<br>
  <?php
     $Puntos           = $Total_Ganado * 30/100;
     $Comisiones       = $Total_Ganado - $Puntos;
     $Total_Ganado_Red = number_format ( $Total_Ganado_Red,0,',','.');
     $Total_Ganado_Cli = number_format ( $Total_Ganado_Cli,0,',','.');
     $Total_Ganado_Otr = number_format ( $Total_Ganado_Otr,0,',','.');
     $Total_Ganado     = number_format ( $Total_Ganado,0,',','.');
     $Puntos           = number_format ( $Puntos,0,',','.');
     $Comisiones       = number_format ( $Comisiones,0,',','.');
  ?>

    <div class="row">
        <div class="text-center bordes  colorBlue  t16 ff0 tU pLR40">DISTRIBUCIÓN COMISIONES </div>
        <div class=" col-sm-3  text-center borderIz  borderAbajo colorBlue  t14 ff0 tU pLR40">RED-Compras de mi Red</div>
        <div class=" col-sm-3 text-center borderIz  borderAbajo colorBlue  t14 ff0 tU pLR40">Ventas a mis Clientes</div>
        <div class=" col-sm-3 text-center borderIz  borderAbajo borderDerech colorBlue  t14 ff0 tU pLR40">CLI/EMP - Cliente de mis empr. </div>
        <div class=" col-sm-3 text-center   borderDerech colorBlue borderAbajo t14 ff0 tU pLR40">TOTAL </div>
</div>

    <div class="row">
        <div class=" col-sm-3  text-right  borderIz  borderAbajo colorBlue  t14 ff0 tU pLR40">
            <strong><?= $Total_Ganado_Red ;?></strong></div>
        <div class=" col-sm-3 text-right borderIz  borderAbajo  colorBlue  t14 ff0 tU pLR40">
            <strong><?= $Total_Ganado_Cli ;?></strong></div>
        <div class=" col-sm-3 text-right borderIz  borderAbajo borderDerech colorBlue  t14 ff0 tU pLR40">
            <strong><?= $Total_Ganado_Otr ;?></strong></div>
        <div class=" col-sm-3 text-right   borderAbajo borderDerech colorBlue  t14 ff0 tU pLR40">
            <strong><?= $Total_Ganado ;?></strong></div>
    </div>

    <!-- Si el periodo del sistema es igual al periodo de consulta se muestra cierta información...      -->
    <?php if ( $periodo_sys == $periodo_sql )  : ;?>

          <div class="row">
              <div class="col-md-9 text-right borderIz  borderAbajo  colorBlue t14 ff0 tU pLR40
                    <?php if ( $cumple_condiciones == FALSE ) echo 'fondo_rojo' ;?> ">comisiones de este mes a pagar : </div>
              <div class="col-sm-3 text-right borderIz  borderAbajo borderDerech colorBlue  t14 ff0 tU pLR40
                <?php if ( $cumple_condiciones == FALSE ) echo 'fondo_rojo' ;?> "">
              <strong> <?php if ( $cumple_condiciones == TRUE ) :?>>
                       <?= $Total_Ganado ;?>
                     <?php else :?>
                          0
                    <?php endif;?>

              </strong></div>

            <?php if ( $cumple_condiciones == FALSE )  :;?>
            <div class="col-sm-12 text-right ">
                Aún tienes tiempo para realizar tu compra mensual reglamentaria de mínimo <strong><?= Session::Get('valor_minimo_pedido_productos') ;?></strong> No pierdas tus comisiones.
            </div>

          <?php endif ;?>

          </div>
        <?php else :?>
          <div class="row">
              <div class="col-md-9 text-right borderIz  borderAbajo  colorBlue t14 ff0 tU pLR40"> Comisiones Pagadas : </div>

              <div class="col-sm-3 text-right borderIz  borderAbajo borderDerech colorBlue  t14 ff0 tU pLR40">
              <strong><?= $Total_Ganado ;?></strong></div>

              <div class="col-md-9 text-right borderIz  borderAbajo  colorBlue t14 ff0 tU pLR40"> Abono a la cuenta puntos (30%) : </div>
              <div class="col-sm-3 text-right borderIz  borderAbajo borderDerech colorBlue  t14 ff0 tU pLR40">
              <strong><?= $Puntos ;?></strong></div>

               <div class="col-md-9 text-right borderIz  borderAbajo  colorBlue t14 ff0 tU pLR40"> Abono a la cuenta dinero (70%) : </div>
              <div class="col-sm-3 text-right borderIz  borderAbajo borderDerech colorBlue  t14 ff0 tU pLR40">
              <strong><?= $Comisiones ;?></strong></div>
          </div>
    <?php endif ;?>




<br>
<br>
<br>
<br>
<br>
</div>

<?php endif;?>


