<div class="contenedor-datos-informe">

	<br /><br />

    <div class="col-sm-6 col-xs-12">
    
        <p class="Estado-cuenta"  style="color: #009900;">Estado de Mi Cuenta Dinero</p>
        <p class="saldos" style="color: #009900;"> <?= $this->Saldo_Comisiones ;?> </p>
        
      	<hr />
        

        <div class="cont-cabezera-tabla-dinero"><!-- Tabla-header = fija -->
            <p class="text-center dIB" style="width: 15%;">Fecha</p><!--
            --><p class="text-center dIB" style="width: 25%;">Concepto</p><!--
            --><p class="text-center dIB" style="width: 15%;"># Doc</p><!--
            --><p class="text-center dIB" style="width: 15%;">Entran</p><!--
            --><p class="text-center dIB" style="width: 15%;">Salen</p><!--
            --><p class="text-center dIB" style="width: 15%;">Saldo</p>
        </div><!-- Tabla-header = fija -->
        
        <table class="table table-bordered table-hover cuerpo-tabla" style="width: 100%;">
        <tbody><!-- Cuerpo -->
        <?php foreach ($this->Comisiones as $Comisiones)  :?>
			<?php
				$nom_tipo_registro = strtolower( $Comisiones['nom_tipo_registro']);
				$nom_tipo_registro = ucfirst( substr($nom_tipo_registro,0,55));
				$vr_entrada        = Numeric_Functions::Formato_Numero_SinSigno( $Comisiones['vr_entrada'] );
				$vr_salida         = Numeric_Functions::Formato_Numero_SinSigno( $Comisiones['vr_salida'] );
				$saldo             = Numeric_Functions::Formato_Numero_SinSigno( $Comisiones['saldo'] );
				$nro_documento     = $Comisiones['nro_documento']
            ?>
                <tr>
                    <td class="text-left   fecha"    style="width: 15%;"> <?= $Comisiones['fecha_registro'] ;?> </td>
                    <td class="text-left   concepto" style="width: 25%;"><?= $nom_tipo_registro ;?> </td>
                    <td class="text-left   concepto" style="width: 15%;"><?= $nro_documento ;?> </td>
                    <td class="text-right  entran"   style="width: 15%;"><?= $vr_entrada ;?>   </td>
                    <td class="text-right  salen"    style="width: 15%"><?= $vr_salida  ;?>   </td>
                    <td class="text-right  saldo"    style="width: 15%;"> <?= $saldo ;?>  </td>
                </tr>
            <?php endforeach ;?>        
        </tbody><!-- Cuerpo -->
        </table>
        
	</div><!-- Mi cuenta_dinero -->


   <!-- Mi cuenta_Puntos -->
    <div class="col-sm-6 col-xs-12">
    
        <p class="Estado-cuenta" style="color: #ff6600;" >Estado de Mi Cuenta Puntos</p>
        <p class="saldos" style="color: #ff6600;"><?= $this->Saldo_Puntos ;?> </p>
        
        <hr />

        <div class="cont-cabezera-tabla-puntos"><!-- Tabla-header = fija -->
            <p class="text-center dIB" style="width: 15%;">Fecha</p><!--
            --><p class="text-center dIB" style="width: 25%;">Concepto</p><!--
            --><p class="text-center dIB" style="width: 15%;"># Doc</p><!--
            --><p class="text-center dIB" style="width: 15%;">Entran</p><!--
            --><p class="text-center dIB" style="width: 15%;">Salen</p><!--
            --><p class="text-center dIB" style="width: 15%;">Saldo</p>
        </div><!-- Tabla-header = fija -->

              <table class="table table-bordered table-hover cuerpo-tabla" >
                <tbody ><!-- Cuerpo -->
                <?php foreach ($this->Puntos as $Puntos)  :?>
                <?php
                      $nom_tipo_registro = strtolower( $Puntos['nom_tipo_registro']);
                      $cant_entrada      = Numeric_Functions::Formato_Numero( $Puntos['cant_entrada'] );
                      $cant_salida       = Numeric_Functions::Formato_Numero($Puntos['cant_salida'] );
                      $saldo             = Numeric_Functions::Formato_Numero( $Puntos['saldo'] );
                      $nro_documento     = $Puntos['nro_documento'];
                ?>
                 <tr style="padding: 0px;">
                     <td class="text-left   fecha"    style="width: 15%;"> <?= $Puntos['fecha_registro_1'] ;?> </td>
                     <td class="text-left   concepto" style="width: 25%;"> <?= $nom_tipo_registro;?> </td>
                     <td class="text-left   concepto" style="width: 15%;"> <?= $nro_documento;?> </td>
                     <td class="text-right  entran"   style="width: 15%;"><?= $cant_entrada;?>   </td>
                     <td class="text-right  salen"    style="width: 15%">  <?= $cant_salida ;?>   </td>
                     <td class="text-right  saldo"    style="width: 15%;"> <?= $saldo;?>   </td>
                 </tr>


               <?php endforeach ;?>
                </tbody><!-- Cuerpo -->
              </table>
         </div><!-- Tabla-Cuenta-puntos -->
         
	</div>
    
</div>


