

<div class="container">
  <div class="contenido">
     <div class=" row">
        <div class=" col-lg-12 col-md-12 col-sm-12 info"><!--INFORMACION MES, AÑO , CONSULTA -->
            <h3 class="text-center"><strong>Comisiones Pagadas</strong></h3>

                <div class="info-consultas text-center">
                  <strong>PERIODO DE CONSULTA : </strong>
                   <select name="meses" id="seleccion">
                   <?php foreach ($this->Periodos as $Periodo) : ;?>
                        <option value="1"><?= $Periodo['nom_periodo'] ?></option>

                    <?php endforeach ;?>
                      </select>

              <!-- <button type="button" class="btn btn-default btn-sm consultar">Consultar</button> -->
                </div>

              <br>
              <br>
<table class="table table-bordered table-hover  tabla_info_compras table-condensed">
            <thead><!-- cabezera -->
                  <tr>
                    <th class="text-center">TP.ING.</th>
                    <th class="text-center">PEDIDO</th>
                    <th class="text-center">FACTURA</th>
                    <th class="text-center">COMPRADOR</th>
                    <th class="text-center">TP.COMP.</th>
                    <th class="text-center">NIV.</th>
                    <th class="text-center">PRODUCTOS</th>
                    <th class="text-center">IVA</th>
                    <th class="text-center">BASE COMIS.</th>
                    <th class="text-center">GRUPO</th>
                    <th class="text-center">% COMIS.</th>
                    <th class="text-center">VR.COMIS.</th>
                    <th class="text-center">NRO. COMIS.</th>

                  </tr>
            </thead><!-- cabezera -->
            <tbody>
              <?php $Total_Ganado = 0 ;?>
              <?php foreach ($this->Comisiones as $Comision) : ;?>
                <?php
                    $compra_productos     = number_format ( $Comision['compra_productos'],0,',','.');
                    $vr_iva               = number_format ( $Comision['vr_iva'],0,',','.');
                    $base_comision        = number_format ( $Comision['base_comision'],0,',','.');
                    $porcentaje           = number_format ( $Comision['porcentaje'] * 4 ,3,',','.').'%';
                    $total_comision       = number_format ( $Comision['total_comision'],0,',','.');
                    $Total_Ganado         = $Total_Ganado + $Comision['total_comision'];
                ?>
                      <tr>
                        <td><?= $Comision['gana_como'] ;?></td>
                        <td><?= $Comision['numero_pedido'] ;?></td>
                        <td><?= $Comision['numero_factura'] ;?></td>
                        <td><?= $Comision['comprador'] ;?></td>
                        <td><?= $Comision['tipocomprador'] ;?></td>
                        <td class="text-center"><?= $Comision['nivel'] ;?></td>
                        <td class="text-right"><?= $compra_productos ;?></td>
                        <td class="text-right"><?= $vr_iva ;?></td>
                        <td class="text-right"><?= $base_comision ;?></td>
                        <td class="text-center"><?= $Comision['codigo_grupo'] ;?></td>
                        <td class="text-right"><?= $porcentaje;?></td>
                        <td class="text-right"><?= $total_comision ;?></td>
                        <td class="text-right"><?= $Comision['textidcomision'] ;?></td>
                      </tr>

               <?php endforeach ;?>
            </tbody>
                              <tr>
                    <th class="text-center"></th>
                    <th class="text-center"></th>
                    <th class="text-center"></th>
                    <th class="text-center"></th>
                    <th class="text-center"></th>
                    <th class="text-center"></th>
                    <th class="text-center"></th>
                    <th class="text-center"></th>
                    <th class="text-center"></th>
                    <th class="text-center"></th>
                    <th class="text-center"></th>
                    <th class="text-center"><?= number_format ( $Total_Ganado ,0,',','.'); ?></th>
                    <th class="text-center"></th>

                  </tr>
  </table>
  
  <br><br>
        </div><!--FIN INFORMACION MES, AÑO , CONSULTA echo '<option value="'.$Anios['anio'].'">'.$Anios['anio'].'</option>';-->
     </div>





     </div>
     </div>


