<div class="container">
       <div class="contenido">
      <h3 class="text-center"><strong>COMISIONES</strong></h3>
      <div class="info-consultas text-center">

        <?php foreach ($this->Periodos as $Periodo) : ;?>
             <button data-idmes = <?= $Periodo['idmes'] ;?>
                     data-anio  = <?= $Periodo['anio'] ;?>
                     data-mes   = <?= $Periodo['nom_periodo'].'-' ;?>
                     type="button"
                     id="Btnperiodo"
                     class="btn btn-default btn-primary Btnperiodo">
                     <?= $Periodo['nom_periodo'] ?>
            </button>

        <?php endforeach ;?>
      </div>

<br>
<strong><?=  $this->nom_mes ;?></strong>
      <div class="bloqIn  >
        <div class="p30 table-responsive">
          <table class="table table-bordered table-hover  tabla_info_compras table-condensed">
            <thead><!-- cabezera -->
              <tr>
                <th class="text-center">
                      <a class="Mytooltip text-left" href="#" >ORIGEN
                        <span>
                            La procedencia de las comisiones que ganas.
                          </span>
                      </a>
                </th>
                <th class="text-center">PEDIDO</th>
                <th class="text-center">FACTURA</th>
                <th class="text-center">COMPRADOR</th>
                <th class="text-center">TP.COMP.</th>
                <th class="text-center">NIV.</th>
                <th class="text-center">PRODUCTOS</th>
                <th class="text-center">IVA</th>
                <th class="text-center">BASE COMIS.</th>
                <th class="text-center">GRUPO</th>
                <th class="text-center">% COMIS.</th>
                <th class="text-center">VR.COMIS.</th>
                <th class="text-center">
                      <a class="Mytooltip text-left" href="#" >#MES
                        <span>
                            Comisión preferencial por 6 meses después de tu inscripción.
                          </span>
                      </a>
                </th>

              </tr>
            </thead><!-- cabezera -->
            <tbody>
              <?php
                  $Total_Ganado     = 0 ;
                  $Total_Ganado_Red = 0;
                  $Total_Ganado_Cli = 0;
                  $Total_Ganado_Otr = 0;
              ?>
              <?php foreach ($this->Comisiones as $Comision) : ;?>
                <?php
                $compra_productos     = number_format ( $Comision['compra_productos'],0,',','.');
                $vr_iva               = number_format ( $Comision['vr_iva'],0,',','.');
                $base_comision        = number_format ( $Comision['base_comision'],0,',','.');
                $porcentaje           = number_format ( $Comision['porcentaje'] ,3,',','.').'%';
                $total_comision       = number_format ( $Comision['total_comision'],0,',','.');
                $Gana_Como            = trim( $Comision['gana_como']) ;
                $periodo_sys          = $Comision['periodo_sys'];
                $periodo_sql          = $Comision['periodo_sql']; // Periodo que consulta el usuario
                $cumple_condiciones   = $Comision['cumple_condiciones'];
                $nivel                = $Comision['nivel'] ;
                if ( $nivel == '0'){
                    $nivel = '';
                }
                if ( $Gana_Como == 'RED') {
                  $Total_Ganado_Red = $Total_Ganado_Red + $Comision['total_comision'];
                }
                if ( $Gana_Como == 'CLIENTE') {
                  $Total_Ganado_Cli = $Total_Ganado_Cli + $Comision['total_comision'];
                }
                if ( $Gana_Como == 'CLI/EMP') {
                  $Total_Ganado_Otr = $Total_Ganado_Otr + $Comision['total_comision'];
                }

                $Total_Ganado         =  $Total_Ganado_Red + $Total_Ganado_Cli + $Total_Ganado_Otr;
                ?>
                <tr>
                  <td><?= $Comision['gana_como'] ;?></td>
                  <td><?= $Comision['numero_pedido'] ;?></td>
                  <td><?= $Comision['numero_factura'] ;?></td>
                  <td><?= $Comision['comprador'] ;?></td>
                  <td><?= $Comision['tipocomprador'] ;?></td>
                  <td class="text-center"><?= $nivel  ;?></td>
                  <td class="text-right"><?= $compra_productos ;?></td>
                  <td class="text-right"><?= $vr_iva ;?></td>
                  <td class="text-right"><?= $base_comision ;?></td>
                  <td class="text-center"><?= $Comision['codigo_grupo'] ;?></td>
                  <td class="text-right"><?= $porcentaje;?></td>
                  <td class="text-right"><?= $total_comision ;?></td>
                  <td class="text-right"><?= $Comision['textidcomision'] ;?></td>
                </tr>

              <?php endforeach ;?>
            </tbody>

          </table>
        </div>

       </div>

<br>
<br>
  <?php
     $Puntos           = $Total_Ganado * 30/100;
     $Comisiones       = $Total_Ganado - $Puntos;
     $Total_Ganado_Red = number_format ( $Total_Ganado_Red,0,',','.');
     $Total_Ganado_Cli = number_format ( $Total_Ganado_Cli,0,',','.');
     $Total_Ganado_Otr = number_format ( $Total_Ganado_Otr,0,',','.');
     $Total_Ganado     = number_format ( $Total_Ganado,0,',','.');
     $Puntos           = number_format ( $Puntos,0,',','.');
     $Comisiones       = number_format ( $Comisiones,0,',','.');
  ?>

    <div class="row">
        <div class="text-center bordes  colorBlue  t20 ff0 tU pLR40">COMISIONES TOTALES</div>
        <div class=" col-sm-4  text-center borderIz  borderAbajo colorBlue  t18 ff0 tU pLR40">GENERADAS POR LA RED</div>
        <div class=" col-sm-4 text-center borderIz  borderAbajo colorBlue  t18 ff0 tU pLR40">VENTAS A CLIENTES</div>
        <a href="" class="Mytooltip">
        <div class=" col-sm-4 text-center borderIz  borderAbajo borderDerech colorBlue  t18 ff0 tU pLR40">OTROS CLIENTES (CLI/EMPR)
        <span> CLIENTES DE MIS EMPRESARIOS </span>
        </a>
        </div>
    </div>

    <div class="row">
        <div class=" col-sm-4  text-right  borderIz  borderAbajo colorBlue  t18 ff0 tU pLR40">
            <strong><?= $Total_Ganado_Red ;?></strong></div>
        <div class=" col-sm-4 text-right borderIz  borderAbajo  colorBlue  t18 ff0 tU pLR40">
            <strong><?= $Total_Ganado_Cli ;?></strong></div>
        <div class=" col-sm-4 text-right borderIz  borderAbajo borderDerech colorBlue  t18 ff0 tU pLR40">
            <strong><?= $Total_Ganado_Otr ;?></strong></div>
    </div>
    <!-- Si el periodo del sistema es igual al periodo de consulta se muestra cierta información...      -->
    <?php if ( $periodo_sys == $periodo_sql )  : ;?>
          <div class="row">
              <div class="col-md-8 text-right borderIz  borderAbajo  colorBlue t18 ff0 tU pLR40
                    <?php if ( $cumple_condiciones == FALSE ) echo 'fondo_rojo' ;?> "> VALOR POR PAGAR : </div>
              <div class="col-sm-4 text-right borderIz  borderAbajo borderDerech colorBlue  t18 ff0 tU pLR40
                <?php if ( $cumple_condiciones == FALSE ) echo 'fondo_rojo' ;?> "">
              <strong><?= $Total_Ganado ;?></strong></div>
            <?php if ( $cumple_condiciones == FALSE )  :;?>
            <div class="col-sm-12 text-right ">
                Dado que no has cumplido con la compra mínima reglamentaria, estas comisiones no serán pagadas.
            </div>
          <?php endif ;?>

          </div>

      <?php else :?>
            <div class="row">
              <div class="col-md-8 text-right borderIz  borderAbajo  colorBlue t18 ff0 tU pLR40"> VALOR PAGADO EN PUNTOS : </div>

              <div class="col-sm-4 text-right borderIz  borderAbajo borderDerech colorBlue  t18 ff0 tU pLR40">
              <strong><?= $Puntos ;?></strong></div>

              <div class="col-md-8 text-right borderIz  borderAbajo  colorBlue t18 ff0 tU pLR40"> VALOR PAGADO EN COMISIONES : </div>
              <div class="col-sm-4 text-right borderIz  borderAbajo borderDerech colorBlue  t18 ff0 tU pLR40">
              <strong><?= $Comisiones ;?></strong></div>

               <div class="col-md-8 text-right borderIz  borderAbajo  colorBlue t18 ff0 tU pLR40"> TOTAL GANADO : </div>
              <div class="col-sm-4 text-right borderIz  borderAbajo borderDerech colorBlue  t18 ff0 tU pLR40">
              <strong><?= $Total_Ganado ;?></strong></div>
          </div>

    <?php endif ;?>




<br>
<br>
<br>
<br>
<br>
</div>




