<div>
	  <div class="col-lg-12">
	  	   <table class="table table-bordered table-hover  tabla_info_compras">
	     	    <thead><!-- cabezera -->
	     	    	    <tr>
                    <th class="text-center">Nombre</th>
                    <th class="text-center">Ene.</th>
                    <th class="text-center">Feb.</th>
                    <th class="text-center">Mar.</th>
                    <th class="text-center">Abr.</th>
                    <th class="text-center">May.</th>
                    <th class="text-center">Jun.</th>
                    <th class="text-center">Jul.</th>
                    <th class="text-center">Ago.</th>
                    <th class="text-center">Sept.</th>
                    <th class="text-center">Oct.</th>
                    <th class="text-center">Nov.</th>
                    <th class="text-center">Dic.</th>
                    <th class="text-center">Total</th>
                    <th class="text-center">Prom.</th>
	     	    	    </tr>
	     	    </thead><!-- cabezera -->

	     	    <tbody>
               <tr>
               	   <td style="width: 300px;">ADRIANA CHIQUITO</td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               	   <td><a href="#">35.082</a></td>
               </tr>
	     	    </tbody>
	  	   </table>
	  </div>
</div>

<style>
	.tabla_info_compras
	{
		  font-size: 12px;
	}
</style>
