

<div class ='contenido-reporte'>
	  <div class="col-lg-12">

	  	   <table class="table table-bordered table-hover  tabla_info_compras">
	     	    <thead><!-- cabezera -->
	     	    	    <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Nombre</th>
                    <th class="text-center">Ene.</th>
                    <th class="text-center">Feb.</th>
                    <th class="text-center">Mar.</th>
                    <th class="text-center">Abr.</th>
                    <th class="text-center">May.</th>
                    <th class="text-center">Jun.</th>
                    <th class="text-center">Jul.</th>
                    <th class="text-center">Ago.</th>
                    <th class="text-center">Sept.</th>
                    <th class="text-center">Oct.</th>
                    <th class="text-center">Nov.</th>
                    <th class="text-center">Dic.</th>
                    <th class="text-center">Total</th>
                    <th class="text-center">Prom.</th>
	     	    	    </tr>
	     	    </thead><!-- cabezera -->

	     	    <tbody>
                   <?php $I =0 ;?>
                   <?php foreach ($this->Datos_Compras  as $Compras)  :?>
                    <?php
                         $nombre   =  $Compras['nombre'];
                         $ene      = Numeric_Functions::Formato_Numero_SinSigno($Compras['ene']);
                         $feb      = Numeric_Functions::Formato_Numero_SinSigno($Compras['feb']);
                         $mar      = Numeric_Functions::Formato_Numero_SinSigno($Compras['mar']);
                         $abr      = Numeric_Functions::Formato_Numero_SinSigno($Compras['abr']);
                         $may      = Numeric_Functions::Formato_Numero_SinSigno($Compras['may']);
                         $jun      = Numeric_Functions::Formato_Numero_SinSigno($Compras['jun']);
                         $jul      = Numeric_Functions::Formato_Numero_SinSigno($Compras['jul']);
                         $ago      = Numeric_Functions::Formato_Numero_SinSigno($Compras['ago']);
                         $sep      = Numeric_Functions::Formato_Numero_SinSigno($Compras['sep']);
                         $oct      = Numeric_Functions::Formato_Numero_SinSigno($Compras['oct']);
                         $nov      = Numeric_Functions::Formato_Numero_SinSigno($Compras['nov']);
                         $dic      = Numeric_Functions::Formato_Numero_SinSigno($Compras['dic']);
                         $total    = Numeric_Functions::Formato_Numero_SinSigno($Compras['total']);
                         $promedio = Numeric_Functions::Formato_Numero_SinSigno($Compras['promedio']);
                         if ( $ene == 0) { $ene = '';}
                         if ( $feb == 0) { $feb = '';}
                         if ( $mar == 0) { $mar = '';}
                         if ( $abr == 0) { $abr = '';}
                         if ( $may == 0) { $may = '';}
                         if ( $jun == 0) { $jun = '';}
                         if ( $jul == 0) { $jul = '';}
                         if ( $ago == 0) { $ago = '';}
                         if ( $sep == 0) { $sep = '';}
                         if ( $oct == 0) { $oct = '';}
                         if ( $nov == 0) { $nov = '';}
                         if ( $dic == 0) { $dic = '';}
                         if ( $total == 0) { $total = '';}
                         if ( $promedio == 0) { $promedio = '';}

                         $I++;
                    ?>
                         <tr>
                         	   <td><a href="#"> <?= $I ;?> </a></td>
                                 <td style="width: 300px;"> <?= $nombre ;?></td>
                         	   <td><a href="#"> <?= $ene ;?> </a></td>
                         	   <td><a href="#"><?= $feb ;?> </a></td>
                         	   <td><a href="#"><?= $mar ;?> </a></td>
                         	   <td><a href="#"><?= $abr ;?> </a></td>
                         	   <td><a href="#"><?= $may ;?> </a></td>
                         	   <td><a href="#"><?= $jun ;?> </a></td>
                         	   <td><a href="#"><?= $jul ;?> </a></td>
                         	   <td><a href="#"><?= $ago ;?> </a></td>
                         	   <td><a href="#"><?= $sep ;?> </a></td>
                         	   <td><a href="#"><?= $oct ;?> </a></td>
                         	   <td><a href="#"><?= $nov ;?> </a></td>
                         	   <td><a href="#"><?= $dic ;?> </a></td>
                         	   <td><a href="#"><?= $total ;?> </a></td>
                         	   <td><a href="#"><?= $promedio ;?> </a></td>
                         </tr>

                        <?php endforeach ;?>
	     	    </tbody>
	  	   </table>
	  </div>
</div>

<style>
	.tabla_info_compras
	{
		  font-size: 12px;
	}
</style>
