<!--
     JS          => Carpeta JS  =>
     Estilos CSS => Carpeta CSS => cuenta_informe_mi_red.css
             ************ Mi Red ************
 -->

<div><!-- Contenedor-Principal -->
	   <div class="row">



						<!-- /// Ventana-modal ( 1 ) = Informacion del Usuario/// -->
						<?php include (APPLICATION_SECTIONS .'cuenta_mi-red_info_usuario.php');?>
						<!-- /// Barra = Infromacion /// -->
						<!-- /// Barra Usuario /// -->
						<?php include (APPLICATION_SECTIONS . 'barra_usuraios.php');?>

      <!-- /// Secion = Amigos-Inactivos /// -->
            <div class="col-lg-12">
            	   <div><!-- Contenedor -->

																						<div class ="col-lg-2"><!-- amigos-compraron-marzo -->
                           <div class="cont-info-amigos-inactivos"><!-- Contenedor -->
                           	   <p class="numero_marzo">0</p>
                           	   <p class="text-amigo_marzo">Amigos ya compraron en Marzo</p>
                           </div><!-- Contenedor -->
																						</div><!-- amigos-compraron-marzo -->

																						<div class ="col-lg-2" style="width: 220px;"><!-- amigos-( 1 )-mes -->
                           <div class="cont-info-amigos-inactivos"><!-- contenedor -->
                           	    <p class="numero-2-mes">0</p>
                           	    <p class="text-amigo-2-mes">Amigos cumplirán un  (1) mes de inactividad</p>
                           </div><!-- contenedor -->
																						</div><!-- amigos-( 1 )-mes -->

																						<div class ="col-lg-2"><!-- amigos-( 2 )-mes -->
                           <div class="cont-info-amigos-inactivos"><!-- contenedor -->
                           	    <p>0</p>
                           	    <p>	Amigos cumplirán dos (2) meses de inactividad</p>
                           </div><!-- contenedor -->
																						</div><!-- amigos-( 2 )-mes -->

																						<div class ="col-lg-2"><!-- amigos-( 3 )-mes -->
                           <div class="cont-info-amigos-inactivos"><!-- contenedor -->
                           	    <p>0</p>
                           	    <p>Amigos cumplirán tres (3) meses de inactividad</p>
                           </div><!-- contenedor -->
																						</div><!-- amigos-( 3 )-mes -->

																						<div class ="col-lg-2"><!-- Total amigos -->
                           <div class="cont-info-amigos-inactivos"><!-- contenedor -->
                           	    <p>0</p>
                           	    <p>Total Amigos</p>
                           </div><!-- contenedor -->
																						</div><!-- Total amigos -->

            	   </div><!-- Contenedor -->
            </div>
      <!-- /// Secion = Amigos-Inactivos /// -->

       <!-- /// Tabla = Niveles /// -->
           <div class="col-lg-12">
           	    <div><!-- Contenedor -->
           	    	    <table class="table table-bordered table-hover">
           	    	    	     <thead><!-- Cabezera -->
           	    	    	     	     <tr>
           	    	    	     	     	   <th class="text-center">Nivel 1</th>
           	    	    	     	     	   <th class="text-center">Nivel 2</th>
           	    	    	     	     	   <th class="text-center">Nivel 3</th>
           	    	    	     	     	   <th class="text-center">Nivel 4</th>
           	    	    	     	     	   <th class="text-center">Nivel 5</th>
           	    	    	     	     	   <th class="text-center">Nivel 6</th>
           	    	    	     	     </tr>
           	    	    	     </thead><!-- Cabezera -->

           	    	    	     <tbody><!-- Cuerpo -->

           	    	    	     	     <tr>
                                     <td class="text-center">0 Amigos</td>
                                     <td class="text-center">0 Amigos</td>
                                     <td class="text-center">0 Amigos</td>
                                     <td class="text-center">0 Amigos</td>
                                     <td class="text-center">0 Amigos</td>
                                     <td class="text-center">0 Amigos</td>
           	    	    	     	     </tr>

           	    	    	     	     <tr>
           	    	    	     	     	   <td ><!--  Ventana-modal ( 1 ) -->
           	    	    	     	     	      <a href="#info_usuario"  data-toggle="modal" data-target="#info_usuario"><strong>JHON JAMES</strong></a><br>
           	    	    	     	     	      <small>Este Usuario sera Eliminado</small>
           	    	    	     	     	   </td>
           	    	    	     	     	   <td class="text-center"></td>
           	    	    	     	     	   <td class="text-center"></td>
           	    	    	     	     	   <td class="text-center"></td>
           	    	    	     	     	   <td class="text-center"></td>
           	    	    	     	     	   <td class="text-center"></td>
           	    	    	     	     </tr>
           	    	    	     </tbody><!-- Cuerpo -->
           	    	    </table>
           	    </div><!-- Contenedor -->
           </div>
       <!-- /// Tabla = Niveles /// -->

	   </div>
</div><!-- Contenedor-Principal -->
<br>
<br>
<br>
