

<div class="participacion-red">
  <table class="table table-bordered table-hover">

    <thead><!-- cabezera -->
      <tr>
       <th class="text-center">#</th>
       <th class="text-center">Código de Usuario</th>
       <th class="text-center">Nombre</th>
       <th class="text-center">Presentado por</th>
       <th class="text-center">Fecha Reg.</th>
       <th class="text-center">Cant. Frontales</th>
       <th class="text-center">Cant .Codigo por Persona</th>
     </tr>
   </thead><!-- cabezera -->
   <tbody>
    <?php $I= 1 ;?>
    <?php foreach ($this->Terceros as $Tercero)  :?>
      <?php

      $codigousuario                 = $Tercero['codigousuario'];
      $nombre                        = $Tercero['nombre'];
      $codigoterceropresenta_inicial = $Tercero['codigoterceropresenta_inicial'];
      $fecha_registro                = $Tercero['fecha_registro_formato'];
      $amigos_nivel_1                = $Tercero['amigos_nivel_1'];
      $cantidad_codigos              = $Tercero['cantidad_codigos'];

      ?>
      <tr>
       <td class="text-center"><?= $I;?> </td>
       <td class="text-center"><?= $codigousuario;?> </td>
       <td class="text-center"><?= $nombre;?> </td>
       <td class="text-center"><?= $codigoterceropresenta_inicial;?> </td>
       <td class="text-center"><?= $fecha_registro;?> </td>
       <td class="text-center"><?= $amigos_nivel_1;?> </td>
       <td class="text-center"><?= $cantidad_codigos;?> </td>
     </tr>
     <?php $I++ ;?>
   <?php endforeach ;?>
 </tbody>


</table>
<?php if ( $this->Cantidad_Registros == 0 ) :?>
 <h3 class="text-center"> No existen registros para el usuario seleccionado. </h3>
<?php endif ;?>
</div>


