<!--
    js          => Carpeta Js  =>
    Estilos CSS => Carpeta CSS => tron_cuenta_info_partici_la_red.css
          ************ Participacion de la red ************
-->
<div class="contenedor"><!-- contenedor de la pagina -->
	  <div class="row">

         <!-- /// Titulo /// -->
             <div class="col-lg-12 col-md-12 col-sm-12">
             	   <div>
             	   	   <h2 style="color: #003e90; margin-top: -10px;"><strong>Informes</strong></h2>
             	   </div>
             </div>
         <!-- /// Titulo /// -->


      <!-- /// Barra Usuario /// -->
      <?php include (APPLICATION_SECTIONS . 'barra_usuraios.php');?>
       <?php include (APPLICATION_SECTIONS . 'anios_disponibles_consultas.php');?>

      Participacion en la Red
       <!-- /// Tabla = Participación de mis amigos  /// -->
           <div class="col-lg-12 col-md-12 col-sm-12">
           	   <div><!-- Contenedor -->
           	   	     <table class="table table-bordered table-hover">

           	   	     	    <thead><!-- cabezera -->
           	   	     	    	    <tr>
           	   	     	    	    	   <th class="text-center">#</th>
           	   	     	    	    	   <th class="text-center">Código de Usuario</th>
           	   	     	    	    	   <th class="text-center">Nombre</th>
           	   	     	    	    	   <th class="text-center">Presentado por</th>
           	   	     	    	    	   <th class="text-center">Fecha Reg.</th>
           	   	     	    	    	   <th class="text-center">Cant. Frontales</th>
           	   	     	    	    	   <th class="text-center">Cant .Codigo por Persona</th>
           	   	     	    	    </tr>
           	   	     	    </thead><!-- cabezera -->
                      <div class="participacion-red">
           	   	     	    <tbody>
                            <?php $I= 1 ;?>
                            <?php foreach ($this->Terceros as $Tercero)  :?>
                              <?php

                                  $codigousuario                 = $Tercero['codigousuario'];
                                  $nombre                        = $Tercero['nombre'];
                                  $codigoterceropresenta_inicial = $Tercero['codigoterceropresenta_inicial'];
                                  $fecha_registro                = $Tercero['fecha_registro_formato'];
                                  $amigos_nivel_1                = $Tercero['amigos_nivel_1'];
                                  $cantidad_codigos              = $Tercero['cantidad_codigos'];

                              ?>
             	   	     	    	     <tr>
             	   	     	    	     	   <td class="text-center"><?= $I;?> </td>
             	   	     	    	     	   <td class="text-center"><?= $codigousuario;?> </td>
             	   	     	    	     	   <td class="text-center"><?= $nombre;?> </td>
             	   	     	    	     	   <td class="text-center"><?= $codigoterceropresenta_inicial;?> </td>
             	   	     	    	     	   <td class="text-center"><?= $fecha_registro;?> </td>
             	   	     	    	     	   <td class="text-center"><?= $amigos_nivel_1;?> </td>
             	   	     	    	     	   <td class="text-center"><?= $cantidad_codigos;?> </td>
             	   	     	    	     </tr>
                                <?php $I++ ;?>
                            <?php endforeach ;?>
           	   	     	    </tbody>
                  </div>

           	   	     </table>
           	   </div><!-- Contenedor -->
           </div>
       <!-- /// Tabla = Participación de mis amigos  /// -->

	  </div>
</div><!-- contenedor de la pagina -->
<br>
<br>
<br>
