<!--
    js          => Carpeta Js  =>
    Estilos CSS => Carpeta CSS => tron_cuenta_info_partici_la_red.css
          ************ Participacion de la red ************
-->
<div class="contenedor"><!-- contenedor de la pagina -->
	  <div class="row">


      <!-- /// Barra Usuario /// -->
      <?php include (APPLICATION_SECTIONS . 'barra_usuraios_anios.php');?>



       <!-- /// Tabla = Participación de mis amigos  /// -->
           <div class="col-lg-12 col-md-12 col-sm-12">
           	   <div><!-- Contenedor -->
           	   	    <div class="participacion-red">
                      <!-- Tabla -->
                        <?php include (APPLICATION_SECTIONS . 'tabla_participacion_la_red.php');?>
                     </div>
           	   </div><!-- Contenedor -->
           </div>
       <!-- /// Tabla = Participación de mis amigos  /// -->

	  </div>
</div><!-- contenedor de la pagina -->
<br>
<br>
<br>

<!--  -->
