<div class="contenedor"><!--Contenedor-De-La-Pagina-->
<div class="row"><!--Fila-->

    <div class="col-lg-12  col-md-12  col-sm-12"><!--Campos De La Pagina RED DE AMIGOS TRON-->
       <p><a href="#"></a></p>
       <p><a href="#"></a></p>
    </div><!--Campos De La Pagina RED DE AMIGOS TRON-->

    <div class="col-lg-9  col-md-9  col-sm-9"><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->
       <div class="row"><!--Titulo-->
       	   <div class="col-lg-12 col-md-12 col-sm-12">
       	   	  <h1 class="titulo-principal">Comisiones</h1> <br>
       	   </div>
       </div><!--Titulo-->


    <div class="col-lg-3 col-md-3 col-sm-3 contenido-indice"><!--Idice-->
       <h5><strong>INDICE</strong></h5><!--Titulo-->

        <nav class="indice">
           <ul class="list-unstyled">
              <li><a href="#">Introducion</a></li>
              <li><a href="#">Informacion general</a></li>
              <li><a href="#">Porcentajes de Comisiones</a></li>
              <li><a href="#">Puntos</a></li>
              <li><a href="#">Medios de Cobro</a></li>
           </ul>
        </nav>
    </div><!--Idice-->

    <div class="col-lg-9 col-md-9 col-sm-9"><!--Informacion-Contendo-Introduccion -->
    	 <div>  <p class="contenido-titulo-Introduccion">Introduccion</p> </div> <br><!--Titulo -->
       <p class="text-introduccion">Las comisiones es uno de los pilares del plan de compensación para los usuarios registrados en el Plan Empresario TRON.
       </p>
    </div><!--Informacion-Contendo-Introduccion -->

<!--///////////////////////////////////////////////////-Información General-//////////////////////////////////////////////////////////////-->

    <div class="well col-lg-12 col-md-12 col-sm-12"><!--Información General-->
       <div> <p class="contenido-titulos">Información General</p></div><!--Titulo -->

       <p>Para recibir comisiones el Empresario TRON debe encontrarse activo en la red y que al último día del mes a liquidar cumplan con alguna de las siguientes condiciones: <br><br>

        <ul class="list-unstyled lista-Info-General">
           <li>1. Que tengan amigos en su red vinculados al Plan Empresario TRON y estos hayan hecho compras.
           </li>

           <li>2. Que tengan amigos vinculados por ellos en el Plan Cliente TRON y estos hayan hecho compras.
           </li>

           <li>3. Que amigos vinculados por ellos al Plan Empresario TRON, tengan amigos vinculados por ellos en el Plan Cliente   TRON y estos hayan hecho compras.
           </li>
        </ul>

       	Las Comisiones se liquidan los primeros 3 días hábiles del mes siguiente al mes que se liquida. <br><br>
       	Las comisiones se pierden cuando un Empresario TRON se inactiva un mes, o sea, no realiza su compra mínima mensual reglamentaria. ($ 25.000 en productos TRON para el hogar ó $ 40.000 en productos industriales fabricados por Tecnologías Aplicadas S.A.). <br><br>
       	Al registrarse en el Plan Empresario TRON, se crearán dos (2) cuentas virtuales a nombre del usuario. La cuenta Dinero y la cuenta Puntos. El 70% del valor total de comisiones serán consignadas en la cuenta Dinero y el 30% restante serán consignados en la cuenta Puntos y estos sólo se utilizaran para compras en la Tienda Virtual. Cada punto tendrá el valor de $1 M/cte. (un peso moneda colombiana corriente). <br><br>
       	Las liquidaciones se basan en todas las compras de productos hechas en el mes por las personas que conforman tu red (“Mis amigos” y “los Amigos de mis Amigos”) registrados en el Plan Empresarios TRON hasta el nivel sexto (6º.) en tu Red y todas las compras de productos hechas en el mes por las personas registradas con tu Código de Usuario en el Plan Cliente TRON. <br><br>
       	Hay algunas cuantías sobre las que no se pagan comisiones, estas son: el IVA, el valor del transporte, la compra de accesorios o de productos promocionales los cuales se encuentran identificados con el ícono</p>
    </div><!--Información General-->














































   </div><!--Contenido-De-La-Pagina = Titulos , Texto ,Informacion -->

<!--////////////////////////////////////////////////-Columna-Derecha-/////////////////////////////////////////////////////////////-->

    <div class="col-lg-3 cont-columna-derecha"><!--Columna-Derecha -->
       <div class="columna-izquierdad-azul"><!-- Primera-parte -->
       	  <div>
       	  	   <div class="blockques-opciones"><a href="<?= BASE_URL ;?>terceros/red_de_aimigos_tron"><img src="<?= BASE_IMG_TIENDA ;?>red.png" /> <p>	La Red de Amigos TRON</p></a>
       	  	   </div>

       	  	   <div class="blockques-opciones"><a href="<?= BASE_URL ;?>terceros/tron_productos"><img src="<?= BASE_IMG_TIENDA ;?>productos.png" /><p>Los Productos TRON</p></a>
       	  	   </div>
       	  </div>

       	  <div>
       	  	   <div class="blockques-opciones"><a href="<?= BASE_URL ;?>terceros/kint_de_inicio"><img src="<?= BASE_IMG_TIENDA ;?>kit.png" /><p>Kit de Inicio <br></p></a>
       	  	   </div>

       	  	   <div class="blockques-opciones"><a href="<?= BASE_URL ;?>terceros/pases_de_cortesia"><img src="<?= BASE_IMG_TIENDA ;?>pases.png" /> <p>Pases de Cortesia</p></a></div>
       	  </div>

       	  <div>
       	  	   <div class="blockques-opciones"><a href="<?= BASE_URL ;?>terceros/comisiones"><img src="<?= BASE_IMG_TIENDA ;?>comision.png" /><p>Comisiones</p></a>
       	  	   </div>

       	  	   <div class="blockques-opciones"><a href="#"><img src="<?= BASE_IMG_TIENDA ;?>bono.png" /><p>Bonificaciones</p></a>
       	  	   </div>

       	  </div>
       </div><!-- Primera-parte -->

      <div class="linea-division"></div><!--Este div Divide la Parte Azul de la Roja -->

       <div class="columna-izquierdad-rojo"><!-- Primera-parte -->
       	  <div>
       	  	   <div class="blockques-opciones-rojo"><a href="#"><img src="<?= BASE_IMG_TIENDA ;?>preguntas.png" /> <p>	Preguntas Frecuentes </p></a></div>


       	  	   <div class="blockques-opciones-rojo"><a href="#"><img src="<?= BASE_IMG_TIENDA ;?>contacto.png" /><p>Contactanos</p></a></div><br>

       	  </div>

       	  <div>
       	  	   <div class="blockques-opciones-rojo"><a href="#"><img src="<?= BASE_IMG_TIENDA ;?>garantia.png" /><p>Garantia de Calidad</p></a>
       	  	   </div>

       	  	   <div class="blockques-opciones-rojo"><a href="#"><img src="<?= BASE_IMG_TIENDA ;?>tecnoaplicadas.png" /> <p>Tecnologias Aplicadas S.A.</p></a></div>
       	  </div>

       	  <div>
       	  	   <div class="blockques-opciones-rojo"><a href="#"><img src="<?= BASE_IMG_TIENDA ;?>terminos.png" /><p>Terminos y Condiciones</p></a>
       	  	   </div>
       	  </div>
       </div><!-- Segunda-parte -->

    </div><!--Columna-Derecha -->
</div><!--Fin-Fila-->
</div><!--Contenedor-De-La-Pagina-->
<br><br> <br>
