<!-- Los estilos Css se encuentran en la carpeta Css => error.css -->

<div class="cont-pag-error">
    <div class="row">
       <div class="col-lg-12">
           <div class="contenedor-informacion">
              <h2>No se a Enocntrado Productos</h2>
           </div>
       </div>

       <div class="col-lg-12">
       	  <div class="contenedor-boton-comprar"><!--Cont-Boton-Comprar -->
       		    <a href="<?= BASE_URL ;?>index" class="carrito-comprar">Volver al Inicio</a>
       	  </div><!--Cont-Boton-Comprar -->
       </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
