<!--
     CSS =>  tron_activacion_mi_cuenta.css
     JS  =>
   -->
   <div class="contenedor">
    <!-- Contenedor principal -->
    <div class="row">
      <!-- Formulario -->
      <div class="contenedor-formulario">
        <div class="row">

         <div class="col-lg-12 col-md-12 col-sm-12">

          <!-- Titulo -->
          <div class="col-lg-12 col-md-12 col-sm-12">
            <div>
              <h3 class="text-center titulo_activacion_cuenta">Activación de Cuenta</h3>
            </div>
          </div>

          <!-- Cont => Formulario -->
          <div>
            <form class="form-horizontal" role="form">

             <!-- Email -->
             <div class="col-lg-12 col-md-12 col-sm-12">
              <div class="form-group">
               <label for="email_activar_cuenta" class="col-lg-5 control-label"><p class="text-label">Email:</p></label>
               <div class="col-lg-7">
                <input type="text" class="form-control" id="email_activar_cuenta"  value="<?=$this->email ;?>" disabled>
              </div>
            </div>
          </div>
          <div class="col-lg-12 col-md-12 col-sm-12">
           <div class="form-group"><!--Codigo  -->
             <label for="codigo" class="col-lg-5 control-label"> <p class="text-left text-label">Código de verificación :</p></label>
             <div class="col-lg-7">
               <input type="password" class="form-control" id="codigo-verificacion" value="<?=$this->codigo_confirmacion ;?>" disabled>
             </div>
           </div>
         </div>
         <!-- contraseña -->
         <div class="col-lg-12 col-md-12 col-sm-12">
          <div class="form-group">
           <label for="password_activar_cuenta" class="col-lg-5 control-label"><p class="text-label" > Contraseña: </p></label>
           <div class="col-lg-7">
            <input type="password" class="form-control" id="password_activar_cuenta"placeholder="Contraseña" >
          </div>
        </div>
      </div>
      <!-- Confirmar contraseña -->
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="form-group">
         <label for="confir-password_activar_cuenta" class="col-lg-5 control-label"><p class="text-label"> Confirmar: </p></label>
         <div class="col-lg-7">
          <input type="password" class="form-control" id="confir-password_activar_cuenta" placeholder="Repita Contraseña">
        </div>
      </div>
    </div>


    <!-- Teriminos y condiciones -->
    <div class="cont_terminos_condiciones">
      <div class="col-lg-12 col-sm-12 col-md-12">
       <div class="text-center">
        <input type="checkbox" id="acepto_terminos_y_condiciones" >
        <label for="acepto_terminos_y_condiciones" id="label_acepto_terminos" class="label_termino_condiciones">He leido y acepto los
          <!-- Link => ventana modal = Terminos y condiciones -->
          <a href="#" data-toggle="modal"  data-target="#terminos_condicones_modal">Términos y condiciones</a>
        </label>
        <!-- Incluye la estructura de la ventana modal -->
        <?php include (APPLICATION_SECTIONS . 'ventana_modal_termino_condiciones.php');?>
      </div>
    </div>
  </div>

  <!-- Btn => Activar cuenta -->
  <div>
  <br>



    <div class="text-center">
    <?php include (APPLICATION_SECTIONS . 'indicador_procesos.php');?>
      <button type='button' id="btn-activar_cta_ocasional" class="btn btn-success" idtercero = '<?= $this->idtercero ;?>'>Activar mi cuenta y finalizar registro</button>
    </div>
  </div>


</form>
</div>

</div>

</div>
</div>
</div>
<!-- Contenedor principal -->
</div>
<br>
<br>

