<!--
     CSS =>  tron_activacion_mi_cuenta.css
     JS  =>  tron_terceros_activar_cuenta.js
   -->
   <div class="contenedor">
      <!-- Formulario -->
      <div class="contenedor-formulario">
        <div class="row">
         <div class="col-lg-12 col-md-12 col-sm-12">
          <!-- Titulo -->
          <div class="col-lg-12 col-md-12 col-sm-12">
            <div>
              <h3 class="text-center titulo_activacion_cuenta">Activación de Cuenta</h3>
            </div>
          </div>

          <!-- Cont => Formulario -->
          <div>
            <form class="form-horizontal" role="form">

             <!-- Email -->
              <div class="form-group">
                 <label for="email_activar_cuenta" class="col-lg-5 control-label"><p class="text-label">Email:</p></label>
                 <div class="col-lg-7">
                   <input type="text" class="form-control" id="email_activar_cuenta"  value="<?=$this->email ;?>" disabled>
                 </div>
              </div>

           <!--Codigo  -->
            <div class="form-group">
               <label for="codigo" class="col-lg-5 control-label"> <p class="text-left text-label">Código de verificación :</p></label>
               <div class="col-lg-7">
                 <input type="password" class="form-control" id="codigo-verificacion" value="<?=$this->codigo_confirmacion ;?>" disabled>
               </div>
            </div>

                <!-- Incluir = Nueva Contraseña ,  Confirmar Contraseña -->
                <?php include (APPLICATION_SECTIONS . 'editar_password.php');?>

          <!-- Teriminos y condiciones -->
          <div class="cont_terminos_condiciones">
            <div class="col-lg-12 col-sm-12 col-md-12">
             <div class="text-left">
              <input type="checkbox" id="acepto_terminos_y_condiciones" >
              <?php if ($this->idtipo_plan_compras <>3) : ?>
                  <label for="acepto_terminos_y_condiciones" id="label_acepto_terminos" class="label_termino_condiciones">He leido y acepto los
                    <!-- Link => ventana modal = Terminos y condiciones -->
                    <a href="#" data-toggle="modal"  data-target="#terminos_condicones_modal">Términos y condiciones</a>
                  </label>
                <?php else :?>
                  <label for="acepto_terminos_y_condiciones" id="label_acepto_terminos" class="label_termino_condiciones">He leido y estoy de acuerdo con el
                    <a href="#convenio_comercial_modal" data-toggle="modal"  data-target="#convenio_comercial_modal">Convenio Comercial</a> <br>y con los
                    <a href="#terminos_condicones_modal" data-toggle="modal"  data-target="#terminos_condicones_modal">Términos y condiciones</a> de este sitio.
                  </label>

              <?php endif ;?>

              <!-- Incluye =
                   *  ventana modal terminos y condiciones
                   *  ventana modal converio comercial -->
              <?php include (APPLICATION_SECTIONS . 'ventana_modal_termino_condiciones.php');?>
              <?php include (APPLICATION_SECTIONS . 'convenio_comercial_modal.php');?>
            </div>
          </div>
        </div>

  <!-- Btn => Activar cuenta -->
  <div>
  <br>



    <div class="text-center">
       <?php include (APPLICATION_SECTIONS . 'indicador_procesos.php');?>
      <button type='button' id="btn-activar_cta_ocasional" class="btn btn-success" idtercero = '<?= $this->idtercero ;?>'>Activar mi cuenta y finalizar registro</button>
    </div>
  </div>


</form>
</div>

</div>

</div>
</div>
</div>
<br>
<br>

