<div class="contenedor_vista">
	  <div class="row" style="padding: 0px;">
         <div class="col-lg-12 col-md-12 col-sm-12" style="padding: 0px;">
         	     <!-- Columna - Izquierdad -->
               <div class="col-lg-2 col-md-2 col-sm-2 padding_none " style="width: 250px;">
		         	     <div class="barra_tabs">
		                   <div><!-- Contenedor -->
		                      <!-- Contenedor  =  Mi perfil-->


		                      <!-- Contenedor  = Informes -->
		                       <div class="tabs_click" id="mi-perfil">
		                          <div class="row">
		                           <div class="col-lg-12">
		                           	    <h4>Mi Perfil</h4>
																																		<div class="descriptcion_tab"><!-- Descripcion -->
																																			   <p>Información Personal,</p>
																																			   <p>pases de cortesía,</p>
																																			   <p>recomendar modelo de negocio,</p>
																																			   <p>mi plan actual.</p>
																																		</div>
		                           </div>
		                        </div>
		                       </div>

		                      <!-- Contenedor  = Informes -->
		                       <div class="tabs_click" id="informes_pedidos">
		                          <div class="row">
		                           <div class="col-lg-12">
		                           	    <h4>Pedidos e Informes</h4>
																																		<div class="descriptcion_tab"><!-- Descripcion -->
																																			   <p>Pedidos realizados,</p>
																																			   <p>estado de mis cuentas e</p>
																																			   <p>informes de la actividad</p>
																																			   <p>de los integrantes de mi red.</p>
																																		</div>
		                           </div>
		                        </div>
		                       </div>

		                      <!-- Contenedor  = Favoritos -->
		                       <div class="tabs_click" id="favoritos">
		                          <div class="row">
		                           <div class="col-lg-12">
		                           	    <h4>Favoritos</h4>
 																																		<div class="descriptcion_tab"><!-- Descripcion -->
																																			   <p>Acceso rápido</p>
																																			   <p>a mis productos</p>
																																			   <p>favoritos</p>

																																		</div>
		                           </div>
		                        </div>
		                       </div>

		                   </div>
		         	     </div>
               </div>

              <!-- columna - derecha -->
         	     <div class="col-lg-9 col-md-9 col-sm-9">
                   <div class="row" id="con-row-menu">
			                  <div class="col-lg-12 col-md-12 col-sm-12"  >
			                  	   <!-- Contenedor Informacion Tabs -->
                         <div>
					                  	   <div class="col-lg-12 col-md-12 col-sm-12 "  style="padding-left: 0px;">
					                  	   	   <div><!-- Contenedor -->

					                                <div><!-- CABEZERAS  -->
					                                	   <div id="cabezera_perfil" class="cabezera" style="display: block;">
					                                       <!-- Mi perfil -->
					                                         <div class="col-lg-12 col-md-12 col-sm-12"  style="padding-left: 0px;">
								                                       <!-- Titulo -->
<!-- 								                                	       <div class="cont-tab-titulo">
								                                	       	   <h3> <strong>Mi Perfil</strong> </h3>
								                                	       </div> -->

								                                         <div class="menu_perfil"><!-- Menu -->
										                                	   	    <nav>
										                                	   	    	   <ul>
										                                	   	    	   	   <li><a class="perfil_menu_link" href="#" id="plan_seleccionado">Plan Seleccionado</a></li>
										                                	   	    	   	   <li><a class="perfil_menu_link" href="#" id='perfil-datos-personales'>Datos Personales</a></li>
										                                	   	    	   	   <li><a class="perfil_menu_link" href="#" id="recomendar_amigo">Recomendar </a></li>
										                                	   	    	   	   <li><a class="perfil_menu_link" href="#" id="pases_cortesia">Pases</a></li>
										                                	   	    	   	   <li><a class="perfil_menu_link" href="#" id="convenio_comercial">Convenio Comercial</a></li>
										                                	   	    	   	   <li><a class="perfil_menu_link" href="#" id="tabla_comisiones">Tabla Comisiones</a></li>
										                                	   	    	   </ul>
										                                	   	    </nav>
								                                         </div>
					                                         </div>
					                                        </div>

					                                        <!-- informes y pedidos -->
					                                         <div id="cabezera_informes" class="cabezera">
												                                	   <div class="col-lg-12 col-md-12 col-sm-12  "  style="padding-left: 0px;">
												                                         <div id="cabezera_perfil">
															                                       <!-- Titulo -->
<!-- 															                                	       <div class="cont-tab-titulo">
															                                	       	   <h3> <strong>Informes y Pedidos</strong> </h3>
															                                	       </div> -->

															                                         <div class="menu_perfil"><!-- Menu -->
																	                                	   	    <nav>
																	                                	   	    	   <ul>
																	                                	   	    	   				<li><a class="perfil_menu_link" href="#" id='informes-pedidos-realizados'>Pedidos Realizados</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#"id ='informes-estado-cuenta' >Estado de Cuentas</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#" id='informes-participacion-red' title="Participación en la Red">Partic. en la Red</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#" id ='informes-red-usuarios'>Mi Red </a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Amigos Presentados</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#" id="compras_tron_link">Compra Tron</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Compra Otros</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#" title="Compras Indiustriales">Compra Indust.</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Totales </a></li>
																	                                	   	    	   </ul>
																	                                	   	    </nav>
															                                         </div>
												                                         </div>
												                                        </div>
					                                         </div>

					                                        <!-- informes y pedidos -->
					 			                                	   <div id="cabezera_favoritos" class="cabezera">
								                                       <!-- Mi perfil -->
								                                         <div class="col-lg-12 col-md-12 col-sm-12   "  style="padding-left: 0px;">
											                                       <!-- Titulo -->
<!-- 											                                	       <div class="cont-tab-titulo">
											                                	       	   <h3> <strong>Favoritos</strong> </h3>
											                                	       </div> -->

											                                         <div class="menu_perfil"><!-- Menu -->
													                                	   	    <nav>
													                                	   	    	   <ul>
													                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Plan Seleccionado</a></li>
													                                	   	    	   	   <li><a class="perfil_menu_link" href="#" >Datos Personales</a></li>
													                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Recomendar Negocio</a></li>
													                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Pases Cortesía</a></li>
													                                	   	    	   </ul>
													                                	   	    </nav>
											                                         </div>
								                                         </div>
								                                        </div>
					                                </div>
					                  	   	   </div>
					                  	   </div>
                         </div>
			                  </div>
                   </div>

                    <div class="contenedor_cuenta">

	                         <div class="row">
                         	  <div class="col-lg-12">
                         	  	   <div></div>
                         	  </div>
                         </div>
                        </div>
         	     </div>
         </div>
	  </div>
</div>
<br>
<br>
<br>



