<div class="contenedor_vista">
	  <div class="row">
         <div class="col-lg-12 col-md-12 col-sm-12">
         	     <!-- Columna - Izquierdad -->
               <div class="col-lg-2 col-md-2 col-sm-2 padding_none " style="width: 250px;">
		         	     <div class="barra_tabs">
		                   <div><!-- Contenedor -->
		                      <!-- Contenedor  =  Mi perfil-->
		                       <div class="tabs_click" id="mi_perfil">
		                          <div class="row">
		                           <div class="col-lg-12">
		                           	    <h4 class ='tab-mi-perfil'>Mi Perfil</h4>
																																		<div class="descriptcion_tab tab-mi-perfil"><!-- Descripcion -->
																																			   <p>Información Personal,</p>
																																			   <p>pases de cortesía,</p>
																																			   <p>recomendar modelo de negocio,</p>
																																			   <p>mi plan actual.</p>
																																		</div>
		                           </div>
		                        </div>
		                       </div>

		                      <!-- Contenedor  = Informes -->
		                       <div class="tabs_click" id="informes_pedidos">
		                          <div class="row">
		                           <div class="col-lg-12">
		                           	    <h4>Informes y Pedidos</h4>
																																		<div class="descriptcion_tab"><!-- Descripcion -->
																																			   <p>Pedidos realizados,</p>
																																			   <p>estado de mis cuentas e</p>
																																			   <p>informes de la actividad</p>
																																			   <p>de los integrantes de mi red.</p>
																																		</div>
		                           </div>
		                        </div>
		                       </div>

		                      <!-- Contenedor  = Favoritos -->
		                       <div class="tabs_click" id="favoritos">
		                          <div class="row">
		                           <div class="col-lg-12">
		                           	    <h4>Favoritos</h4>
 																																		<div class="descriptcion_tab"><!-- Descripcion -->
																																			   <p>Acceso rápido</p>
																																			   <p>a mis productos</p>
																																			   <p>favoritos</p>

																																		</div>
		                           </div>
		                        </div>
		                       </div>

		                   </div>
		         	     </div>
               </div>

              <!-- columna - derecha -->
         	     <div class="col-lg-9 col-md-9 col-sm-9">
                   <div class="row" id="con-row-menu">
			                  <div class="col-lg-12 col-md-12 col-sm-12"  >
			                  	   <!-- Contenedor Informacion Tabs -->
                         <div>
					                  	   <div class="col-lg-12 col-md-12 col-sm-12 "  style="padding-left: 0px;">
					                  	   	   <div><!-- Contenedor -->

					                                <div><!-- CABEZERAS  -->
					                                	   <div id="cabezera_perfil" class="cabezera" style="display: block;">
					                                       <!-- Mi perfil -->
					                                         <div class="col-lg-12 col-md-12 col-sm-12"  style="padding-left: 0px;">
								                                       <!-- Titulo -->
								                                	       <div class="cont-tab-titulo">
								                                	       	   <h3> <strong>Mi Perfil</strong> </h3>
								                                	       </div>

								                                         <div class="menu_perfil"><!-- Menu -->
										                                	   	    <nav>
										                                	   	    	   <ul>
										                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Plan Seleccionado</a></li>
										                                	   	    	   	   <li><a class="perfil_menu_link" href="#" id='perfil-datos-personales'>Datos Personales</a></li>
										                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Recomendar </a></li>
										                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Pases</a></li>
										                                	   	    	   </ul>
										                                	   	    </nav>
								                                         </div>
					                                         </div>
					                                        </div>

					                                        <!-- informes y pedidos -->
					                                         <div id="cabezera_informes" class="cabezera">
												                                	   <div class="col-lg-12 col-md-12 col-sm-12  "  style="padding-left: 0px;">
												                                         <div id="cabezera_perfil">
															                                       <!-- Titulo -->
															                                	       <div class="cont-tab-titulo">
															                                	       	   <h3> <strong>Informes y Pedidos</strong> </h3>
															                                	       </div>

															                                         <div class="menu_perfil"><!-- Menu -->
																	                                	   	    <nav>
																	                                	   	    	   <ul>
																	                                	   	    	   				<li><a class="perfil_menu_link" href="#">Pedidos Realizados</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Estado de Cuentas</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#" title="Participación en la Red">Partic. en la Red</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Mi red </a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Amigos Presentados</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Compra Tron</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Compra Otros</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#" title="Compras Indiustriales">Compra Indust.</a></li>
																	                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Totales </a></li>
																	                                	   	    	   </ul>
																	                                	   	    </nav>
															                                         </div>
												                                         </div>
												                                        </div>
					                                         </div>

					                                        <!-- informes y pedidos -->
					 			                                	   <div id="cabezera_favoritos" class="cabezera">
								                                       <!-- Mi perfil -->
								                                         <div class="col-lg-12 col-md-12 col-sm-12   "  style="padding-left: 0px;">
											                                       <!-- Titulo -->
											                                	       <div class="cont-tab-titulo">
											                                	       	   <h3> <strong>Favoritos</strong> </h3>
											                                	       </div>

											                                         <div class="menu_perfil"><!-- Menu -->
													                                	   	    <nav>
													                                	   	    	   <ul>
													                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Plan Seleccionado</a></li>
													                                	   	    	   	   <li><a class="perfil_menu_link" href="#" >Datos Personales</a></li>
													                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Recomendar Negocio</a></li>
													                                	   	    	   	   <li><a class="perfil_menu_link" href="#">Pases Cortesía</a></li>
													                                	   	    	   </ul>
													                                	   	    </nav>
											                                         </div>
								                                         </div>
								                                        </div>
					                                </div>
					                  	   	   </div>
					                  	   </div>
                         </div>
			                  </div>
                   </div>
                    <div class="contenedor_cuenta">
	                         <div class="row">
                         	  <div class="col-lg-12">
                         	  	   <div>
                         	  	   	   <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe vero explicabo sapiente, nesciunt inventore illo ullam itaque repudiandae suscipit, velit libero magni. Eaque, consectetur, repellendus repellat deleniti animi iure! Laudantium?</div>
                         	  	   	   <div>Beatae ratione, excepturi fuga maiores debitis. Totam, sunt dolorum, minima quod magni sed quas necessitatibus at omnis cumque, ipsum pariatur molestiae blanditiis voluptatibus? Harum atque doloribus at, blanditiis explicabo saepe!</div>
                         	  	   	   <div>Eos, quaerat, quos? Impedit commodi suscipit, neque, saepe quasi eaque iste obcaecati sunt in a! Sunt repudiandae iste, enim vero nemo ad est ipsum quaerat eligendi nam reprehenderit libero aperiam.</div>
                         	  	   	   <div>Tempora cupiditate adipisci cum, debitis, nam reiciendis aliquid! Praesentium hic impedit expedita odit facere perspiciatis eveniet reprehenderit iste, nemo consectetur aperiam velit maxime quaerat doloremque. Consequuntur corrupti saepe, eos minima?</div>
                         	  	   	   <div>Molestias atque, iure dolorum similique maxime ipsa facilis eum, corporis nostrum, veniam voluptatibus quo. Nemo in repellendus blanditiis mollitia dolorem corporis accusamus error, nam recusandae, eum harum laudantium modi molestiae.</div>
                         	  	   	   <div>Laboriosam incidunt aperiam porro maxime architecto quaerat, veritatis placeat quod, animi soluta, necessitatibus, tenetur ducimus! Ut neque, provident error. Enim commodi fugit numquam nisi quod temporibus, asperiores animi sequi modi.</div>
                         	  	   	   <div>Sint maiores similique sit accusantium at vitae fuga, totam dolore libero magnam harum. Nulla quas, omnis, ab error natus, officia voluptas commodi eius autem iure esse, eum expedita. Ad, at.</div>
                         	  	   	   <div>Molestias officia laboriosam hic eos provident voluptatem, repellendus dolores explicabo eaque! Eos expedita, laborum blanditiis. Quas neque harum sapiente eligendi veritatis atque ratione iusto, consequatur, est repellat voluptatibus dicta id.</div>
                         	  	   	   <div>Nisi necessitatibus eos harum enim, consectetur tenetur doloribus sed delectus ad, dolores doloremque, fugit dolorem dolor reprehenderit eius eligendi molestias ratione voluptate corporis porro numquam! Necessitatibus, eligendi consequuntur totam amet!</div>
                         	  	   	   <div>Eius voluptatem, pariatur deleniti non facilis minima assumenda quo laboriosam aliquam expedita magni, eligendi consectetur cum laudantium, soluta ipsam nihil rem et similique enim provident mollitia excepturi odio dolor corporis!</div>
                         	  	   </div>
                         	  </div>
                         </div>
                        </div>
         	     </div>
         </div>
	  </div>
</div>
<br>
<br>
<br>



