<!-- llamado de la ventana modal del convenio comercial -->
	<?php include (APPLICATION_SECTIONS . 'convenio_comercial_modal.php');?>
<!--  / llamado de la ventana modal del convenio comercial -->


<div class="ionix">
    <div class="general pAA30 mb30">
		<div class="row">

            <img src="../public/images/tienda/menu.png" id="menuAppr" class="cP" style="position:absolute; top:30px; left:-52px; z-index:100; display:none;" />

            <div id="columna_izquierdad" class="col-sm-2 col-xs-12 vcenter" style="vertical-align:top; position:relative;"><!-- Columna - Izquierdad -->
                <!-- BTN = Mostrar TABs -->
                <?php include (APPLICATION_SECTIONS . 'micuenta_lateral.php');?>
            </div><!--

            --><div id="columan_derecha" class="col-sm-10 col-xs-12 vcenter"><!-- columna - derecha -->

            	<article class="rgts_pasos">

                    <div id="cabezera_perfil" class="menuMiCuenta"><!-- Menu -->
                        <ul>
                            <li><a class="perfil_menu_link" href="#" id="plan_seleccionado" style="background-color:#003e90;"><span>Plan Seleccionado</span></a></li>
                            <li><a class="perfil_menu_link" href="#" id='perfil-datos-personales'><span>Datos Personales</span></a></li>
                            <?php if ( $this->idtipo_plan_compras == 3 ) :?>
                                <li><a class="perfil_menu_link" href="#" id="recomendar_amigo"><span>Recomendar</span></a></li>
                                <!--<li><a class="perfil_menu_link" href="#" id="pases_cortesia">Pases</a></li>-->
                                <!-- BTN = Convenio comercial
                                <li style="position:relative;" id="cont_conevion_comercial">
                                    <a class="perfil_menu_link" href="#" id="convenio_comercial"><span>Convenio Comercial</span></a>
                                    <ul class="menu_convenio" style="display:none">
                                        <li><a  href="#convenio_comercial_modal" data-toggle="modal" data-target="#convenio_comercial_modal" class="link_convenio"><span>Vista Previa</span></a></li>
                                        <li><a href="#" class="link_convenio" id="convenio_pdf"><span>Imprimir / Grabar</span></a></li>
                                    </ul>
                                </li>
                                -->
                                <li><a class="perfil_menu_link" href="#" id="convenio_pdf"><span>Convenio Comercial<br><small>( Ver/Imprimir )</small></span></a></li>
                                 <li><a class="perfil_menu_link" href="#" id="tabla_comisiones"><span>Plan de Compensaciones</span></a></li>
                            <?php endif ;?>
                        </ul>
                    </div>

                    <div id="cabezera_informes" class="cabezera menuMiCuenta">
                        <ul>
                            <li><a class="perfil_menu_link" href="#" id='informes-pedidos-realizados'><span>Pedidos Realizados</span></a></li>
                            <li><a class="perfil_menu_link" href="#"id ='informes-estado-cuenta' ><span>Estado de Cuentas</span></a></li>
                            <?php if ( $this->idtipo_plan_compras == 3 ) :?>
                                <li><a class="perfil_menu_link" href="#" id ='informes-participacion-red' title="Participación en la Red"><span>Partic. en la Red</span></a></li>
                                <li><a class="perfil_menu_link" href="#" id ='informes-red-usuarios'><span>Mi Red</span></a></li>
                                <li><a class="perfil_menu_link" href="#" id ='informes-amigos-presentados' title="Empresarios Presentados"><span>Empresarios Presen.</span></a></li>
                                <li><a class="perfil_menu_link" href="#" id ='informes-clientes-presentados' title="Clientes Presentados"><span>Clientes Presentados</span></a></li>
                                <li><a class="perfil_menu_link" href="#" id ="compras_tron_link"><span>Compra Tron</span></a></li>
                                <li><a class="perfil_menu_link" href="#" id ="compras_otros_link"><span>Compra Otros</span></a></li>
                                <li><a class="perfil_menu_link" href="#" id ="compras_industriales_link" title="Compras Indiustriales"><span>Compra Indust.</span></a></li>
                                <li><a class="perfil_menu_link" href="#" id ="compras_totales_link"><span>Compras Totales</span></a></li>
                            <?php endif ;?>
                        </ul>
                    </div>

                    <div id="cabezera_favoritos" class="cabezera menuMiCuenta">
                        <ul>
                            <li><a class="perfil_menu_link" href="#" id="cuenta_favoritos"><span>Mis Favoritos</span></a></li>
                        </ul>
                    </div>

                    <div class="contenedor_cuenta">

                    	<?php include 'views/terceros/plan_seleccionado.phtml'; ?>

                    </div>

                </article>



			</div>
		</div>
	</div>
</div>

