<div class="modal fade" id="ventana-final">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header encabezado-modal">
        <h4 class="modal-title">Contraseña modificada con éxito !</h4>
      </div>
      <div class="modal-body">
        <p>Su contraseña ha sido modificada con éxito. Ahora puede iniciar sesión en nuestra tienda virtual.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" id="cerrar-ventana-final">Cerrar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->






<div class="vista-cambiar-password"><!--Contenedor de la pagina -->
  <div class="row">
    <div class="col-lg-12"><!--Fila -->
     <div class="titulo"><!--Titulos -->
       <h2 class="text-center">
         Cambiar Contraseña
       </h2>
     </div><br><br><!--Titulos -->

     <div><!--Contenedor del  fromulario -->
       <form class=" form-horizontal" role="form">
         <!--Formulario -->
         <div class="form-group"><!--Codigo  -->
           <label for="codigo" class="col-lg-5 control-label"> <p class="text-left text-label">Código de verificación :</p></label>
           <div class="col-lg-7">
             <input type="password" class="form-control" id="codigo-verificacion" value="<?=$this->Numero_Confirmacion ;?>" disabled>
           </div>
         </div> <br /><!-- Codigo -->

         <div class="form-group"><!--Nueva contrasseña -->
           <label for="new-password" class="col-lg-5 control-label"> <p class="text-left text-label">Nueva Contaseña:</p></label>
           <div class="col-lg-7">
            <input data-toggle="password" data-placement="before" class="form-control new-password"
            type="password" id="new-password" placeholder="Registre nueva contraseña"/>
          </div>
        </div><!--Nueva contrasseña -->

        <div class="form-group"><!--Confirmar contraseña -->
          <label for="confirmar-password" class="col-lg-5 control-label"><p class="text-left text-label">Confirmar Contraseña:</p></label>
          <div class="col-lg-7" >
            <input data-toggle="password" data-placement="before"class="form-control confirmar-password" type="password"
            id="confirmar-password" placeholder="Confirme la contraseña" />
          </div>
          <div class="text-center" id="mensaje-validacion"></div><br>

        </div><!--Confirmar contraseña -->
      </form><!--Formulario -->

    </div><!--Contenedor del  fromulario -->

  </div>

</div><!--Fila -->
<div class="conten-btn-guardar"><!-- Boton Guardar -->
  <button type="button" class="btn btn-success boton-guarar-password" >Guardar Nueva Contraseña</button>
</div><!-- Boton Guardar -->
</div><!--Contenedor de la pagina -->

<br><br><br>
<br>
<br><br>


