<!--
     Estilos CSS => carpeta CSS => tron_cuenta_pases_cortesia.css
     ******** Cuenta-perfil Pases de Premium **********
-->
<div class="contenedor"><!-- Contenedor de la pagina -->
	   <div class="row">

         <!-- /// Titulo /// -->
            <div class="col-lg-12 col-md-12 col-sm-12">
            	  <div><!-- Contenedor -->
                    <h2 class="titulo"><strong>Pases Premium</strong></h2>
                    <p class="titulo"><strong>Obtén Pases Premium para realizar tus compras con Escala C.</strong></p>
            	  </div><!-- Contenedor -->
            </div>
         <!-- /// Titulo /// -->

        <!-- /// Barra Usuario /// -->
            <?php include (APPLICATION_SECTIONS . 'barra_usuraios.php');?>
        <!-- /// Barra Usuario /// -->

         <!-- /// Cuerpo pagina /// -->
              <div><!-- Contenido-cuerpo-pagina -->
                  <div>
                      <div class="col-lg-12 col-md-12 col-sm-12">
                          <!--  pases Premium -->
                          <div class="col-lg-5 col-md-5 col-sm-5">

                             <div class="cont-img-pases"><!-- IMG  = pases de Premium-->
                                    <a href="<?=  BASE_URL ;?>Terceros/cuenta_pases_de_cortesia"><img src="<?= BASE_IMG_EMPRESA ; ?>pase_premium.png" class="img-pases-permium" /></a>
                             </div><!-- IMG = pases de Premium -->

                          </div>
                          <!-- Comprar pases -->

                           <!-- Info pases-Premium -->
                          <div class="col-lg-7 col-md-7 col-sm-7">
                              <div class="cont-info-pases">
                                   <p><a href="<?=  BASE_URL ;?>Terceros/cuenta_pases_de_cortesia">
                                       <strong> << </strong>
                                       Ver estado de Pases de Cortesia</a>
                                    </p>

                                       <p>Posees 0/5 Pases de Cortesía efectivos. </p>
                                   <div class="cont-barra-cantidad-pases-premium"> <!-- Barra = cantidad Pases-efectivos -->
                                   	   <div class="barra-cantidad-ps-premium">
                                   	   	  <!-- Barra cantidad pases -->
                                   	   </div>
                                   </div> <!-- Barra = cantidad Pases-efectivos -->
                                   <p><em>Acumula 5 para obtener un Pase Premium.</em></p>
                                   <a href="<?= BASE_URL ;?>redtron/pases_de_cortesia">¿Qué es un Pase Premium?</a>
                              </div>
                          </div>
                           <!-- Info pases-Premium -->

                           <!-- Barra =  Mis-Pases Premium -->
                              <div class="col-lg-12 col-md-12 col-sm-12">
                              	  <div class="barra_bottom_premium"><!-- Contenedor -->
                              	  	   <p>Mis Pases Premium</p>
                              	  	   <p>No posees ningún Pase Premium</p>
                              	  </div><!-- Contenedor -->
                              </div>
                           <!-- Barra =  Mis-Pases Premium -->

                      </div>
                  </div>
              </div><!-- Contenido-cuerpo-pagina -->
         <!-- /// Cuerpo pagina /// -->
	   </div>
</div><!-- Contenedor de la pagina -->
<br><br><br>
