<!--
    js          => Carpeta Js  =>
    Estilos CSS => Carpeta CSS => tron_cuenta_info_partici_la_red.css
          ************ Participacion de la red ************
-->
<div class="contenedor"><!-- contenedor de la pagina -->
	  <div class="row">

         <!-- /// Titulo /// -->
             <div class="col-lg-12 col-md-12 col-sm-12">
             	   <div>
             	   	   <h2 style="color: #003e90; margin-top: -10px;"><strong>Informes</strong></h2>
             	   </div>
             </div>
         <!-- /// Titulo /// -->

      <!-- /// Barra = Infromacion /// -->
      <?php include (APPLICATION_SECTIONS . 'cuenta_navbar_informe.php');?>
      <!-- /// Barra Usuario /// -->
      <?php include (APPLICATION_SECTIONS . 'barra_usuraios.php');?>


       <!-- /// Tabla = Participación de mis amigos  /// -->
           <div class="col-lg-12 col-md-12 col-sm-12">
           	   <div><!-- Contenedor -->
           	   	     <table class="table table-bordered table-hover">

           	   	     	    <thead><!-- cabezera -->
           	   	     	    	    <tr>
           	   	     	    	    	   <th class="text-center">#</th>
           	   	     	    	    	   <th class="text-center">Codigo de Usuario</th>
           	   	     	    	    	   <th class="text-center">Nombre</th>
           	   	     	    	    	   <th class="text-center">Presentado por</th>
           	   	     	    	    	   <th class="text-center">Fecha Reg.</th>
           	   	     	    	    	   <th class="text-center">Cant. Frontales</th>
           	   	     	    	    	   <th class="text-center">Cant .Codigo por Persona</th>
           	   	     	    	    </tr>
           	   	     	    </thead><!-- cabezera -->

           	   	     	    <tbody>
           	   	     	    	     <tr>
           	   	     	    	     	   <td class="text-center">1</td>
           	   	     	    	     	   <td class="text-center">EG2904TRON</td>
           	   	     	    	     	   <td class="text-center">ERNESTO GARRIDO CARRERO</td>
           	   	     	    	     	   <td class="text-center">JUAN BAUTISTA ANDRAD</td>
           	   	     	    	     	   <td class="text-center">29/11/2013</td>
           	   	     	    	     	   <td class="text-center"></td>
           	   	     	    	     	   <td class="text-center">1</td>
           	   	     	    	     </tr>
           	   	     	    </tbody>

           	   	     </table>
           	   </div><!-- Contenedor -->
           </div>
       <!-- /// Tabla = Participación de mis amigos  /// -->

	  </div>
</div><!-- contenedor de la pagina -->
<br>
<br>
<br>
