<!--
     Js          => Carpeta Js  =>
     Estilos css => Carpeta CSS => tron_informe_mi_cuenta.css
          ******** Informacion Sobre Mi Cuenta  ********
-->
<div class="contenedor"><!-- Contenedor de la pagina -->
	   <div class="row">

         <!-- /// Titulo /// -->
             <div class="col-lg-12">
             	   <div>
             	   	   <h2 style="color: #003e90; margin-top: -10px;"><strong>Informes</strong></h2>
             	   </div>
             </div>
         <!-- /// Titulo /// -->



      <!-- /// Barra = Infromacion /// -->
      <?php include (APPLICATION_SECTIONS . 'cuenta_navbar_informe.php');?>
      <!-- /// Barra Usuario /// -->
      <?php include (APPLICATION_SECTIONS . 'barra_usuraios.php');?>




         <!-- /// Division-pagina = Mi cuenta dinero ,  Mi cuanta puntos /// -->
             <!-- Mi cuenta_dinero -->
               <div class="col-lg-6 col-md-6 col-sm-6">

                     <div class="col-lg-12 col-md-12 col-sm-12"><!-- logo = Cuenta-dinero -->
                     	   <div><!-- Contenededor -->
                     	   	    <p class="Estado-cuenta"  style="color: #009900;">Estado de Mi Cuenta Dinero</p>
                     	   	    <p class="saldos" style="color: #009900;">Saldo: $0</p>
                     	   </div><!-- Contenededor -->
                     </div><!-- logo = Cuenta-dinero -->

                     <div class="col-lg-12 col-md-12 col-ms-12"><!-- Tabla-Cuenta-dinero -->
                          <div class="cont-cabezera-tabla-dinero"><!-- Tabla-header = fija -->
                              <p class="Cabezera-tabla text-center" style="width: 15.5%;">Fecha</p>
                              <p class="Cabezera-tabla text-center" style="width: 52%;">Concepto</p>
                              <p class="Cabezera-tabla text-center" style="width: 8%;">Entran</p>
                              <p class="Cabezera-tabla text-center" style="width: 10%;">Salen</p>
                              <p class="Cabezera-tabla text-center" style="width: 8%;">Saldo</p>
                          </div><!-- Tabla-header = fija -->

                          <table class="table table-condensed table-hover cuerpo-tabla">
                            <tbody><!-- Cuerpo -->
                                 <tr>
                                     <td class="fecha text-center">24/01/2014</td>
                                     <td class="text-center concepto">pago parcial de pedidos con con comis. y/o bonif.</td>
                                     <td class="text-center entran">352  </td>
                                     <td class="text-center salen">352  </td>
                                     <td class="text-center saldo">3.00</td>
                                 </tr>

                                  <!-- cont-tabla -->
                                      <?php include (APPLICATION_SECTIONS . 'cont-tabla-informacion-cuenta.php');?>
                                  <!-- cont-tabla -->

                            </tbody><!-- Cuerpo -->
                          </table>
                     </div><!-- Tabla-Cuenta-dinero -->

               </div><!-- Mi cuenta_dinero -->


   <!-- Mi cuenta_Puntos -->
    <div class="col-lg-6">

          <div class="col-lg-12 col-md-12 col-sm-12"><!-- logo = Cuenta-puntos -->
          	   <div><!-- Contenededor -->
          	   	    <p class="Estado-cuenta" style="color: #ff6600;" >Estado de Mi Cuenta Puntos</p>
          	   	    <p class="saldos" style="color: #ff6600;">Saldo: 0</p>
          	   </div><!-- Contenededor -->
          </div><!-- logo = Cuenta-puntos -->

         <div class="col-lg-12 col-md-12 col-ms-12"><!-- Tabla-Cuenta-puntos -->
              <div class="cont-cabezera-tabla-puntos"><!-- Tabla-header = fija -->
                  <p class="Cabezera-tabla-puntos text-center" style="width: 15.5%;">Fecha</p>
                  <p class="Cabezera-tabla-puntos text-center" style="width: 52%;">Concepto</p>
                  <p class="Cabezera-tabla-puntos text-center" style="width: 8%;">Entran</p>
                  <p class="Cabezera-tabla-puntos text-center" style="width: 10%;">Salen</p>
                  <p class="Cabezera-tabla-puntos text-center" style="width: 8%;">Saldo</p>
              </div><!-- Tabla-header = fija -->

              <table class="table table-condensed table-hover cuerpo-tabla">
                <tbody><!-- Cuerpo -->
                     <tr>
                         <td class="fecha text-center">24/01/2014</td>
                         <td class="text-center concepto">pago parcial de pedidos con con comis. y/o bonif.</td>
                         <td class="text-center entran">352  </td>
                         <td class="text-center salen">352  </td>
                         <td class="text-center saldo">3.00</td>
                     </tr>

                    <!-- cont-tabla -->
                        <?php include (APPLICATION_SECTIONS . 'cont-tabla-informacion-cuenta.php');?>
                    <!-- cont-tabla -->

                </tbody><!-- Cuerpo -->
              </table>
         </div><!-- Tabla-Cuenta-puntos -->
      </div>
    <!-- Mi cuenta_Puntos -->

         <!-- /// Division-pagina = Mi cuenta dinero ,  Mi cuanta puntos /// -->

         <!-- /// Btn-visualizar = descendente /// -->
             <div class="well col-lg-12 col-md-12 col-ms-12">
             	   <div><!-- Contenedor -->


             	   </div><!-- Contenedor -->
             </div>
         <!-- /// Btn-visualizar = descendente /// -->

































	   </div>
</div><!-- Contenedor de la pagina -->
<br>
<br>
<br>
