<!--  Css => tron_mejor_experiencia_usuario.css -->

<div class="cont-info-pagina">
  <div class="row">

     <!-- Contenedor -->
      <div class="cont-mensaje">
         <div class="row">
					  	   <div class="col-lg-12 col-md-12 col-sm-12">
					          <!-- IMG -->
					          <div class="col-lg-3 col-md-3 col-sm-3">
					          	  <div>
					          	  	 <img src="<?=  BASE_IMG_EMPRESA ;?>alerta_visualizacion.jpg" class="img-responsive">
					          	  </div>
					          </div>

					          <!-- Mensaje -->
					          <div class="col-lg-9 col-md-9 col-sm-9	">
					          	  <div>
					          	  	   <p>Tu navegador <strong>Fire fox</strong> <br><br>
					                      Para una mejor experiencia de usuario descarga e instala las ultimas versiones de algunos de estos naveagadores..!
					          	  	    </p><br>
					          	  </div>
					          </div>

					          <div class="col-lg-12">
					          	  <div>
					          	  	   <img src="<?=  BASE_IMG_EMPRESA ;?>mensaje_navegadores.png" class="img-responsive">
					          	  </div>
					          </div>
					  	   </div>
         </div>
      </div>

   </div>

</div>
<br><br>
