<!--
     Estilos CSS => Capeta CSS => tron_mis_pedidos.css
              ******** Mis Pedidos *******
 -->
<div class="contenedor"><!-- Contebedorlolo -->
    <div class="row">

       <!-- /// Titulo /// -->
          <div class="col-lg-12 col-md-12 col-sm-12">
          	   <div><!-- contendedor -->
                    <h2 style="color: #003e90; margin-top: -10px;"><strong>Historial de pedidos</strong></h2>
                    <p style="color: #003e90;"><strong>Historial de pedidos y facturas.</strong></p>
          	   </div><!-- contendedor -->
          </div>
       <!-- /// Titulo /// -->

        <!-- /// Barra Usuario /// -->
            <?php include (APPLICATION_SECTIONS . 'barra_usuraios.php');?>
        <!-- /// Barra Usuario /// -->


        <!-- /// Cuerpo pagina /// -->
             <div class="col-lg-12 col-md-12 col-sm-12"><!-- Tabla -->
                 <div>	<!-- contenedor -->
                      <table class="table table-bordered ">
                            <thead>	<!-- Cabezera -->
                                   <tr>
                                        <th class="text-center">	Fecha pedido</th>
                                        <th class="text-center">Número <br> pedido</th>
                                        <th class="text-center">Valor <br> pedido</th>
                                        <th class="text-center">Valor a <br> pagar</th>
                                        <th class="text-center">Número <br> factura</th>
                                        <th class="text-center">Estado</th>
                                        <th class="text-center">Medio de <br> pago</th>
                                        <th class="text-center">Eliminar</th>
                                   </tr>
                            </thead><!-- Cabezera -->

                            <tbody><!-- Cuerpo -->
                                   <tr>
                                        <td class="text-center"> 2015-03-03</td><!-- Fecha pedido -->
                                        <td class="text-center"><a href="#">21621</a></td><!-- Numero-Pedido -->
                                        <td class="text-center">65.700</td><!--Valor pedido -->
                                        <td class="text-center">65.700</td><!-- Valor a pagar -->
                                        <td class="text-center">M 7855</td><!-- Número factura -->
                                        <td class="text-center">Pendiente de pago</td><!-- Estado -->
                                        <td class="text-center"><!-- Medio de pago -->
                                           <a href="#">
                                               <img style="width: 25%;" src="<?= BASE_IMG_TIENDA ;?>editar_pago.png" title="Cambiar forma de Pago">
                                           </a>
                                         </td><!-- Medio de pago -->
                                        	<td class="text-center"><!-- Eliminar -->
                                        	     <a href="#">
                                        	     	  <img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" title="Eliminar Pedido">
                                        	     </a>
                                        	</td><!-- Eliminar -->
                                   </tr>
                            </tbody><!-- Cuerpo -->
                      </table>
                 </div><!-- contenedor -->
             </div><!-- Tabla -->
        <!-- /// Cuerpo pagina /// -->

































    </div>
</div><!-- Contebedorlolo -->
<br>
<br>
<br>
