     <!--
						Css  => tron_modificacion_datos.css
						Js   => tron_modificacion_datos.js
 -->
 <div class="contenedor_principal">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">


         <!-- Titulo -->
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12">
            <h4 class="titulo_principal text-center">
               <strong>ADMINISTRACIÓN DE LOS DATOS DE MI CUENTA</strong><br>
            </h4>
          </div>
        </div>

        <!-- Formulario  -->
        <div>
          <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12">
                <!-- Tabs -->
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#paso1" data-toggle="tab" id="personales"> 1. Datos Personales </a></li>
                    <?php if (  $this->idtipo_plan_compras == 3 ) :?>
                        <li><a href="#paso2" data-toggle="tab" id="cuenta"> 2. Datos de Cuenta </a></li>
                        <li><a href="#paso3" data-toggle="tab" id="direcciones" idtercero = "<?= $this->idtercero ;?>" > 3. Direcciones </a></li>
                     <?php endif ;?>
                </ul>

                <!-- Conten => tabs -->
                <div class="tab-content">
                   <!-- 1. Datos Personales -->
                   <div class="tab-pane fade in active" id="paso1">
                       <?php include (APPLICATION_SECTIONS . 'terceros_modificacion_paso_1.php');?>
                   </div>

                  <?php if (  $this->idtipo_plan_compras == 3 ) :?>
                   <!-- 2. Datos de Cuenta -->
                   <div class="tab-pane fade" id="paso2">
                       <?php include (APPLICATION_SECTIONS . 'terceros_modificacion_paso_2.php');?>
                   </div>

                   <!-- 3. Direcciones -->
                   <div class="tab-pane fade" id="paso3">
                       <?php include (APPLICATION_SECTIONS . 'terceros_modificacion_paso_3.php');?>
                   </div>
                  <?php endif ;?>

               </div>

              <!-- BTN = Atualizar datos -->
              <div class="text-center">
                  <div class="col-lg-12 col-md-12 col-sm-12">
                      <button type="button" id="btn_atualizar_datos" class="btn_atualizar_datos"
                      idtercero           = "<?= $this->idtercero ;?>"
                      idtpidentificacion  = "<?= $this->idtpidentificacion ;?>">Actualizar Datos</button>
                  </div>
              </div>


          </div>
        </div>
        </div>


        </div>
        </div>
        </div>
        <br>
        <br>
        <br>
