<!--
						Css  => tron_modificacion_datos.css
						Js   => tron_modificacion_datos.js
 -->
 <div class="contenedor_principal">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">


         <!-- Titulo -->
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12">
            <h4 class="titulo_principal text-center">
               <strong>Modificacion de Datos</strong><br>
            </h4>
          </div>
        </div>

        <!-- Formulario  -->
        <div>
          <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12">
                <!-- Tabs -->
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#paso1" data-toggle="tab"> Paso 1 </a></li>
                    <li><a href="#paso2" data-toggle="tab"> Paso 2 </a></li>
                    <li><a href="#paso3" data-toggle="tab"> Paso 3 </a></li>
                </ul>

                <!-- Conten => tabs -->
                <div class="tab-content">
                   <!-- Paso 1 -->
                   <div class="tab-pane fade in active" id="paso1">
                       <?php include (APPLICATION_SECTIONS . 'paso1_modificacion_datos.php');?>
                   </div>

                   <!-- Paso 2 -->
                   <div class="tab-pane fade" id="paso2">
                       <?php include (APPLICATION_SECTIONS . 'paso2_modificacion_datos.php');?>
                   </div>

                   <!-- PAso 3 -->
                   <div class="tab-pane fade" id="paso3">
                       <?php include (APPLICATION_SECTIONS . 'paso3_modificacion_datos.php');?>
                   </div>
               </div>
           </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        <br>
        <br>
        <br>
