<!--
   Vista = modificacion_datos_registro.phtml
   Css   = modificacion_datos_registro.css
   Js    = modificacion_datos_registro.js
 -->
<div class="cont_vista_modificaion_datos">
	  <div class="formulario_modificacion">
       <div class="row">
       <!-- titulo -->
         <div class="col-lg-12 col-md-12 col-sm-12">
         	    <div class="text-center">
         	       <h4 class="titulo_modififcacion"><strong>MODIFICACION DE DATOS</strong></h4>
         	    </div>
         </div>
       <!-- Columna Derecha -->
          <div class="col-lg-6 col-md-6 col-sm-6">
               <div>
                   <form class="form-horizontal" role="form">
												         <!-- Codigo presenta -->
												          <div>
												              <div class="form-group">
												                <label for="codigoTerceropresenta-inicial" class="col-lg-6 control-label"><p class="text-label">Código de quien te presenta:</p></label>
												                <div class="col-lg-6">
                               <input type="text" class="form-control" id="codigoTerceropresenta-inicial">
												                </div>
												              </div>
												          </div>
                     <!-- Tipo documento -->
												          <div>
												              <div class="form-group">
												                <label for="Idtpidentificacion" class="col-lg-6 control-label"><p class="text-label">Tipo de documento:</p></label>
												                <div class="col-lg-6">
                               <select class="form-control" id="Idtpidentificacion">
                               	   <option>:: Seleccione ::</option>}
                               	   option
                               </select>
												                </div>
												              </div>
												          </div>
                     <!-- Numero de documento -->
												          <div>
												              <div class="form-group">
												                <label for="Identificacion" class="col-lg-6 control-label"><p class="text-label">Número de documento:</p></label>
												                <div class="col-lg-6">
                               <input type="text" class="form-control" id="Identificacion">
												                </div>
												              </div>
												          </div>
                     <!-- Nombres -->
												          <div>
												              <div class="form-group">
												                <label for="pnombre" class="col-lg-6 control-label"><p class="text-label">Nombres:</p></label>
												                <div class="col-lg-6">
                               <input type="text" class="form-control" id="pnombre">
												                </div>
												              </div>
												          </div>
                     <!-- Apellidos -->
												          <div>
												              <div class="form-group">
												                <label for="papellido" class="col-lg-6 control-label"><p class="text-label">Apellidos:</p></label>
												                <div class="col-lg-6">
                               <input type="text" class="form-control" id="papellido">
												                </div>
												              </div>
												          </div>
                     <!-- Genero -->
												          <div>
												              <div class="form-group">
												                <label for="Genero" class="col-lg-6 control-label"><p class="text-label">Género:</p></label>
												                <div class="col-lg-6">
                               <input type="text" class="form-control" id="Genero">
												                </div>
												              </div>
												          </div>
                   </form>
               </div>
          </div>
        <!--Columna izquierdad -->
          <div class="col-lg-6 col-md-6 col-sm-6">
              <div>
              	 <form class="form-horizontal" role="form">
                     <!-- Departamento -->
												          <div>
												              <div class="form-group">
												                <label for="Iddpto" class="col-lg-6 control-label"><p class="text-label">Departamento:</p></label>
												                <div class="col-lg-6">
                               <input type="text" class="form-control" id="Iddpto">
												                </div>
												              </div>
												          </div>
                     <!-- Municipio -->
												          <div>
												              <div class="form-group">
												                <label for="IdMcpio" class="col-lg-6 control-label"><p class="text-label">Municipio:</p></label>
												                <div class="col-lg-6">
                               <input type="text" class="form-control" id="IdMcpio">
												                </div>
												              </div>
												          </div>
                     <!-- Direccion -->
												          <div>
												              <div class="form-group">
												                <label for="Direccion" class="col-lg-6 control-label"><p class="text-label">Direccion:</p></label>
												                <div class="col-lg-6">
                               <input type="text" class="form-control" id="Direccion">
												                </div>
												              </div>
												          </div>
                     <!-- Barrio -->
												          <div>
												              <div class="form-group">
												                <label for="Barrio" class="col-lg-6 control-label"><p class="text-label">Barrio:</p></label>
												                <div class="col-lg-6">
                               <input type="text" class="form-control" id="Barrio">
												                </div>
												              </div>
												          </div>
                     <!-- Numero de celular -->
												          <div>
												              <div class="form-group">
												                <label for="celular1" class="col-lg-6 control-label"><p class="text-label">Numero de celular:</p></label>
												                <div class="col-lg-6">
                               <input type="text" class="form-control" id="celular1">
												                </div>
												              </div>
												          </div>
                     <!-- Correo electronico -->
												          <div>
												              <div class="form-group">
												                <label for="email" class="col-lg-6 control-label"><p class="text-label">Correo electronico:</p></label>
												                <div class="col-lg-6">
                               <input type="text" class="form-control" id="email">
												                </div>
												              </div>
												          </div>
              	 </form>
              </div>
          </div>
         <!-- BNT = Atualiar Registro -->
         <div>
            <div class="text-center col-lg-12 col-md-12 col-sm-12">
            	    <button type="button" class="btn_actualizar_registro" id="btn_actualizar_registro">Atualizar registro</button>
            </div>
         </div>
       </div>
	  </div>
</div>
<br>
<br>

