<style>
    .panel-heading {background-color: #003E90!important}
    .panel-footer  {background-color: #FFFFFF!important}
}
</style>




<div class="container .content-nuevo-registro">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-primary ">
        <div class="panel-heading">REGISTRO DE NUEVO USUARIO</div>
        <div class="panel-body">

          <form class="form-horizontal" role="form">

            <div class="form-group">
              <label for="codigoterceropresenta" class="col-lg-4 control-label">Código de quien te presenta :</label>
              <div class="col-lg-8">
                <input type="email" class="form-control" id="codigoterceropresenta" placeholder="Deja en blanco si nadie te presenta">
              </div>
            </div>




            <div class="form-group ">
                <div class="">
                  <label for="pnombre" class="col-lg-4 control-label">Tipo Documento :</label>
                  <div>
                    <div class="col-lg-3">
                        <?php include (APPLICATION_SECTIONS . 'terceros/tipos_documentos.php');?>
                    </div>
                    <label for="papellido" class="col-lg-2 control-label">Número :</label>
                    <div class="col-lg-3">
                      <input type="email" class="form-control" id="identificacion" placeholder="Número documento">
                    </div>
                  </div>
                </div>

              </div>



            <div class="persona-natural">
              <div class="form-group ">
                <div class="">
                  <label for="pnombre" class="col-lg-4 control-label">Nombre :</label>
                  <div>

                    <div class="col-lg-3">
                      <input type="email" class="form-control" id="pnombre" placeholder="Nombre">
                    </div>
                    <label for="papellido" class="col-lg-2 control-label">Apellidos :</label>
                    <div class="col-lg-3">
                      <input type="email" class="form-control" id="papellido" placeholder="Nombre">
                    </div>
                  </div>
                </div>

              </div>


              <div class="form-group">
                <label for="genero" class="col-lg-4 control-label">Género : </label>
                <div class="col-lg-8">
                  <select class="form-control" id="genero">
                    <option value="">Seleccione...</option>
                        <option value="1">Masculino</option>
                        <option value="0">Femenino</option>
                  </select>

                </div>
              </div>

<!--
              <div class="form-group ">
                <div class="">
                  <label for="dianacimiento" class="col-lg-4 control-label">Día de nacimiento :</label>
                  <div>

                    <div class="col-lg-3">
                      <select class="form-control" id="dianacimiento">
                        <option>1</option>
                      </select>
                    </div>
                    <label for="mesnacimiento" class="col-lg-2 control-label">Mes :</label>
                    <div class="col-lg-3">
                      <select class="form-control" id="mesnacimiento">
                        <option>1</option>
                      </select>
                    </div>
                  </div>
                </div>

              </div>
-->
            </div>

            <div class="persona-juridica">
              <div class="form-group">
                <label for="razonsocial" class="col-lg-4 control-label">Razón Social : </label>
                <div class="col-lg-8">
                  <input type="email" class="form-control" id="razonsocial" placeholder="Empresa o razón social">

                </div>
              </div>
            </div>

            <div class="form-group">
              <label for="email" class="col-lg-4 control-label">Email : </label>
              <div class="col-lg-8">
                <input type="email" class="form-control" id="email" placeholder="Dirección de correo electrónico">
              </div>
            </div>

            <div class="form-group">
              <label for="passwordusuario" class="col-lg-4 control-label">Contraseña : </label>
              <div class="col-lg-8">
                <input type="email" class="form-control" id="passwordusuario" placeholder="contraseña">
              </div>
            </div>


          </form>


        </div>

        <div class="panel-footer">
          <div class="text-right">
            <button type="button" class="btn btn-success btn-md" id="btn-grabar-datos">Grabar Datos </button>
          </div>
        </div>

      </div> <!-- Fin / panel panel-primary      -->

    </div>    <!-- Fin / Col      -->
  </div>      <!-- Fin / Row      -->
</div>        <!-- Fin / Container      -->
