<!-- Esta vista se carga em administracion de mi cuenta ....  por medio de ajax -->

<div class="contenedor">
    <div class="row">
        <div class="contenedor_plan_selec">
            <!-- /// Cabezera = plan-tron , pases de cortesia /// -->
             <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="banner-cabezera"><!--- Contenedor -->
                    <div class="row">
                      <div class="col-lg-6 col-md-6 col-sm-6"><!-- Plan Empresario Tron -->
                          <div class="cont-img_plan-empresario">
                              <img src="<?= BASE_IMG_EMPRESA ; ?>empresarioI.png" class="img-empresario-tron" /><!-- IMG = Empresario tron -->
                              <p class="text-perteneces-A"> Perteneces al <br> PLAN EMPRESARIO TRON</p><!-- Perteneces -->
                          </div>
                       </div><!-- Plan Empresario Tron -->

                        <div class="col-lg-6 col-md-6 col-sm-6"><!-- Pases de cortesia -->
                              <div class="col-lg-6 col-md-6 col-sm-6">
                                 <a href="#">
                                    <img src="<?= BASE_IMG_EMPRESA ; ?>pases-version2.png"class="img-pases-cortesia" />
                                 </a><!-- IMG = Pases de cortesia -->
                              </div>

                             <div class="text-center col-lg-6 col-md-6 col-sm-6">
                                 <p class="text-center" style="margin-top:  20px;">Entre todos tus usuarios posees 12 Pases de Cortesía.</p>
                                 <a href="#"  id="comprar_pases" class="btn-Enviar-o-comprar" >Enviar o Comprar</a><br>
                                 <a href="<?= BASE_URL ;?>redtron/pases_de_cortesia" class="link-pases-cortesia">¿Qué son los pases de cortesía?</a>
                             </div>
                        </div><!-- Pases de cortesia -->
                    </div>
                </div><!--- Contenedor -->
             </div>
          <!-- /// Cabezera = plan-tron , pases de cortesia /// -->
        </div>
    </div>
</div>
