
<div>

<!-- VEntana modal =  recomendar amigo -->
  <?php include (APPLICATION_SECTIONS . 'modal_img_recomendar.php');?>
<!--  -->
  <?php include (APPLICATION_SECTIONS . 'modal_recomendar_amigo.php');?>
<!-- /// Recomienda el modelo de negocio a un amigo /// -->
   <div class="col-lg-12 col-md-12 col-sm-12">
      <div class="cont-recomendar-negocio"><!-- Contenedor -->
       <div class="row">
      <!-- Titulo -->
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div><!--- Cont-titulo -->

                  <h4 class="text-left titulo-info"> Recomienda el modelo de negocio a un amigo

                     <small>
                        <a href="#modal_img_recomendar"   data-toggle="modal" data-target="#modal_img_recomendar" class="link-editar"><img src="<?= BASE_IMG_EMPRESA ; ?>info.png">
                            <span class="editar"> Info</span> <!-- Editar Informacion -->
                         </a>
                     </small>
                   </h4><!-- Titulo -->
                </div><!--- Cont-titulo -->
            </div>
      <!-- Titulo -->

    <!-- informacion -->
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div>
                <p>
                   Recuerda que al compartir tu URL Única, se relaciona
                   automáticamente a quien la recibe con tu código de
                   usuario permitiendo que sus compras te generen comisiones. </p> <br>

                 <p>
                    <strong>Método 1:</strong>Correo prediseñado
                 </p>

                 <p><!-- Invitacion-tron -->
                    <a href="#"  data-toggle="modal" data-target="#modal_recomendar_amigo">
                        <img src="<?= BASE_IMG_EMPRESA ; ?>enviar.png"> Enviar Invitación de la Red TRON
                    </a>
                 </p><!-- Invitacion-tron -->

                 <p><br />
                     <strong>Método 2:</strong>
                     Copia y pega la siguiente URL en sitios como: Redes sociales, blogs, comunidades o en tu correo electrónico.
                     Url única para referidos. <br /><br />
                      <img src="<?= BASE_IMG_EMPRESA ; ?>enviar.png"> <em> <?= BASE_URL ;?>terceros/referidos/<?= Session::Get('idtercero') ;?>/<?= Session::Get('codigousuario') ;?> </a> </em>
                 </p>

            </div>
        </div>
    <!-- informacion -->
     </div>
     </div><!-- Contenedor -->
   </div>
<!-- /// Recomienda el modelo de negocio a un amigo /// -->

</div>
