<div class="container-registro">
   <div class="row">


      <div class="contenedor-flechas-pasos">
       <!--LLamado flechas superiores -->
           <?php include (APPLICATION_SECTIONS . 'tron_registro_flechas_up.php');?>
       <!--LLamado flechas superiores -->
     </div><br>

               <div class="contenedor-formulario"><!--Contenedor- de  el formulario -->
                 <div class="row formulario">
                  <form class="form-horizontal" role="form">

                    <div class="col-lg-12 col-md-12 col-sm-12"><!--TIpo-Document -->
                      <div class="form-group">
                        <label for="tipo-document" class="col-lg-2  control-label"><p class="text-label text-left">Tipo de Documento :</p></label>
                        <div class="col-lg-10">
                         <select class="form-control" id="tipo-document">
                          <option value="">Vacio</option>
                        </select>
                      </div>

                      <div class="col-lg-12"><!--Mensaje de validacion -->
                        <div class="mjs-valid-d_cumento"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img">  Seleccione un Documento!!</div>
                      </div><!--Mensaje de validacion -->

                    </div>
                  </div><!--TIpo-Document -->

    <!--Campos NIT -->

    <div class="row"><!--Fila -->
      <div class=" col-lg-12 col-md-12 col-sm-12 campos-nit"><!-- Campos NIT-->
        <div class=" col-lg-6"><!--Campos-NIT = Numero-NIT , DV -->

          <div class=" col-lg-8"><!-- Numero nit-->
            <div class="form-group">
              <label for="numero-nit" class="col-lg-6 control-label"><p class="text-label text-left">Número NIT:</p></label>
              <div class="col-lg-6">
               <input type="text" class="form-control" id="numero-nit">
             </div>

             <div class="col-lg-12"><!--Mensaje de validacion -->
                  <div class="mjs-valid-nit"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Campo Vacio !!</div>
             </div><!--Mensaje de validacion -->

           </div>
         </div><!-- Numero nit-->


         <div class=" col-lg-4"><!-- D.V-->
           <div class="form-group">
             <label for="D.V" class="col-lg-1 control-label"><p class="text-label text-left">D.V:</p></label>
             <div class="col-lg-9">
              <input type="text" class="form-control" id="campo-dv">
            </div>

             <div class="col-lg-12"><!--Mensaje de validacion -->
                 <div class="mjs-valid-D-V"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img">  Campo Vacio !!</div>
             </div><!--Mensaje de validacion -->
          </div>
        </div><!-- D.V-->

      </div><!--Campos-NIT = Numero-NIT , DV -->


      <div class=" col-lg-6"><!--Confirmar-NIT = Numero-NIT , D.V -->
        <div class=" col-lg-8"><!-- Confirmar-Numero nit-->
          <div class="form-group">
            <label for="confirmar-numero-nit" class="col-lg-5 control-label"><p class="text-label text-left">Confirmar:</p></label>
            <div class="col-lg-7">
             <input type="text" class="form-control" id="confi-nit" placeholder="Número NIT">
           </div>

            <div class="col-lg-12"><!--Mensaje de validacion -->
                <div class="mjs-valid-Confi-NIT"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img">  Campo Vacio !!</div>
            </div><!--Mensaje de validacion -->
         </div>
       </div><!-- Confirmar-Numero nit-->


       <div class=" col-lg-4"><!--Confirmar- D.V-->
         <div class="form-group">
           <label for="confirmar-dv" class="col-lg-1 control-label"><p class="text-label text-left">D.V</p></label>
           <div class="col-lg-9">
            <input type="text" class="form-control" id="confirmar-dv" placeholder="D.V">
          </div>

           <div class ="col-lg-12"><!--Mensaje de validacion -->
               <div class ="mjs-valid-confi-D-V"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Campo Vacio !!</div>
           </div><!--Mensaje de validacion -->

        </div>
      </div><!-- Confirmar-D.V-->
    </div><!--Confirmar-NIT = Numero-NIT , D.V -->

  </div><!--Campos NIT -->
</div><!--Fila -->

<div class="col-lg-12 col-md-12 col-sm-12 campos-nit"><!--Razón Social -->
 <div class="form-group">
   <label for="razon-social" class="col-lg-2 control-label"><p class="text-label text-left">Razón Social:</p></label>
   <div class="col-lg-10 ">
     <input type="text" class="form-control" id="razon-social">
   </div>

     <div class ="col-lg-12"><!--Mensaje de validacion -->
         <div class ="mjs-valid-nit-razon-scl "><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Campo Vacio !!</div>
     </div><!--Mensaje de validacion -->

 </div>

</div><!--Razón Social -->


<!--Campos NIT -->

             <div class="col-lg-4 col-md-4 col-sm-4"><!--Columan Contiene => numero-documento , nombres , pais -->

               <div class="form-group campos-cedu-ciudadana"><!--Numero-documento -->
                 <label for="numero-document"  class=" col-lg-6 "><p class="text-label text-left">Número Documento:</p></label>
                 <div class="col-lg-6 ">
                   <input type="text" class="form-control" id="numero-docut">
                 </div>

                 <div class ="col-lg-12"><!--Mensaje de validacion -->
                   <div class ="mjs-valid-Num-dcto"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Campo Vacio !!</div>
                 </div><!--Mensaje de validacion -->

               </div><!--Numero-documento -->



               <div class="form-group cedu-ciudad campos-cedu-ciudadana"><!--Nombres -->
                <label for="nombres" class="col-lg-6  control-label"><p class="text-label text-left">Nombres:</p></label>
                <div class="col-lg-6 ">
                 <input type="text" class="form-control" id="nombres">
               </div>

                 <div class ="col-lg-12"><!--Mensaje de validacion -->
                    <div class ="mjs-valid-nombre"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Campo Vacio !!</div>
                </div><!--Mensaje de validacion -->

            </div><!--Nombres -->


            <div class="form-group"><!--País residencia -->
               <label for="pais" class="col-lg-6  control-label"><p class="text-label text-left">País residencia:</p></label>
               <div class="col-lg-6 ">
                 <select  class="form-control" id="pais">
                   <option value="1">Colombia</option>
                 </select>
               </div>

               <div class ="col-lg-12"><!--Mensaje de validacion -->
                  <div class ="mjs-valid-pais"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img">  Seleccione un Pais !!</div>
               </div><!--Mensaje de validacion -->

             </div><!--País residencia -->

            </div><!--Columan Contiene => numero-documento , nombres , pais -->




            <div class="col-lg-4 col-md-4 col-sm-4" id="columna-2"><!--Columan Contine => Confirmar , apellidos , departamento -->

             <div class="form-group campos-cedu-ciudadana"><!--Confirmar -->
               <label for="confirmar-docut" class="col-lg-4 control-label" ><p class="text-label text-left">Confirmar:</p></label>
               <div class="col-lg-8 cont-input">
                <input type="text" class="form-control" placeholder="Número Documento" id="confirmar-docut">
              </div>

              <div class="col-lg-12"><!--Mensaje de validacion -->
                <div class="mjs-valid-confi-num-dcto"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Campo Vacio !!</div>
              </div><!--Mensaje de validacion -->

            </div><!--Confirmar -->


            <div class="form-group campos-cedu-ciudadana"><!--Apellidos -->
             <label for="apellidos" class="col-lg-4  control-label"><p class="text-label text-left">Apellidos:</p></label>
             <div class="col-lg-8 cont-input">
              <input type="text" class="form-control" id="apellidos">
            </div>

            <div class="col-lg-12"><!--Mensaje de validacion -->
             <div class="mjs-valid-apellidos"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Campo Vacio !!</div>
            </div><!--Mensaje de validacion -->

            </div><!--Apellidos -->


            <div class="form-group"><!--Departamento -->
              <label for="departamento" class="col-lg-4  control-label"><p class="text-label text-left">Departamento:</p></label>
              <div class="col-lg-8 cont-input">
                <?php include (APPLICATION_SECTIONS . 'departamentos.php');?>

              </div>

              <div class="col-lg-12"><!--Mensaje de validacion -->
                <div class="mjs-valid-departamento"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Seleccione un Departamento !!</div>
              </div><!--Mensaje de validacion -->

            </div><!--Departamento -->

            </div><!--Columan Contine => Confirmar , apellidos , departamento -->



            <div class="col-lg-4 col-md-4 col-sm-4" id="columna-3"><!--colunma  contiene => genero , municipios -->

             <div class="form-group seleccion-genero campos-cedu-ciudadana"><!--Género -->
               <label for="genero" class="col-lg-4  control-label"><p class="text-label text-left">Género:</p></label>
               <div class="col-lg-8 cont-input">
                <select  class="form-control" id="genero">
                  <option value="">Masculino</option>
                  <option value="">Femenino</option>
                </select>
              </div>

              <div class="col-lg-12"><!--Mensaje de validacion -->
               <div class="mjs-valid-genero"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Seleccione un Genero.</div>
             </div><!--Mensaje de validacion -->

            </div><!--Género -->


            <div class="form-group"><!--Municipio -->
             <label for="municipio" class="col-lg-4  control-label"><p class="text-label text-left">Municipio</p></label>
              <div class="col-lg-8 cont-input">
                <select class="form-control" id="municipio">
                <option value="0">Seleccione una ciudad o municipio</option>
                </select>
              </div>

              <div class="col-lg-12"><!--Mensaje de validacion -->
                 <div class="mjs-valid-municipio"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Seleccione un Municipio.</div>
              </div><!--Mensaje de validacion -->

            </div><!--Municipio -->

            </div><!--colunma  contiene => genero , municipios -->





            <div class="col-lg-12 col-md-12 col-sm-12 columna-5"><!--Dirección residencia -->

             <div class="form-group">
               <label for="direccion" class="col-lg-2 control-label"><p class="text-label text-left">Dirección residencia:</p></label>
               <div class="col-lg-10">
                <input type="text" class="form-control" id="direccion">
              </div>

              <div class="col-lg-12"><!--Mensaje de validacion -->
                <div class="mjs-valid-residencia"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Campo Vacio !!</div>
              </div><!--Mensaje de validacion -->

            </div>
            </div><!--Dirección residencia -->


            <div class="col-lg-6 col-md-6 col-sm-6 columna-6" ><!--Columna contiene => barrio , correo -->

             <div class="form-group"><!-- Barrio-->
               <label for="barrio" class=" col-lg-4 control-label"><p class="text-label text-left">Barrio:</p></label>
               <div class=" col-lg-6">
                <input type="text" class="form-control input-col-6-7" id="barrio">
              </div>

              <div class="col-lg-12"><!--Mensaje de validacion -->
                <div class="mjs-valid-barrio"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Campo Vacio !!</div>
              </div><!--Mensaje de validacion -->

            </div><!-- Barrio-->


            <div class="form-group"><!--Correo Electrónico -->
             <label for="correo" class="col-lg-4 control-label"><p class="text-label text-left">Correo Electrónico:</p></label>
             <div class="col-lg-6">
               <input type="email" class="form-control input-col-6-7" id="correo">
             </div>

             <div class="col-lg-12"><!--Mensaje de validacion -->
              <div class="mjs-valid-correo"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Campo Vacio !!</div>
            </div><!--Mensaje de validacion -->

            </div><!--Correo Electrónico -->

            </div><!--Columna contiene => barrio , correo -->



            <div class="col-lg-6 col-md-6 col-sm-6 columna-7" ><!--Columna contenido => numero celular , confirmar -->

             <div class="form-group"><!--Número Celular -->
               <label for="celular" class="col-lg-6 control-label"><p class="text-label text-left">Número Celular:</p></label>
               <div class="col-lg-6 ">
                <input type="text" class="form-control" id="celular">
              </div>

              <div class="col-lg-12"><!--Mensaje de validacion -->
               <div class="mjs-valid-cel"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Campo Vacio !!</div>
             </div><!--Mensaje de validacion -->

            </div><!--Número Celular -->


            <div class="form-group"><!--Confirmar -->
             <label for="confirmar-correo" class="col-lg-6 control-label"><p class="text-label text-left">Confirmar:</p></label>
             <div class="col-lg-6 ">
              <input type="text" class="form-control input-col-6-7" id="confirmar-correo" placeholder="Correo Electrónico">
            </div>

            <div class="col-lg-12"><!--Mensaje de validacion -->
              <div class="mjs-valid-confi-correo"><img src="<?= BASE_IMG_TIENDA ;?>negativo-rojo.png" class="error-img"> Campo Vacio !!</div>
            </div><!--Mensaje de validacion -->

            </div><!--Confirmar -->

            </div><!--Columna contenido => numero celular , confirmar -->



            <!-- Boton Continuar -->

            <div class="col-lg-12 col-md-12 col-sm-12 col-btn-continuar">
              <div class="cont-btn-continuar">
                <button type="button" id="btn-continuar" class="btn btn-defautl  btn-block btn-continuar"> Continuar </button>
              </div>
            </div>

            <!-- Boton Continuar -->


            </form>


            </div>
            </div><!--Contenedor- de  el formulario -->

   </div>
</div>
<br><br><br><br><br><br>






