<style>
  .panel-heading { background-color: #003E90 !important }
  .panel-footer  { background-color: #FFFFFF !important }
   .modal-header .modal-body {
   padding:0px;
}

</style>


 <?php if ( $this->EXISTE == FALSE ) :?>

  <div class="text-center">
    <br> <br> <br> <h2>
        EL REGISTRO NO SE ENCUENTRA ALMACENADO EN NUESTRO SISTEMA DE INFORMACIÓN
    </h2><br><br><br><br><br><br><br>
  </div>
<?php else :?>


<div class="container .content-nuevo-registro">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-primary ">
        <div class="panel-heading">MODIFICACIÓN DE DATOS REGISTRADOS</div>

        <div class="panel-body">

         <form class="form-horizontal" role="form" id="form-registro">


                <div class="form-group" style="display:none">
                  <label for="codigoterceropresenta" class="col-lg-4 control-label ">Código de quien te presenta :</label>
                  <div class="col-lg-8">
                    <input type="text"  class="form-control" id="codigoterceropresenta" value="<?=$this->codigoterceropresenta ;?>" disabled="disabled">
                  </div>
                </div>
                <div class="alert alert-success alert-dismissable text-center">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                   <strong> Estos son los datos que registraste. Ahora podrás modificarlos.</strong>
                </div>

            <div class="form-group">
              <label  class="col-lg-4 control-label">Quiero registrame como :</label>
              <div class="col-lg-8">

                <label class="radio-inline">
                  <?php   if ( $this->idtipo_plan_compras == 2 ) :?>
                    <input type="radio" name="registro-cliente" id="registro-cliente" checked="checked" >Cliente
                  <?php else :?>
                    <input type="radio" name="registro-cliente" id="registro-cliente" >Cliente
                  <?php endif ;?>
                </label>

                <label class="radio-inline">
                  <?php   if ( $this->idtipo_plan_compras == 3 ) :?>
                    <input type="radio" name="registro-empresario" id="registro-empresario" checked="checked">Empresario TRON
                    <?php else :?>
                      <input type="radio" name="registro-empresario" id="registro-empresario">Empresario TRON
                    <?php endif ;?>
                </label>

              </div>
            </div>



            <div class="form-group ">
              <div class="row">
                <label for="pnombre" class="col-lg-4 control-label">Tipo Documento :</label>
                <div>
                  <div class="col-lg-3">

                    <select class="form-control input_campo_datos" id="idtpidentificacion">
                      <option value="<?=$this->idtpidentificacion;?>"><?= $this->nomtpidentificacion ;?></option>
                      <?php
                      foreach ($this->TiposDocumentos as $Documento) {
                        echo '<option value="'.$Documento['idtpidentificacion'].'">'.   $Documento['nomtpidentificacion'].'</option>';
                      }
                      ?>
                    </select>

                  </div>
                  <label for="identificacion" class="col-lg-2 control-label">Número :</label>
                  <div class="col-lg-3">
                  <input type="text" class="form-control" id="identificacion" placeholder="Número documento" value="<?= $this->identificacion ;?>">
                  </div>
                </div>
              </div>
            </div>




            <div id="persona-natural">
              <div class="form-group ">
                <div class="row">
                  <label for="pnombre" class="col-lg-4 control-label">Nombre :</label>
                  <div>

                    <div class="col-lg-3">
                      <input type="text" class="form-control" id="pnombre" placeholder="Nombre" value = "<?=$this->pnombre ;?>">
                    </div>
                    <label for="papellido" class="col-lg-2 control-label">Apellidos :</label>
                    <div class="col-lg-3">
                      <input type="text" class="form-control" id="papellido" placeholder="Apellido" value ="<?= $this->papellido ;?>">
                    </div>
                  </div>
                </div>

              </div>

              <div id="lblgenero">
                <div class="form-group">
                  <label for="genero" class="col-lg-4 control-label">Género : </label>
                  <div class="col-lg-8">

                    <select class="form-control" id="genero">
                      <option value="<?=$this->genero ;?>"><?= $this->nom_genero ;?></option>
                      <option value="1">Masculino</option>
                      <option value="0">Femenino</option>
                    </select>

                  </div>
                </div>
              </div>

            </div>


            <div id="mes-anio">
              <div class="form-group ">
                <div class="row">
                  <label for="dianacimiento" class="col-lg-4 control-label">Día de nacimiento :</label>
                  <div>

                    <div class="col-lg-3">
                      <select  class="form-control" id="dianacimiento" value="0">
                          <option value="<?= $this->dianacimiento ;?>"><?= $this->dianacimiento  ;?></option>
                        <?php for( $i=1; $i<=31; $i++) : ;?>
                          <option value="<?= $i ;?>"><?= $i ;?></option>
                        <?php endfor ;?>
                      </select>
                    </div>
                    <label for="mesnacimiento" class="col-lg-2 control-label">Mes :</label>
                    <div class="col-lg-3">
                      <select  class="form-control " id="mesnacimiento" tabindex="4" value="0">
                        <option value="<?= $this->mesnacimiento ;?>"><?= $this->nom_mes ;?></option>

                        <option value="1">ENERO</option>
                        <option value="2">FEBRERO</option>
                        <option value="3">MARZO</option>
                        <option value="4">ABRIL</option>
                        <option value="5">MAYO</option>
                        <option value="6">JUNIO</option>
                        <option value="7">JULIO</option>
                        <option value="8">AGOSTO</option>
                        <option value="9">SEPTIEMBRE</option>
                        <option value="10">OCTUBRE</option>
                        <option value="11">NOVIEMBRE</option>
                        <option value="12">DICIEMBRE</option>

                      </select>
                    </div>
                  </div>
                </div>

              </div>

            </div>

            <div id="persona-juridica">
              <div class="form-group">
                <label for="razonsocial" class="col-lg-4 control-label">Razón Social : </label>
                <div class="col-lg-8">
                  <input type="text" class="form-control" id="razonsocial" placeholder="Empresa o razón social" value="<?= $this->razonsocial;?>">

                </div>
              </div>
            </div>

            <div class="form-group">
              <label for="email" class="col-lg-4 control-label">Email : </label>
              <div class="col-lg-8">
                <input type="email" class="form-control" id="email-edit" placeholder="Dirección de correo electrónico" value="<?= $this->email ;?>">
              </div>
            </div>

            <div class="form-group">
              <label for="passwordusuario" class="col-lg-4 control-label">Contraseña : </label>
              <div class="col-lg-8">
                <input type="password" class="form-control" id="passwordusuario" placeholder="contraseña">
                <input type="hidden"   id="idtercero" value="<?= $this->idtercero ;?>">
              </div>
            </div>
          </form>

        </div>

        <div class="panel-footer">

       <div class="text-center" id='img_cargando'>
          <img src="<?= BASE_IMG_EMPRESA ;?>cargando.gif" alt="">
        </div>

          <div class="text-right">
            <button type="button" class="btn btn-success btn-md" id="btn-actualiza-datos">
              <span class="glyphicon glyphicon-floppy-save"></span>
              Actualizar Información </button>
            </div>

        </div>

        </div> <!-- Fin / panel panel-primary      -->

      </div>    <!-- Fin / Col      -->
    </div>      <!-- Fin / Row      -->
  </div>        <!-- Fin / Container      -->

<?php endif ;?>
<!--
<?php //include (VENTANAS_MODALES . 'registro_cliente_bienvenida.php');?>
<?php //include (VENTANAS_MODALES . 'registro_empresario_bienvenida.php');?>
   -->
