<?php Debug::Mostrar( "Registro - Pasoso " ); ?>
<div class="ionix">
    <div class="general pAA30 mb30">
		<div class="row">

            <div class="col-sm-2 col-xs-12 vcenter" style="vertical-align:top;">
            	<?php include (APPLICATION_SECTIONS .'terceros\list_paso_.php');?>
            </div><!--

            --><div class="col-sm-10 col-xs-12 vcenter">

                <article class="rgts_pasos" id="rgts_paso_1">
                	<?php include (APPLICATION_SECTIONS .'terceros\registro_paso_1.php');?>
                </article>

                <!-- Paso 2 -->
                <article class="rgts_pasos" id="rgts_paso_2">
                	<?php include (APPLICATION_SECTIONS .'terceros\registro_paso_2.php');?>
                </article>

                <!-- Paso 3 -->
                <article class="rgts_pasos" id="rgts_paso_3">
                	<?php include (APPLICATION_SECTIONS .'terceros\registro_paso_3.php');?>
                </article>

            </div>

		</div>
    </div>
</div>


