<div class="pAA30">


    <style>
        td, th			{ vertical-align:middle !important; }
    </style>

    <!-- tabla -->
    <table class="table table-bordered table-hover">
        <thead>
            <tr style="border-bottom: 3px solid #003E90;">
                <th width="35%"  colspan="2" rowspan="1" class="taC"><img src="../public/images/empresa/logo.png" width="150" /></th>
                <th class="taC t12" style="background:#fadfdf;">Productos Grupo:</th>
                <th width="20%" class="text-center" style="background:#d7f8fe;" >
                	COMISIONES  POR COMPRAS DE EMPRESARIOS TRON<br />
                    <small>(% sobre venta sin IVA)</small>
                </th>
                <th width="40%" colspan="2" class="taC"  style="background:#fadfdf;">
                	COMISIONES  POR COMPRAS DE CLIENTES TRON <br />
                    <small>(% sobre venta sin IVA)</small>
                </th>
            </tr>
 
 
            <tr style="border-bottom: 3px solid #fff;">
                <td class="taC t12" style="background-color:#eee;"></td>
                <td class="taC t12" style="background:#d7f8fe;">Si has ingresado<br>con tu código<br>de usuario a:</td>
                <td style="background:#fadfdf;"></td>
                <td class="text-center" style="background:#d7f8fe;">COMISIÓN PARA CADA UNO DE LOS EMPRESARIOS HASTA 6 NIVELES SOBRE EL COMPRADOR</td>
                <td class="text-center" style="background:#fadfdf;">COMISIÓN PARA EL EMPRESARIO QUE HACE LA VENTA AL CLIENTE</td>
                <td class="text-center" style="background:#fadfdf;">COMISIÓN PARA EL EMPRESARIO SUPERVISOR DE QUIEN HACE LA VENTA AL CLIENTE</td>
            </tr>
        </thead>

        <tbody>
            <?php $Primer_Registro  = TRUE ;?>
            <?php $Segundo_Registro = TRUE ;?>
            <?php $Ultimo_Registro = FALSE ;?>
		<?php
            $ggg = 1;
            foreach ($this->Comisiones_Grupos as $Comisiones)  :

                $codigo_grupo          = $Comisiones['codigo_grupo'];
                $comis_empre_1_unidad  = number_format ( $Comisiones['comis_empre_1_unidad'],1,',','.').'%';
                $comis_empre_escala_a  = number_format ($Comisiones['comis_empre_escala_a'],1,',','.').'%';
                $comis_empre_escala_b  = number_format ($Comisiones['comis_empre_escala_b'],1,',','.').'%';
                $comis_empre_escala_c  = number_format ($Comisiones['comis_empre_escala_c'],1,',','.').'%';

                $comis_amg_n1_unidad   = number_format ($Comisiones['comis_amg_n1_unidad'],1,',','.').'%';
                $comis_amg_n1_escala_a = number_format ($Comisiones['comis_amg_n1_escala_a'],1,',','.').'%';
                $comis_amg_n1_escala_b = number_format ($Comisiones['comis_amg_n1_escala_b'],1,',','.').'%';
                $comis_amg_n1_escala_c = number_format ($Comisiones['comis_amg_n1_escala_c'],1,',','.').'%';

                $comis_amg_n2_unidad   = number_format ($Comisiones['comis_amg_n2_unidad'],1,',','.').'%';
                $comis_amg_n2_escala_a = number_format ($Comisiones['comis_amg_n2_escala_a'],1,',','.').'%';
                $comis_amg_n2_escala_b = number_format ($Comisiones['comis_amg_n2_escala_b'],1,',','.').'%';
                $comis_amg_n2_escala_c = number_format ($Comisiones['comis_amg_n2_escala_c'],1,',','.').'%';

                if ( $Primer_Registro == TRUE) :
        ?>
                <!-- Grupo A -->
                <tr>
                    <td rowspan="3">TRON Hogar y Automotríz</td>
                    <td class="t12" style="background:#d7f8fe;">0 - 1 Empresarios</td>
                    <td style="background:#fadfdf;">
                    	<center>
                    	<div style="background:url(../public/images/productos/23.png) center center no-repeat; width:44px; height:44px; background-size:44px auto; color:#FFF;" class="tab">
                        	<div class="tabIn">
                            	<strong><?= $codigo_grupo  ;?></strong>
                        	</div>
                        </div>
                        </center>
                    </td>
                    <td class="text-center" style="background:#d7f8fe;"> <?= $comis_empre_1_unidad  ;?> </td>
                    <td class="text-center" style="background:#fadfdf;"> <?= $comis_amg_n1_unidad ;?>  </td>
                    <td class="text-center" style="background:#fadfdf;"> <?= $comis_amg_n2_unidad  ;?>  </td>
                </tr>
                <tr>
                    <td class="t12" style="background:#d7f8fe;">2 - 3 Empresarios</td>
                    <td style="background:#fadfdf;">
                    	<center>
                    	<div style="background:url(../public/images/productos/23.png) center center no-repeat; width:44px; height:44px; background-size:44px auto; color:#FFF;" class="tab">
                        	<div class="tabIn">
                            	<strong><?= $codigo_grupo  ;?></strong>
                        	</div>
                        </div>
                        </center>
                    </td>
                    <td class="text-center" style="background:#d7f8fe;"> <?= $comis_empre_1_unidad  ;?> </td>
                    <td class="text-center" style="background:#fadfdf;"> <?= $comis_amg_n1_unidad ;?>  </td>
                    <td class="text-center" style="background:#fadfdf;"> <?= $comis_amg_n2_unidad  ;?>  </td>
                </tr>
                <tr>
                    <td class="t12" style="background:#d7f8fe;">4 o más Empresarios</td>
                    <td style="background:#fadfdf;">
                    	<center>
                    	<div style="background:url(../public/images/productos/23.png) center center no-repeat; width:44px; height:44px; background-size:44px auto; color:#FFF;" class="tab">
                        	<div class="tabIn">
                            	<strong><?= $codigo_grupo  ;?></strong>
                        	</div>
                        </div>
                        </center>
                    </td>
                    <td class="text-center" style="background:#d7f8fe;"> <?= $comis_empre_1_unidad  ;?> </td>
                    <td class="text-center" style="background:#fadfdf;"> <?= $comis_amg_n1_unidad ;?>  </td>
                    <td class="text-center" style="background:#fadfdf;"> <?= $comis_amg_n2_unidad  ;?>  </td>
                    <?php $Primer_Registro = FALSE ;?>
                </tr>

            <!-- Grupo B =>  PP -->
            <?php elseif ( $Segundo_Registro == TRUE) :?>

                <tr>
                    <td colspan="2">Línea Industrial
                        <?php $Segundo_Registro = FALSE ;?>
                    </td>
                    <td style="background:#fadfdf;">
                    	<center>
                    	<div style="background:url(../public/images/productos/23.png) center center no-repeat; width:44px; height:44px; background-size:44px auto; color:#FFF;" class="tab">
                        	<div class="tabIn">
                            	<strong>B</strong>
                        	</div>
                        </div>
                        </center>
                    </td>
                    <td class="taC" style="background:#d7f8fe;"><?= $comis_empre_1_unidad  ;?> </td>
                    <td class="taC" style="background:#fadfdf;"><?= $comis_amg_n1_unidad ;?></td>
                    <td class="taC" style="background:#fadfdf;"> <?= $comis_amg_n2_unidad  ;?> </td>
                </tr>

            <?php else : ?>
            <?php if ( $codigo_grupo != 'PP') :?>
                <tr>
                    <?php if($ggg <2){ ?>
                        <td rowspan="8" colspan="2">Otros productos</td>
                    <?php } ?>
                    <td style="background:#fadfdf;">
                    	<center>
                        <div style="background:url(../public/images/productos/23.png) center center no-repeat; width:44px; height:44px; background-size:44px auto; color:#FFF;" class="tab">
                        	<div class="tabIn">
                            	<strong><?= $codigo_grupo  ;?></strong>
                        	</div>
                        </div>
                        </center>
                    </td>
                    <td class="text-center" style="background:#d7f8fe;"> <?= $comis_empre_1_unidad  ;?> </td>
                    <td class="text-center" style="background:#fadfdf;"> <?= $comis_amg_n1_unidad  ;?> </td>
                    <td class="text-center" style="background:#fadfdf;"> <?= $comis_amg_n2_unidad  ;?> </td>
                </tr>
            <?php else : ?>

                <tr>
					<td colspan="2">Productos Promocionales</td>
                    <td style="background:#fadfdf;">
                    	<center>
                    	<div style="background:url(../public/images/productos/23.png) center center no-repeat; width:44px; height:44px; background-size:44px auto; color:#FFF;" class="tab">
                        	<div class="tabIn">
                            	<strong><?= $codigo_grupo  ;?></strong>
                        	</div>
                        </div>
                        </center>
                    </td>

                    <td class="text-center" style="background:#d7f8fe;"> <?= $comis_empre_1_unidad  ;?> </td>
                    <td class="text-center" style="background:#fadfdf;"> <?= $comis_amg_n1_unidad  ;?> </td>
                    <td class="text-center" style="background:#fadfdf;"> <?= $comis_amg_n2_unidad  ;?> </td>
                </tr>
            <?php endif;?>

            <?php $ggg++; endif; ?>


        <?php endforeach ;?>

        </tbody>
    </table>




</div>

