<div class="pAA30">

    <div class="taba_tabla">
        <div class="tabla_tab1">
            COMISIONES POR COMPRAS AMIGOS DEL PLAN EMPRESARIO TRON  ( % sobre venta sin IVA ).
        </div>
        <div class="tabla_tab2"><br>
            COMISIONES POR COMPRAS AMIGOS DEL PLAN CLIENTES TRON ( % sobre venta sin IVA).
        </div>
    </div>
    <br /><br />
    <style>
        td, th			{ vertical-align:middle !important; }
    </style>
    
    <!-- tabla -->
    <table class="table table-bordered table-hover">
        <thead>
            <tr style="border-bottom: 3px solid #003E90;">
                <th>ION</th>
                <th class="text-center">GRUPO</th>
                <th class="text-center">COMISIONES PARA EL EMPRESARIO EN RED CON EL COMPRADOR</th>
                <th class="text-center">COMISIONES PARA EL EMPRESARIO QUE LO PRESENTÓ</th>
                <th class="text-center">COMISIONES PARA QUIEN PRESENTÓ AL EMPRESARIO</th>
            </tr>
            <tr style="border-bottom: 3px solid #003E90;">
                <th>ION</th>
                <th class="text-center">GRUPO</th>
                <th class="text-center">COMISIONES PARA EL EMPRESARIO EN RED CON EL COMPRADOR</th>
                <th class="text-center">COMISIONES PARA EL EMPRESARIO QUE LO PRESENTÓ</th>
                <th class="text-center">COMISIONES PARA QUIEN PRESENTÓ AL EMPRESARIO</th>
            </tr>
        </thead>
    
        <tbody>
            <?php $Primer_Registro  = TRUE ;?>
            <?php $Segundo_Registro = TRUE ;?>
		<?php
            $ggg = 1;
            foreach ($this->Comisiones_Grupos as $Comisiones)  : 
        
                $codigo_grupo          = $Comisiones['codigo_grupo'];
                $comis_empre_1_unidad  = number_format ( $Comisiones['comis_empre_1_unidad'],3).'%';
                $comis_empre_escala_a  = number_format ($Comisiones['comis_empre_escala_a'],3).'%';
                $comis_empre_escala_b  = number_format ($Comisiones['comis_empre_escala_b'],3).'%';
                $comis_empre_escala_c  = number_format ($Comisiones['comis_empre_escala_c'],3).'%';
                
                $comis_amg_n1_unidad   = number_format ($Comisiones['comis_amg_n1_unidad'],3).'%';
                $comis_amg_n1_escala_a = number_format ($Comisiones['comis_amg_n1_escala_a'],3).'%';
                $comis_amg_n1_escala_b = number_format ($Comisiones['comis_amg_n1_escala_b'],3).'%';
                $comis_amg_n1_escala_c = number_format ($Comisiones['comis_amg_n1_escala_c'],3).'%';
                
                $comis_amg_n2_unidad   = number_format ($Comisiones['comis_amg_n2_unidad'],3).'%';
                $comis_amg_n2_escala_a = number_format ($Comisiones['comis_amg_n2_escala_a'],3).'%';
                $comis_amg_n2_escala_b = number_format ($Comisiones['comis_amg_n2_escala_b'],3).'%';
                $comis_amg_n2_escala_c = number_format ($Comisiones['comis_amg_n2_escala_c'],3).'%';
                
                if ( $Primer_Registro == TRUE) :
        ?>
                <!-- Grupo A -->
                <tr>
                    <td>Tron Hogar</td>
                    <td class="text-center" > <?= $codigo_grupo  ;?> </td>
                    <td class="text-center" style="background:#d7f8fe;"> <?= $comis_empre_1_unidad  ;?> </td>
                    <td class="text-center" style="background:#fadfdf;"> <?= $comis_amg_n1_unidad ;?>  </td>
                    <td class="text-center" style="background:#ccc;"> <?= $comis_amg_n2_unidad  ;?>  </td>
                    <?php $Primer_Registro = FALSE ;?>
                </tr>
    
            <!-- Grupo B =>  PP -->
            <?php elseif ( $Segundo_Registro == TRUE) :?>
    
                <tr>
                    <td>Industrial &nbsp; <img src="<?= BASE_IMG_EMPRESA ;?>tecnologias.png">
                        <?php $Segundo_Registro = FALSE ;?>
                    </td>
                    <td class="text-center" >B</td>
                    <td class="taC" style="background:#d7f8fe;">Industrial</td>
                    <td class="taC" style="background:#fadfdf;">Industrial</td>
                    <td class="taC" style="background:#ccc;">Industrial</td>
                </tr>
    
            <?php else : ?>
    
                <tr>
                    <?php if($ggg <2){ ?>
                        <td rowspan="9">Otros productos</td>
                    <?php } ?>
                    <td class="text-center"> <?= $codigo_grupo  ;?> </td>
                    <td class="text-center" style="background:#d7f8fe;"> <?= $comis_empre_1_unidad  ;?> </td>
                    <td class="text-center" style="background:#fadfdf;"> <?= $comis_amg_n1_unidad  ;?> </td>
                    <td class="text-center" style="background:#ccc;"> <?= $comis_amg_n2_unidad  ;?> </td>
                </tr>
            
            <?php $ggg++; endif; ?>
    
            
        <?php endforeach ;?>
        
        </tbody>
    </table>
        
    
    <div class="definicion_colores_tabla tab">
       <div class="tab30 p10 mb5 rr5" style="background:#d7f8fe;"><span class="color color3"></span><span class="defi_color"> COMISIONES PARA EL EMPRESARIO EN RED CON EL COMPRADOR.</span></div>
       <div class="tab5"></div>
       <div class="tab30 p10 mb5 rr5" style="background:#fadfdf;"><span class="color color4"></span><span class="defi_color"> COMISIONES PARA EL EMPRESARIO QUE LO PRESENTO.</span></div>
       <div class="tab5"></div>
       <div class="tab30 p10 mb5 rr5" style="background:#ccc;"><span class="color color5"></span><span class="defi_color"> COMISIONES PARA QUIEN PRESENTO AL EMPRESARIO.</span></div>
    </div>

</div>

