<div class="tabla_tron">
	   <div class="row">
	      <div class="well col-lg-2 col-md-2 col-sm-2"></div>
        <!-- columan superrior -->
        <div class="col-lg-9 col-md-9 col-sm-9">
          <div >
        	   <div style="background: #CAE8F2;" class="col-lg-6 col-md-6 col-sm-6 text-center">
        	   	  	<p>COMISIONES POR COMPRAS AMIGOS DEL PLAN <br> EMPRESARIO TRON  ( % sobre venta sin IVA ).</p>
        	   </div>
          </div>

          <div>
        	   <div style="background:#CDCBCE;" class="col-lg-6 col-md-6 col-sm-6 text-center">
        	   	  	<p>COMISIONES POR COMRPAS AMIGOS DEL PLAN CLIENTES TRON <br> ( % sobre venta sin IVA).</p>
        	   </div>
          </div>

         <!-- divison columan X 3 -->
         <div style="background:#EAF9FE;" class="col-lg-4 col-md-4 col-sm-4 text-center">
         	  <p>COMISIONES PARA EL EMPRESARIO EN RED CON EL COMPRADOR </p><br>
         </div>

         <div style="background:#FAF8FB;"class="col-lg-4 col-md-4 col-sm-4 text-center">
         	  <p>COMISIONES PARA EL EMPRESARIO QUE LO PRESENTO</p><br>
         </div>

         <div style="background:#EFEDF0;" class="col-lg-4 col-md-4 col-sm-4 text-center">
         	  <p>COMISIONES PARA QUIEN PRESENTO AL EMPRESARIO</p><br>
         </div>

        <table class="table table-bordered">
        	    <thead>
        	    	   <tr>
            				<th style="background:#CAE8F2;">Grupo</th>
            				<th class="table_tron_cabezera">1 UNID</th>
            				<th class="table_tron_cabezera">Escala A</th>
            				<th class="table_tron_cabezera">Escala B</th>
            				<th class="table_tron_cabezera">Escala C</th>
            				<th class="table_tron_cabezera">1 UNID</th>
            				<th class="table_tron_cabezera">Escala A</th>
            				<th class="table_tron_cabezera">Escala B</th>
            				<th class="table_tron_cabezera">Escala C</th>
            				<th class="table_tron_cabezera">1 UNID</th>
            				<th class="table_tron_cabezera">Escala A</th>
            				<th class="table_tron_cabezera">Escala B</th>
            				<th class="table_tron_cabezera">Escala C</th>
        	    	   </tr>
        	    </thead>

        	    <tbody>
<!--         	    	   <tr>
																					<td>IMG</td>
																					<td rowspan="3">fffff</td>

																					<td></td>
																					<td></td>
																					<td></td>
																					<td></td>
																					<td></td>
																					<td></td>
																					<td></td>
																					<td></td>
																					<td></td>
        	    	   </tr> -->
        	    </tbody>
        </table>













        </div>
	   </div>
</div>

<style>

</style>
