<div class="tabla_tron"><br><br><br>
	   <div class="row contenedor_tabla_comisiones">
      <!-- Columna Sectiones de la tabla -->
       <div class="col-lg-2 col-md-2 col-sm-2 sectiones_tabla">
           <!-- section hogar -->
          <div>
            <div class="section_hogar">
                <!-- logo -->
                <div class="bloques_img_hogar">
                   <img src= "<?= BASE_IMG_EMPRESA ; ?>logo.png" class="img_section_hogar">
                </div>
                <!-- text = hogar -->
                <div class="bloques_img_hogar">
                   <h5 class="columna_left_text text-left"><strong>HOGAR</strong></h5>
                </div>
           </div>
          </div>
          <!-- section industrial -->
          <div>
              <div class="section_industrial">
                <!-- text -->
                <div class="bloques_img_industrial">
                   <h5 class="columna_left_text text-left"><strong>INDUSTRAL</strong></h5>
                </div>
                <!-- img -->
                <div class="bloques_img_industrial">
                     <img src="<?= BASE_IMG_EMPRESA ;?>tecnologias.png" class="img-responsive img-tecno_aplicds">
                </div>
              </div>
          </div>
          <!-- section otros productos -->
          <div>
               <div class="section_otros_productos">
                <div class="text_otros_product"><br><br><br>
                   <h5 class="columna_left_text text-left"><strong>OTROS PRODUCTOS</strong></h5>
                </div>
               </div>
          </div>
          <!-- section prodcutos promocionales -->
          <div>
              <div class="section_promocionales">
                <div class="text_otros_product">
                   <h5 class="columna_left_text text-left"><strong>PRODUCTOS PROMOCIONALES</strong></h5>
                </div>
              </div>
          </div>
       </div>



        <div class="col-lg-9 col-md-9 col-sm-9" style="padding: 0px;">

          <!-- Tabs -->
          <div class="taba_tabla">
              <div class="tabla_tab1">
                 COMISIONES POR COMPRAS AMIGOS DEL PLAN EMPRESARIO TRON  ( % sobre venta sin IVA ).
              </div>
              <div class="tabla_tab2"><br>
                  COMISIONES POR COMPRAS AMIGOS DEL PLAN CLIENTES   TRON  <br>( % sobre venta sin IVA).
              </div>
          </div>

        <!-- tabla -->
        <table class="table table-bordered">
        	    <thead style="font-size: 11.5px;">
        	    	   <tr>
            				<th class="text-center" style="border-bottom: 3px solid #003E90;">Grupo</th>
            				<th class="text-center" style="background: #FFFFDF; border-bottom: 3px solid #003E90;">1 UNID </th>
            				<th class="text-center" style="background: #FFFFDF; border-bottom: 3px solid #003E90;">1 UNID</th>
            				<th class="text-center" style="background: #FFFFDF; border-bottom: 3px solid #003E90;">1 UNID</th>
        	    	   </tr>
        	    </thead>

        	    <tbody>
              <?php $Primer_Registro = TRUE ;?>
              <?php foreach ($this->Comisiones_Grupos as $Comisiones)  : ; ?>
                <?php
                    $codigo_grupo          = $Comisiones['codigo_grupo'];
                    $comis_empre_1_unidad  = number_format ( $Comisiones['comis_empre_1_unidad'],3).'%';
                    $comis_empre_escala_a  = number_format ($Comisiones['comis_empre_escala_a'],3).'%';
                    $comis_empre_escala_b  = number_format ($Comisiones['comis_empre_escala_b'],3).'%';
                    $comis_empre_escala_c  = number_format ($Comisiones['comis_empre_escala_c'],3).'%';

                    $comis_amg_n1_unidad   = number_format ($Comisiones['comis_amg_n1_unidad'],3).'%';
                    $comis_amg_n1_escala_a = number_format ($Comisiones['comis_amg_n1_escala_a'],3).'%';
                    $comis_amg_n1_escala_b = number_format ($Comisiones['comis_amg_n1_escala_b'],3).'%';
                    $comis_amg_n1_escala_c = number_format ($Comisiones['comis_amg_n1_escala_c'],3).'%';

                    $comis_amg_n2_unidad   = number_format ($Comisiones['comis_amg_n2_unidad'],3).'%';
                    $comis_amg_n2_escala_a = number_format ($Comisiones['comis_amg_n2_escala_a'],3).'%';
                    $comis_amg_n2_escala_b = number_format ($Comisiones['comis_amg_n2_escala_b'],3).'%';
                    $comis_amg_n2_escala_c = number_format ($Comisiones['comis_amg_n2_escala_c'],3).'%';
                ?>
                  <?php if ( $Primer_Registro == TRUE) :?>
                    <!-- Grupo A -->
                      <tr style="font-size: 11.5px;">
                				<td class="text-center" > <?= $codigo_grupo  ;?> </td>
                				<td class="text-center" style="background: #8BDEED;"> <?= $comis_empre_1_unidad  ;?> </td>
                				<td class="text-center" style="background: #FFA0A0;"> <?= $comis_amg_n1_unidad ;?>  </td>
                				<td class="text-center" style="background: #EEEEEE;"> <?= $comis_amg_n2_unidad  ;?>  </td>
                        <?php $Primer_Registro = FALSE ;?>
            	        </tr>
                    <?php else : ?>
                     <!-- Grupo B =>  PP -->
                      <tr style="font-size: 11.5px;">
                        <td class="text-center"> <?= $codigo_grupo  ;?> </td>
                        <td class="text-center" style="background: #8BDEED;"> <?= $comis_empre_1_unidad  ;?> </td>
                        <td class="text-center" style="background: #FFA0A0;"> <?= $comis_amg_n1_unidad  ;?> </td>
                        <td class="text-center" style="background: #EEEEEE;"> <?= $comis_amg_n2_unidad  ;?> </td>
                    </tr>

                  <?php endif;?>
        	    </tbody>
              <?php endforeach ;?>
        </table>
        </div>
        <!-- definicionde colores -->
       <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="definicion_colores_tabla">
           <div><span class="color color3"></span><span class="defi_color"> COMISIONES PARA EL EMPRESARIO EN RED CON EL COMPRADOR.</span></div>
           <div><span class="color color4"></span><span class="defi_color"> COMISIONES PARA EL EMPRESARIO QUE LO PRESENTO.</span></div>
           <div><span class="color color5"></span><span class="defi_color"> COMISIONES PARA QUIEN PRESENTO AL EMPRESARIO.</span></div>
        </div>
       </div>
	   </div>
</div>

