 <div class="conte_transferencias">
 	   <div class="row">
 	   	   <div class="col-lg-12 col-md-12 col-sm-12">
 	   	   	   <!-- Titulo -->
 	   	   	   <div>
 	   	   	   	    <div class="col-lg-12 col-md-12 col-sm-12">
 	   	   	   	    	  <h4 class="text-center titulo_transferencia">Transferencia de comisiones y puntos <br> entre codigos</h4><br>
 	   	   	   	    </div>
 	   	   	   </div>

             <!-- Formulario -->
             <div>
             	   <div class="form-horizontal" role="form">
                      <!-- columna left -->
                      <div>
                      	   <div class="col-lg-6 col-md-6 col-sm-6">
																			        <!-- Codigo de origen -->
																			          <div>
																			              <div class="form-group">
																			                <label for="codigo_origen"  class="col-lg-5  control-label"><p class="text-label">Codigo de origen:</p></label>
																			                <div class="col-lg-7">
																			                    <select class="form-control" id="codigo_origen">
																			                    	   <option value="">SELECCIONE</option>
																			                    </select>
																			                </div>
																			              </div>
																			          </div>

																			        <!-- Saldo comi -->
																			          <div>
																			              <div class="form-group">
																			                <label for="saldo_comisiones"   class="col-lg-5  control-label"><p class="text-label">Saldo comisiones:</p></label>
																			                <div class="col-lg-7">
																			                    <input type="text" class="form-control" id="saldo_comisiones">
																			                </div>
																			              </div>
																			          </div>

																			        <!-- Slado puntos -->
																			          <div>
																			              <div class="form-group">
																			                <label for="saldo_puntos"   class="col-lg-5  control-label"><p class="text-label">Slado puntos:</p></label>
																			                <div class="col-lg-7">
																			                    <input type="text" class="form-control" id="saldo_puntos">
																			                </div>
																			              </div>
																			          </div>
                      	   </div>

                      <!-- columna right -->
                      <div>
                      	   <div class="col-lg-6 col-md-6 col-sm-6">
																			        <!-- Codigo destinario -->
																			          <div>
																			              <div class="form-group">
																			                <label for="codigo_destinario"   class="col-lg-5  control-label"><p class="text-label">Codigo destinario:</p></label>
																			                <div class="col-lg-7">
																			                    <select class="form-control" id="codigo_destinario">
																			                    	   <option value="">SELECCIONE</option>
																			                    </select>
																			                </div>
																			              </div>
																			          </div>

																			        <!-- Transferencia -->
																			          <div>
																			              <div class="form-group">
																			                <label for="transferencia1"   class="col-lg-5  control-label"><p class="text-label">Transferencia:</p></label>
																			                <div class="col-lg-7">
																			                    <input type="text" class="form-control" id="transferencia1">
																			                </div>
																			              </div>
																			          </div>

																			        <!-- Trnasferencia -->
																			          <div>
																			              <div class="form-group">
																			                <label for="transferencia2"   class="col-lg-5  control-label"><p class="text-label">Trnasferencia:</p></label>
																			                <div class="col-lg-7">
																			                    <input type="text" class="form-control" id="transferencia2">
																			                </div>
																			              </div>
																			          </div>
                      	   </div>
                      </div>
                      </div>
                       <!-- btn = Realizar Transferencia -->
                       <div clasS="text-center">
                       	   <div class="col-lg-12 col-md-12 col-sm-12">
                       	   	   <button type="button" class="btn_realizar_transferencia" id="">Realizar Transferencia</button>
                       	   </div>
                       </div>
             	   </div>
             </div>
 	   	   </div>
 	   </div>
 </div>
<br>
<br>
<br>
