<?php
    if ( !isset($_SESSION['carrito'] )) {
      echo "<br><br><h1> AGREGUE PRODUCTOS AL CARRO PARA REALIZAR LAS VERIFICACIONES </h1><br><br><br><br>";
      exit;
    }
?>

<?php
  $carro = $_SESSION['carrito'] ;
?>


<div class="row" style ='padding-top : 150px ;'>
        <div class="col-lg-12 col-md-12 col-sm-12">
<table class="table table-bordered table-hover">
                   <thead><!-- Cabezera tabla -->
                       <tr>
                            PRODUCTOS Y VALORES

                            <th class="titulo-tabla">Producto</th>
                            <th class="titulo-tabla">Presen.</th>
                            <th class="titulo-tabla">Frag.</th>
                            <th class="titulo-tabla">Cant.</th>
                            <th class="titulo-tabla">Peso(gr)</th>
                            <th class="titulo-tabla">Peso Tot.</th>
                            <th class="titulo-tabla">Iva</th>
                            <th class="titulo-tabla">Grupo</th>
                            <th class="titulo-tabla">$ Vr.Unit</th>
                            <th class="titulo-tabla">$ Vta.Total</th>
                            <th class="titulo-tabla">$ Declarado</th>
                            <th class="titulo-tabla">% Sub.Flete</th>
                            <th class="titulo-tabla">$ Vr.Sub.Flete</th>
                            <th class="titulo-tabla">$ Vr.Ant.Rcdo</th>

                       </tr>
                   </thead>

                   <tbody><!-- Cuerpo -->
                   <?php
                      $_peso_gramos_total          = 0;
                      $_precio_total_produc_pedido = 0;
                      $_valor_declarado            = 0;
                      $_vr_ppto_fletes             = 0;
                      $_vr_anticipo_recaudo        = 0;
                   ?>
                   	<?php foreach ($carro as $productos) :?>
                       <tr>
                           <td class="cuerpo-tabla"><?= $productos['nom_producto'] ;?>  </td>
                           <td class="cuerpo-tabla"><?= $productos['nompresentacion'] ;?>  </td>
                           <td class="cuerpo-tabla"><?= $productos['fragancia'] ;?>  </td>
                           <td class="cuerpo-tabla"><?= $productos['cantidad'] ;?>  </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['peso_gramos']) ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['peso_gramos_total'] ) ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['iva']  )."%" ;?> </td>
                           <td class="cuerpo-tabla"><?=  $productos['codigo_grupo'] ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['precio_unitario_produc_pedido']) ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['precio_total_produc_pedido'] ) ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['valor_declarado'] ) ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['ppto_fletes']*100 )."%" ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['vr_ppto_fletes'] ) ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['vr_anticipo_recaudo'] ) ;?> </td>
                           <?php
                              $_peso_gramos_total          = $_peso_gramos_total          + $productos['peso_gramos_total'] ;
                              $_precio_total_produc_pedido = $_precio_total_produc_pedido + $productos['precio_total_produc_pedido'];
                              $_valor_declarado            = $_valor_declarado            + $productos['valor_declarado'];
                              $_vr_ppto_fletes             = $_vr_ppto_fletes             + $productos['vr_ppto_fletes'];
                              $_vr_anticipo_recaudo        = $_vr_anticipo_recaudo        + $productos['vr_anticipo_recaudo'];
                            ?>
                       </tr>
										<?php endforeach ;?>
                    <tr>
                        <th class="titulo-tabla" colspan="5"></th>
                        <th class="titulo-tabla"><?= number_format($_peso_gramos_total) ;?> </th>
                        <th class="titulo-tabla" colspan="3"></th>
                        <th class="titulo-tabla"><?= number_format($_precio_total_produc_pedido) ;?></th>
                        <th class="titulo-tabla"><?= number_format($_valor_declarado) ;?> </th>
                        <th class="titulo-tabla"></th>
                        <th class="titulo-tabla"><?= number_format($_vr_ppto_fletes) ;?> </th>
                        <th class="titulo-tabla"><?= number_format($_vr_anticipo_recaudo) ;?></th>
                    </tr>

                   </tbody>
              </table>
</div>
</div>

<table class="table table-bordered table-hover" style ="width : 50%;">
   <thead><!-- Cabezera tabla -->
       <tr>
            <th class="titulo-tabla" colspan="3">REDETRANS</th>
            <th class="titulo-tabla" colspan="3">SERVIENTREGA</th>
       </tr>
       <tr>
          <th class="titulo-tabla"></th>
          <th class="titulo-tabla">COURRIER</th>
          <th class="titulo-tabla">CARGA</th>
          <th class="titulo-tabla">PREMIER</th>
          <th class="titulo-tabla">INDUSTRIAL</th>
       </tr>
       <tr>
          <th class="titulo-tabla">Vr. Flete</th>
          <th> <?= number_format(Session::Get('REDETRANS_COURRIER_flete'));?>  </th>
          <th> <?= number_format(Session::Get('REDETRANS_CARGA_valor_flete'));?>  </th>
          <th> <?= number_format(Session::Get('SERVIENTREGA_PREMIER_valor_flete'));?>  </th>
          <th> <?= number_format(Session::Get('SERVIENTREGA_INDUS_valor_flete'));?>  </th>
       </tr>
       <tr>
          <th class="titulo-tabla">Vr. Seguro</th>
          <th> <?=  number_format(Session::Get('REDETRANS_COURRIER_seguro')) ;?></th>
          <th> <?=  number_format(Session::Get('REDETRANS_CARGA_seguro')) ;?></th>
          <th> <?= number_format(Session::Get('SERVIENTREGA_PREMIER_seguro'));?>  </th>
          <th> <?= number_format(Session::Get('SERVIENTREGA_INDUS_seguro'));?>  </th>
       </tr>

       <tr>
          <th class="titulo-tabla">Flete Total</th>
          <th> <?= number_format( Session::Get('REDETRANS_COURRIER_flete_total')) ;?> </th>
          <th> <?= number_format( Session::Get('REDETRANS_CARGA_flete_total')) ;?> </th>
          <th> <?= number_format(Session::Get('SERVIENTREGA_PREMIER_flete_total'));?>  </th>
          <th> <?= number_format(Session::Get('SERVIENTREGA_INDUS_flete_total'));?>  </th>
       </tr>
   </thead>
</table>




FLETES Y VALORES ..... CIUDAD DE DESTINO : <strong><?= Session::Get('nommcipio_despacho') ;?></strong><br>
TIPO DE DESPACHO SELECCIONADO :            <strong><?=   Session::Get('tipo_tarifa'); ?></strong><br>
CANTIDAD DE UNIDADES DE DESPACHO :         <strong><?=   Session::Get('Cant_Unidades_Despacho'); ?></strong><br>


<br>
<table class="table table-bordered table-hover" style ="width : 50%;">
  <thead>
    <tr>
      <th>TOTALES</th>
      <th> </th>
    </tr>
  </thead>
  <tr> <th>VALOR TOTAL FLETE            </th> <th> <?= number_format(Session::Get('flete_real_calculado')); ?> </th>  </tr>
  <tr> <th>( - ) SUBSIDIO FLETE         </th> <th> <?= number_format($_vr_ppto_fletes) ;?> </th>  </tr>
  <tr> <th>( + ) RECAUDO                </th> <th> <?= number_format(Session::Get('recaudo_total')) ;?> </th>  </tr>
  <tr> <th>( + ) VR.FIJO RECAUDO        </th> <th> <?= number_format(Session::Get('py_vr_adicional'));?></th>  </tr>
  <tr> <th>( - ) ANTICIPO RECAUDO       </th> <th> <?= number_format($_vr_anticipo_recaudo) ;?>  </th>  </tr>
  <tr> <th>( = ) VALOR TOTAL TRANSPORTE </th> <th> <?= number_format(Session::Get('Vr_Transporte'));?>  </th>  </tr>
</table>



<!--
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
           <div class="cont-table">
              <table class="table table-bordered table-hover">
                   <thead>

                   </thead>

                   <tbody>

																				<tr><td></td></tr>



                                        <tr>
                                        <td class="cuerpo-tabla">vr_diferencia_recaudo</td>
                                        <td class="cuerpo-tabla"><?=   Session::Get('vr_diferencia_recaudo'); ?> </td>
                                        </tr>

                                        <tr>
                                        <td class="cuerpo-tabla">minimo compra TA</td>
                                        <td class="cuerpo-tabla"><?=   Session::Get('minimo_compras_productos_ta'); ?> </td>
                                        </tr>

                                        <tr>
                                        <td class="cuerpo-tabla">idtercero_pedido </td>
                                        <td class="cuerpo-tabla"><?=   Session::Get('idtercero_pedido'); ?> </td>
                                        </tr>

                                        <tr>
                                        <td class="cuerpo-tabla">idtipo_plan_compras </td>
                                        <td class="cuerpo-tabla"><?=   Session::Get('idtipo_plan_compras'); ?> </td>
                                        </tr>

                                        <tr>
                                        <td class="cuerpo-tabla">usuario_viene_del_registro </td>
                                        <td class="cuerpo-tabla"><?=   Session::Get('usuario_viene_del_registro'); ?> </td>
                                        </tr>



                                        <tr>
                                        <td class="cuerpo-tabla">idtercero_presenta </td>
                                        <td class="cuerpo-tabla"><?=   Session::Get('idtercero_presenta'); ?> </td>
                                        </tr>


																				<tr>
																				<td class="cuerpo-tabla">SUB-TOTAL PEDIDO  </td>
																				<td class="cuerpo-tabla"><?=  number_format(Session::Get('sub_total_pedido_Otros')); ?> </td>
																				</tr>

																				<tr>
																				<td class="cuerpo-tabla">FLETE COBRADO  </td>
																				<td class="cuerpo-tabla"> </td>
																				</tr>
																				<tr>
																							<td class="cuerpo-tabla">TRANSPORTADORA  </td>
																							<td class="cuerpo-tabla"><?=  number_format(Session::Get('id_transportadora')); ?> </td>
																				 </tr>
                                        <tr>
                                              <td class="cuerpo-tabla">TIPO DESPACHO  </td>

                                         </tr>
																				<tr>
																							<td class="cuerpo-tabla">PRESUPUESTO FLETES  </td>
																							<td class="cuerpo-tabla"><?=  number_format(Session::Get('presupuesto_flete_otros')); ?> </td>
																				 </tr>
																				<tr>
																							<td class="cuerpo-tabla">VALOR RECAUDO  </td>
																							<td class="cuerpo-tabla"><?=  number_format(Session::Get('Vr_Recaudo')); ?> </td>
																				 </tr>
																				<tr>
																							<td class="cuerpo-tabla">VALOR TRANSPORTE  </td>
																							<td class="cuerpo-tabla"><?=  number_format(Session::Get('Vr_Transporte')); ?> </td>
																				 </tr>
																				<tr>
																							<td class="cuerpo-tabla">VALOR TOTAL PEDIDO </td>
																							<td class="cuerpo-tabla"><?=  number_format(Session::Get('Vr_Total_Pedido_Real')); ?> </td>
																				 </tr>
                                        <tr>
                                              <td class="cuerpo-tabla">BASE IVA </td>
                                              <td class="cuerpo-tabla"><?=  number_format(Session::Get('Vr_Base_Iva')); ?> </td>
                                         </tr>
                                        <tr>
                                              <td class="cuerpo-tabla">VALOR TOTAL DEL PEDIDO </td>
                                              <td class="cuerpo-tabla"><?=  number_format(Session::Get('Vr_Total_Pedido_Real')); ?> </td>
                                         </tr>



                   </tbody>
              </table>



-->
