
<?php
		    	$datos = 	Session::Get('Fletes_Cobrados_Transportadoras');
?>


    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
           <div class="cont-table"><!-- Contenedor -->
              <table class="table table-bordered table-hover">
                   <thead><!-- Cabezera tabla -->
                       <tr>
                            FLETES Y VALORES
                            <th class="titulo-tabla">Nombre Empresa</th>
                            <th class="titulo-tabla">Tipo Tarifa</th>
                            <th class="titulo-tabla">Valor</th>

                       </tr>
                   </thead>

                   <tbody><!-- Cuerpo -->
                   	<?php foreach ($datos as $dato) :?>
                       <tr>
                           <td class="cuerpo-tabla"> Id <?= $dato['idtercero'] . ' '. $dato['transportador'] ;?>  </td>
                           <td class="cuerpo-tabla"><?= $dato['tipo_tarifa'] ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $dato['valor_flete']) ;?> </td>

                       </tr>
																				<?php endforeach ;?>
																				<<tr></tr>
																				<tr>
																				<td class="cuerpo-tabla">SUB-TOTAL PEDIDO  </td>
																				<td class="cuerpo-tabla"><?=  number_format(Session::Get('sub_total_pedido_Otros')); ?> </td>
																				</tr>
																				<tr>
																				<td class="cuerpo-tabla">FLETE COBRADO  </td>
																				<td class="cuerpo-tabla"><?=  number_format(Session::Get('flete_cobrado_otros')); ?> </td>
																				</tr>
																				<tr>
																							<td class="cuerpo-tabla">TRANSPORTADORA  </td>
																							<td class="cuerpo-tabla"><?=  number_format(Session::Get('id_transportadora')); ?> </td>
																				 </tr>
																				<tr>
																							<td class="cuerpo-tabla">PRESUPUESTO FLETES  </td>
																							<td class="cuerpo-tabla"><?=  number_format(Session::Get('presupuesto_flete_otros')); ?> </td>
																				 </tr>
																				<tr>
																							<td class="cuerpo-tabla">VALOR RECAUDO  </td>
																							<td class="cuerpo-tabla"><?=  number_format(Session::Get('Vr_Recaudo')); ?> </td>
																				 </tr>
																				<tr>
																							<td class="cuerpo-tabla">VALOR TRANSPORTE  </td>
																							<td class="cuerpo-tabla"><?=  number_format(Session::Get('Vr_Transporte')); ?> </td>
																				 </tr>
																				<tr>
																							<td class="cuerpo-tabla">VALOR TOTAL PEDIDO </td>
																							<td class="cuerpo-tabla"><?=  number_format(Session::Get('Vr_Total_Pedido_Real')); ?> </td>
																				 </tr>
                   </tbody>
              </table>

           </div>
        </div>
    </div>


