<?php
    if ( !isset($_SESSION['carrito'] )) {
      echo "<br><br><h1> AGREGUE PRODUCTOS AL CARRO PARA REALIZAR LAS VERIFICACIONES </h1><br><br><br><br>";
      exit;
    }
?>

<?php
  $carro = $_SESSION['carrito'] ;
?>


<div class="row" style ='padding-top : 150px ;'>
        <div class="col-lg-12 col-md-12 col-sm-12">
<table class="table table-bordered table-hover">
                   <thead><!-- Cabezera tabla -->
                       <tr>
                            PRODUCTOS Y VALORES

                            <th class="titulo-tabla">Producto</th>
                            <th class="titulo-tabla">Presen.</th>
                            <th class="titulo-tabla">Frag.</th>
                            <th class="titulo-tabla">Cant.</th>
                            <th class="titulo-tabla">Peso(gr)</th>
                            <th class="titulo-tabla">Peso Tot.</th>
                            <th class="titulo-tabla">Iva</th>
                            <th class="titulo-tabla">Grupo</th>
                            <th class="titulo-tabla">$ Vr.Unit</th>
                            <th class="titulo-tabla">$ Vta.Total</th>
                            <th class="titulo-tabla">$ Declarado</th>
                            <th class="titulo-tabla">% Sub.Flete</th>
                            <th class="titulo-tabla">$ Vr.Sub.Flete</th>
                            <th class="titulo-tabla">$ Vr.Ant.Rcdo</th>

                       </tr>
                   </thead>

                   <tbody><!-- Cuerpo -->
                   <?php
                      $_peso_gramos_total          = 0;
                      $_precio_total_produc_pedido = 0;
                      $_valor_declarado            = 0;
                      $_vr_ppto_fletes             = 0;
                      $_vr_anticipo_recaudo        = 0;
                   ?>
                   	<?php foreach ($carro as $productos) :?>
                       <tr>
                           <td class="cuerpo-tabla"><?= $productos['nom_producto'] ;?>  </td>
                           <td class="cuerpo-tabla"><?= $productos['nompresentacion'] ;?>  </td>
                           <td class="cuerpo-tabla"><?= $productos['fragancia'] ;?>  </td>
                           <td class="cuerpo-tabla"><?= $productos['cantidad'] ;?>  </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['peso_gramos']) ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['peso_gramos_total'] ) ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['iva']  )."%" ;?> </td>
                           <td class="cuerpo-tabla"><?=  $productos['codigo_grupo'] ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['precio_unitario_produc_pedido']) ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['precio_total_produc_pedido'] ) ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['valor_declarado'] ) ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['ppto_fletes']*100 )."%" ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['vr_ppto_fletes'] ) ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $productos['vr_anticipo_recaudo'] ) ;?> </td>
                           <?php
                              $_peso_gramos_total          = $_peso_gramos_total          + $productos['peso_gramos_total'] ;
                              $_precio_total_produc_pedido = $_precio_total_produc_pedido + $productos['precio_total_produc_pedido'];
                              $_valor_declarado            = $_valor_declarado            + $productos['valor_declarado'];
                              $_vr_ppto_fletes             = $_vr_ppto_fletes             + $productos['vr_ppto_fletes'];
                              $_vr_anticipo_recaudo        = $_vr_anticipo_recaudo        + $productos['vr_anticipo_recaudo'];
                            ?>
                       </tr>
										<?php endforeach ;?>
                    <tr>
                        <th class="titulo-tabla" colspan="5"></th>
                        <th class="titulo-tabla"><?= number_format($_peso_gramos_total) ;?> </th>
                        <th class="titulo-tabla" colspan="3"></th>
                        <th class="titulo-tabla"><?= number_format($_precio_total_produc_pedido) ;?></th>
                        <th class="titulo-tabla"><?= number_format($_valor_declarado) ;?> </th>
                        <th class="titulo-tabla"></th>
                        <th class="titulo-tabla"><?= number_format($_vr_ppto_fletes) ;?> </th>
                        <th class="titulo-tabla"><?= number_format($_vr_anticipo_recaudo) ;?></th>
                    </tr>

                   </tbody>
              </table>
</div>

<?php if ( Session::Get('cumple_condicion_cpras_tron_industial') == TRUE ){
    $Cumple_Condiciones = 'SI';
  }else{
    $Cumple_Condiciones = 'NO';
  }
  ?>

<div class="col-lg-6">

  <table class="table table-bordered table-hover" style ="width : 80%;">
   <thead><!-- Cabezera tabla -->
       <tr>
            <th class="titulo-tabla" colspan="3">REDETRANS</th>
            <th class="titulo-tabla" colspan="3">SERVIENTREGA</th>
       </tr>
       <tr>
          <th class="titulo-tabla"></th>
          <th class="titulo-tabla">COURRIER</th>
          <th class="titulo-tabla">CARGA</th>
          <th class="titulo-tabla">PREMIER</th>
          <th class="titulo-tabla">INDUSTRIAL</th>
       </tr>
       <tr>
          <th class="titulo-tabla">Vr. Flete</th>
          <th> <?= number_format(Session::Get('REDETRANS_COURRIER_flete'));?>  </th>
          <th> <?= number_format(Session::Get('REDETRANS_CARGA_valor_flete'));?>  </th>
          <th> <?= number_format(Session::Get('SERVIENTREGA_PREMIER_valor_flete'));?>  </th>
          <th> <?= number_format(Session::Get('SERVIENTREGA_INDUS_valor_flete'));?>  </th>
       </tr>
       <tr>
          <th class="titulo-tabla">Vr. Seguro</th>
          <th> <?=  number_format(Session::Get('REDETRANS_COURRIER_seguro')) ;?></th>
          <th> <?=  number_format(Session::Get('REDETRANS_CARGA_seguro')) ;?></th>
          <th> <?= number_format(Session::Get('SERVIENTREGA_PREMIER_seguro'));?>  </th>
          <th> <?= number_format(Session::Get('SERVIENTREGA_INDUS_seguro'));?>  </th>
       </tr>

       <tr>
          <th class="titulo-tabla">Flete Total</th>
          <th> <?= number_format( Session::Get('REDETRANS_COURRIER_flete_total')) ;?> </th>
          <th> <?= number_format( Session::Get('REDETRANS_CARGA_flete_total')) ;?> </th>
          <th> <?= number_format(Session::Get('SERVIENTREGA_PREMIER_flete_total'));?>  </th>
          <th> <?= number_format(Session::Get('SERVIENTREGA_INDUS_flete_total'));?>  </th>
       </tr>
   </thead>
</table>
      CUMPLE CONDICIONES PARA PRECIO ESPECIAL TRON : <strong><?= $Cumple_Condiciones ;?></strong> <br /><br />
      VALORES A MOSTRAR EN EL CARRITO DE COMPRA : <br /><br />
      &nbsp; &nbsp;&nbsp;VR.TRANSPORTE COMPRADOR OCASIONAL  [ COURRIER ] : <?= number_format(Session::Get('VR_TRANS_OCASI_COURIER')) ;?> <br />
      &nbsp;&nbsp;&nbsp; VR.TRANSPORTE COMPRADOR AMIGO TRON [ COURRIER ] : <?= number_format(Session::Get('VR_TRANS_TRON_COURIER') );?> <br /><br />
      &nbsp; &nbsp;&nbsp;VR.TRANSPORTE COMPRADOR OCASIONAL  [ CARGA ] : <?= number_format(Session::Get('VR_TRANS_OCASI_CARGA')) ;?> <br />
      &nbsp;&nbsp;&nbsp; VR.TRANSPORTE COMPRADOR AMIGO TRON [ CARGA ] : <?= number_format(Session::Get('VR_TRANS_TRON_CARGA') );?> <br />
</div>



<br>

<div class="col-lg-6">
  <table class="table table-bordered table-hover" style ="width : 80%;">
  <thead>
    <tr>
      <th>TOTALES</th>
      <th> COURRIER -- <?= Session::Get('nommcipio_despacho') ;?> <br /> <?=   Session::Get('COURRIER_TIPO_TARIFA'); ?> </th>
      <th> CARGA -- <?= Session::Get('nommcipio_despacho') ;?> <br /> <?=   Session::Get('CARGA_TIPO_TARIFA'); ?> </th>
    </tr>
  </thead>
    <tr>
        <th>NÚMERO UNIDADES</th>
        <th> <?= number_format(Session::Get('COURRIER_UNIDADES')); ?></th>
        <th><?= number_format(Session::Get('CARGA_UNIDADES')); ?></th>
  </tr>
  <tr>
        <th>VALOR TOTAL FLETE</th>
        <th> <?= number_format(Session::Get('COURRIER_FLETES')); ?> </th>
        <th> <?= number_format(Session::Get('CARGA_FLETES')); ?> </th>
  </tr>

  <tr>
      <th>( - ) SUBSIDIO FLETE         </th>
      <th> <?= number_format(Session::Get('COURRIER_SUBSIDIO_FLETE')); ?> </th>
      <th><?= number_format(Session::Get('CARGA_SUBSIDIO_FLETE')); ?></th>
  </tr>
  <tr>
      <th>= FLETE REAL         </th>
      <th> <?= number_format(Session::Get('COURRIER_FLETE_REAL')); ?> </th>
      <th> <?= number_format(Session::Get('CARGA_FLETE_REAL')); ?> </th>
  </tr>

  <tr>
      <th>( + ) RECAUDO                </th>
      <th colspan="2"> <?= number_format(Session::Get('recaudo_total')) ;?> </th>

  </tr>
  <tr>
      <th>( + ) VR.FIJO RECAUDO        </th>
      <th colspan="2"> <?= number_format(Session::Get('py_vr_adicional'));?>

  </th>  </tr>
  <tr>
    <th>( - ) ANTICIPO RECAUDO       </th>
    <th colspan="2"> <?= number_format($_vr_anticipo_recaudo) ;?>  </th>

    </tr>
    <tr>
    <th>( = ) VALOR TOTAL TRANSPORTE </th>
    <th>   <?= number_format( Session::Get('COURRIER_VR_TRANSPORTE_FINAL') ); ?>  </th>
    <th>   <?= number_format( Session::Get('CARGA_VR_TRANSPORTE_FINAL') ); ?>  </th>
    </tr>
</table>
</div>

</div>
