
<?php
		    	$datos = 	Session::Get('Fletes_Cobrados_Transportadoras');
          if (isset($_SESSION['carrito'])){
		    	$carro = $_SESSION['carrito'];
        }
        else
        {
          echo "<br><br><h1> AGREGUE PRODUCTO AL CARRO PARA REALIZAR LAS VERIFICACIONES </h1><br><br><br><br>";		    	//Debug::Mostrar($carro);
          exit;
        }

?>

<!--
 <?php
  Debug::Mostrar(Session::Get('fecha_hora_acepta_convenio'));
?>

-->




    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
           <div class="cont-table"><!-- Contenedor -->
              <table class="table table-bordered table-hover">
                   <thead><!-- Cabezera tabla -->
                       <tr>
                            FLETES Y VALORES ..... CIUDAD DE DESTINO : <strong><?= Session::Get('nommcipio_despacho') ;?></strong>
                            <th class="titulo-tabla">Nombre Empresa</th>
                            <th class="titulo-tabla">Tipo Tarifa</th>
                            <th class="titulo-tabla">Valor</th>

                       </tr>
                   </thead>

                   <tbody><!-- Cuerpo -->
                   	<?php foreach ($datos as $dato) :?>
                       <tr>
                           <td class="cuerpo-tabla"> Id <?= $dato['idtercero'] . ' '. $dato['transportador'] ;?>  </td>
                           <td class="cuerpo-tabla"><?= $dato['tipo_tarifa'] ;?> </td>
                           <td class="cuerpo-tabla"><?= number_format( $dato['valor_flete']) ;?> </td>

                       </tr>
																				<?php endforeach ;?>
																				<tr><td></td></tr>
                                        <tr>
                                        <td class="cuerpo-tabla">FLETE COBRADO  </td>
                                        <td class="cuerpo-tabla"><?=  number_format(Session::Get('flete_cobrado_otros')); ?> </td>
                                        </tr>

                                        <tr>
                                              <td class="cuerpo-tabla">PRESUPUESTO FLETES  </td>
                                              <td class="cuerpo-tabla"><?=  number_format(Session::Get('presupuesto_flete_otros')); ?> </td>
                                         </tr>
                                        <tr>
                                        <td class="cuerpo-tabla">RECAUDO TOTAL </td>
                                              <td class="cuerpo-tabla"><?=  number_format(Session::Get('recaudo_total')); ?> </td>
                                         </tr>

                                        <td class="cuerpo-tabla">PRESUPUESTO DE RECAUDO </td>
                                              <td class="cuerpo-tabla"><?=  number_format(Session::Get('presupuesto_recaudo')); ?> </td>
                                         </tr>

                                        <td class="cuerpo-tabla">VR. RECAUDO PAGADO POR EL CLIENTE </td>
                                              <td class="cuerpo-tabla"><?=  number_format(Session::Get('vr_diferencia_recaudo')); ?> </td>
                                         </tr>

                                        <tr>
                                              <td class="cuerpo-tabla">VALOR TRANSPORTE  </td>
                                              <td class="cuerpo-tabla"><?=  number_format(Session::Get('Vr_Transporte')); ?> </td>
                                         </tr>

                                        <tr>
                                              <td class="cuerpo-tabla">COMBOS Y/O KITS ELIMINADOS </td>
                                              <td class="cuerpo-tabla"><?=  number_format(Session::Get('kit_combos_eliminados')); ?> </td>
                                         </tr>


                   </tbody>
              </table>





